package com.IClrawler.TaskInfo

import com.IClrawler.TaskInfo.Cric_DataInfo

/**
 * Created by dell on 2015/10/10.
 */
class Cric_TaskLink(task: Cric_DataInfo) {
  var hongGuanMonthStart = "2000年01月"
  var hongGuanMonthEnd = "2015年12月"

  var hongGuanYearStart = "1978年"
  var hongGuanYearEnd = "2015年"

  var hgQuarterStart = "1978年1季度"
  var hgQuarterEnd = "2015年4季度"


  var quarterlyDate = ""
  var weekDate = "2015年52周:2016年01周"
  var monthDate = "2015年09月:2015年12月"
  var dayDate = "2015-12-14:2015-01-04"

  def quarterLandLink = {
    val quarterLandLink = List(
      List("{\"Dims\":[{\"Key\":\"MarketMonitor.Dim.LandTime.BiddingDateQuarter\",\"Value\":\"" + quarterlyDate + "\"},{\"Key\":\"MarketMonitor.Dim.ProjectRegion.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"MarketMonitor.Dim.LandTime.BiddingDateQuarter\"],\"Columns\":[],\"Outputs\":\"成交幅数,成交占地面积,成交建筑面积,成交总价,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"reportcenter\"}" + ";152008" + ";土地" + ";季供求" + ";全市",
        "{\"Dims\":[{\"Key\":\"MarketMonitor.Dim.LandTime.ListingDateQuarter\",\"Value\":\"" + quarterlyDate + "\"},{\"Key\":\"MarketMonitor.Dim.ProjectRegion.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"MarketMonitor.Dim.LandTime.ListingDateQuarter\"],\"Columns\":[],\"Outputs\":\"供应幅数,供应占地面积,供应建筑面积,,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"reportcenter\"}"
      ),
      List("{\"Dims\":[{\"Key\":\"MarketMonitor.Dim.ProjectRegion.Region\",\"Value\":\"\"},{\"Key\":\"MarketMonitor.Dim.LandTime.BiddingDateQuarter\",\"Value\":\"" + quarterlyDate + "\"},{\"Key\":\"MarketMonitor.Dim.ProjectRegion.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"MarketMonitor.Dim.LandTime.BiddingDateQuarter\"],\"Columns\":[\"MarketMonitor.Dim.ProjectRegion.Region\"],\"Outputs\":\"成交幅数,成交占地面积,成交建筑面积,成交总价,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"reportcenter\"}" + ";152009" + ";土地" + ";季供求" + ";各区域",
        "{\"Dims\":[{\"Key\":\"MarketMonitor.Dim.ProjectRegion.Region\",\"Value\":\"\"},{\"Key\":\"MarketMonitor.Dim.LandTime.ListingDateQuarter\",\"Value\":\"" + quarterlyDate + "\"},{\"Key\":\"MarketMonitor.Dim.ProjectRegion.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"MarketMonitor.Dim.LandTime.ListingDateQuarter\"],\"Columns\":[\"MarketMonitor.Dim.ProjectRegion.Region\"],\"Outputs\":\"供应幅数,供应占地面积,供应建筑面积,,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"reportcenter\"}"
      ),
      List("{\"Dims\":[{\"Key\":\"MarketMonitor.Dim.ProjectRegion.Circle\",\"Value\":\"\"},{\"Key\":\"MarketMonitor.Dim.LandTime.BiddingDateQuarter\",\"Value\":\"" + quarterlyDate + "\"},{\"Key\":\"MarketMonitor.Dim.ProjectRegion.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"MarketMonitor.Dim.LandTime.BiddingDateQuarter\"],\"Columns\":[\"MarketMonitor.Dim.ProjectRegion.Circle\"],\"Outputs\":\"成交幅数,成交占地面积,成交建筑面积,成交总价,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"reportcenter\"}" + ";152010" + ";土地" + ";季供求" + ";各环线",
        "{\"Dims\":[{\"Key\":\"MarketMonitor.Dim.ProjectRegion.Circle\",\"Value\":\"\"},{\"Key\":\"MarketMonitor.Dim.LandTime.ListingDateQuarter\",\"Value\":\"" + quarterlyDate + "\"},{\"Key\":\"MarketMonitor.Dim.ProjectRegion.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"MarketMonitor.Dim.LandTime.ListingDateQuarter\"],\"Columns\":[\"MarketMonitor.Dim.ProjectRegion.Circle\"],\"Outputs\":\"供应幅数,供应占地面积,供应建筑面积,,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"reportcenter\"}"
      ),
      List("{\"Dims\":[{\"Key\":\"MarketMonitor.Dim.LandTime.BiddingDateQuarter\",\"Value\":\"" + quarterlyDate + "\"},{\"Key\":\"MarketMonitor.Dim.ProjectRegion.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"MarketMonitor.Dim.LandTime.BiddingDateQuarter\"],\"Columns\":[\"MarketMonitor.Dim.LandStep.PlotRatio\"],\"Outputs\":\"成交幅数,成交占地面积,成交建筑面积,成交总价,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"reportcenter\"}" + ";152011" + ";土地" + ";季供求" + ";各容积率",
        "{\"Dims\":[{\"Key\":\"MarketMonitor.Dim.LandTime.ListingDateQuarter\",\"Value\":\"" + quarterlyDate + "\"},{\"Key\":\"MarketMonitor.Dim.ProjectRegion.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"MarketMonitor.Dim.LandTime.ListingDateQuarter\"],\"Columns\":[\"MarketMonitor.Dim.LandStep.PlotRatio\"],\"Outputs\":\"供应幅数,供应占地面积,供应建筑面积,,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"reportcenter\"}"
      ),
      List("{\"Dims\":[{\"Key\":\"MarketMonitor.Dim.LandTime.BiddingDateQuarter\",\"Value\":\"" + quarterlyDate + "\"},{\"Key\":\"MarketMonitor.Dim.ProjectRegion.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"MarketMonitor.Dim.LandTime.BiddingDateQuarter\"],\"Columns\":[\"MarketMonitor.Dim.LandStep.LandAreaStep\"],\"Outputs\":\"成交幅数,成交占地面积,成交建筑面积,成交总价,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"reportcenter\"}" + ";152012" + ";土地" + ";季供求" + ";各占地面积",
        "{\"Dims\":[{\"Key\":\"MarketMonitor.Dim.LandTime.ListingDateQuarter\",\"Value\":\"" + quarterlyDate + "\"},{\"Key\":\"MarketMonitor.Dim.ProjectRegion.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"MarketMonitor.Dim.LandTime.ListingDateQuarter\"],\"Columns\":[\"MarketMonitor.Dim.LandStep.LandAreaStep\"],\"Outputs\":\"供应幅数,供应占地面积,供应建筑面积,,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"reportcenter\"}"
      )
    )
    quarterLandLink

  }

  def quarterLink = {
    val quarterLink = List(
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.RoomUsage\",\"Value\":\"商品房\"},{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"全市月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.Time.Quarter\",\"Value\":\"" + quarterlyDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Quarter\"],\"Columns\":[],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\"}" + ";150008" + ";商品房" + ";季供求" + ";全市",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.RoomUsage\",\"Value\":\"商品房\"},{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"区域月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.MonthData.Region\",\"Value\":\"\"},{\"Key\":\"StatisticCenter.Dim.Time.Quarter\",\"Value\":\"" + quarterlyDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Quarter\"],\"Columns\":[\"StatisticCenter.Dim.MonthData.Region\"],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\"}" + ";150009" + ";商品房" + ";季供求" + ";各区域",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.RoomUsage\",\"Value\":\"商品房\"},{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"环线月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.MonthData.Region\",\"Value\":\"\"},{\"Key\":\"StatisticCenter.Dim.Time.Quarter\",\"Value\":\"" + quarterlyDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Quarter\"],\"Columns\":[\"StatisticCenter.Dim.MonthData.Region\"],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\"}" + ";150010" + ";商品房" + ";季供求" + ";各环线",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"分用途月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.Time.Quarter\",\"Value\":\"" + quarterlyDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Quarter\"],\"Columns\":[\"StatisticCenter.Dim.MonthData.House\"],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\"}" + ";150011" + ";商品房" + ";季供求" + ";各物业属性",

      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.RoomUsage\",\"Value\":\"商品住宅（不含政策性用房）\"},{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"全市月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.Time.Quarter\",\"Value\":\"" + quarterlyDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Quarter\"],\"Columns\":[],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\",\"MdxSource\":2}" + ";151013" + ";商品住宅" + ";季供求" + ";全市",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.RoomUsage\",\"Value\":\"商品住宅（不含政策性用房）\"},{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"区域月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.MonthData.Region\",\"Value\":\"\"},{\"Key\":\"StatisticCenter.Dim.Time.Quarter\",\"Value\":\"" + quarterlyDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Quarter\"],\"Columns\":[\"StatisticCenter.Dim.MonthData.Region\"],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\",\"MdxSource\":2}" + ";151014" + ";商品住宅" + ";季供求" + ";各区域",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.RoomUsage\",\"Value\":\"商品住宅（不含政策性用房）\"},{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"板块月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.MonthData.Region\",\"Value\":\"\"},{\"Key\":\"StatisticCenter.Dim.Time.Quarter\",\"Value\":\"" + quarterlyDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Quarter\"],\"Columns\":[\"StatisticCenter.Dim.MonthData.Region\"],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\",\"MdxSource\":2}" + ";151015" + ";商品住宅" + ";季供求" + ";各版块",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.RoomUsage\",\"Value\":\"商品住宅（不含政策性用房）\"},{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"环线月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.MonthData.Region\",\"Value\":\"\"},{\"Key\":\"StatisticCenter.Dim.Time.Quarter\",\"Value\":\"" + quarterlyDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Quarter\"],\"Columns\":[\"StatisticCenter.Dim.MonthData.Region\"],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\",\"MdxSource\":2}" + ";151016" + ";商品住宅" + ";季供求" + ";各环线",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"分用途月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.Time.Quarter\",\"Value\":\"" + quarterlyDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Quarter\"],\"Columns\":[\"StatisticCenter.Dim.MonthData.Home\"],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\",\"MdxSource\":2}" + ";151017" + ";商品住宅" + ";季供求" + ";各物业属性",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.RoomUsage\",\"Value\":\"商品住宅（不含政策性用房）\"},{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"分户型月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.Time.Quarter\",\"Value\":\"" + quarterlyDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Quarter\"],\"Columns\":[\"StatisticCenter.Dim.MonthData.RoomType\"],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\",\"MdxSource\":2}" + ";151018" + ";商品住宅" + ";季供求" + ";各房型",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.RoomUsage\",\"Value\":\"商品住宅（不含政策性用房）\"},{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"面积段月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.Time.Quarter\",\"Value\":\"" + quarterlyDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Quarter\"],\"Columns\":[\"StatisticCenter.Dim.MonthData.AreaStep\"],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\",\"MdxSource\":2}" + ";151019" + ";商品住宅" + ";季供求" + ";各面积段",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.RoomUsage\",\"Value\":\"商品住宅（不含政策性用房）\"},{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"单价价格段月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.Time.Quarter\",\"Value\":\"" + quarterlyDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Quarter\"],\"Columns\":[\"StatisticCenter.Dim.MonthData.PriceStep\"],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\",\"MdxSource\":2}" + ";151020" + ";商品住宅" + ";季供求" + ";各单价段",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.RoomUsage\",\"Value\":\"商品住宅（不含政策性用房）\"},{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"总价价格段月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.Time.Quarter\",\"Value\":\"" + quarterlyDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Quarter\"],\"Columns\":[\"StatisticCenter.Dim.MonthData.AllMoneyStep\"],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\",\"MdxSource\":2}" + ";151021" + ";商品住宅" + ";季供求" + ";各总价段",

      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.RoomUsage\",\"Value\":\"商业\"},{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"全市月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.Time.Quarter\",\"Value\":\"" + quarterlyDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Quarter\"],\"Columns\":[],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\"}" + ";153010" + ";商业" + ";季供求" + ";全市",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.RoomUsage\",\"Value\":\"商业\"},{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"区域月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.MonthData.Region\",\"Value\":\"\"},{\"Key\":\"StatisticCenter.Dim.Time.Quarter\",\"Value\":\"" + quarterlyDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Quarter\"],\"Columns\":[\"StatisticCenter.Dim.MonthData.Region\"],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\"}" + ";153011" + ";商业" + ";季供求" + ";各区域",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.RoomUsage\",\"Value\":\"商业\"},{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"环线月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.MonthData.Region\",\"Value\":\"\"},{\"Key\":\"StatisticCenter.Dim.Time.Quarter\",\"Value\":\"" + quarterlyDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Quarter\"],\"Columns\":[\"StatisticCenter.Dim.MonthData.Region\"],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\"}" + ";153012" + ";商业" + ";季供求" + ";各环线",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.RoomUsage\",\"Value\":\"商业\"},{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"面积段月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.Time.Quarter\",\"Value\":\"" + quarterlyDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Quarter\"],\"Columns\":[\"StatisticCenter.Dim.MonthData.AreaStep\"],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\"}" + ";153013" + ";商业" + ";季供求" + ";各面积段",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.RoomUsage\",\"Value\":\"商业\"},{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"单价价格段月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.Time.Quarter\",\"Value\":\"" + quarterlyDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Quarter\"],\"Columns\":[\"StatisticCenter.Dim.MonthData.PriceStep\"],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\"}" + ";153014" + ";商业" + ";季供求" + ";各单价段",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.RoomUsage\",\"Value\":\"商业\"},{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"总价价格段月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.Time.Quarter\",\"Value\":\"" + quarterlyDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Quarter\"],\"Columns\":[\"StatisticCenter.Dim.MonthData.AllMoneyStep\"],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\"}" + ";153015" + ";商业" + ";季供求" + ";各总价段",

      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.RoomUsage\",\"Value\":\"办公\"},{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"全市月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.Time.Quarter\",\"Value\":\"" + quarterlyDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Quarter\"],\"Columns\":[],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\"}" + ";154010" + ";办公" + ";季供求" + ";全市",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.RoomUsage\",\"Value\":\"办公\"},{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"区域月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.MonthData.Region\",\"Value\":\"\"},{\"Key\":\"StatisticCenter.Dim.Time.Quarter\",\"Value\":\"" + quarterlyDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Quarter\"],\"Columns\":[\"StatisticCenter.Dim.MonthData.Region\"],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\"}" + ";154011" + ";办公" + ";季供求" + ";各区域",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.RoomUsage\",\"Value\":\"办公\"},{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"环线月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.MonthData.Region\",\"Value\":\"\"},{\"Key\":\"StatisticCenter.Dim.Time.Quarter\",\"Value\":\"" + quarterlyDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Quarter\"],\"Columns\":[\"StatisticCenter.Dim.MonthData.Region\"],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\"}" + ";154012" + ";办公" + ";季供求" + ";各环线",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.RoomUsage\",\"Value\":\"办公\"},{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"面积段月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.Time.Quarter\",\"Value\":\"" + quarterlyDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Quarter\"],\"Columns\":[\"StatisticCenter.Dim.MonthData.AreaStep\"],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\"}" + ";154013" + ";办公" + ";季供求" + ";各面积段",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.RoomUsage\",\"Value\":\"办公\"},{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"单价价格段月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.Time.Quarter\",\"Value\":\"" + quarterlyDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Quarter\"],\"Columns\":[\"StatisticCenter.Dim.MonthData.PriceStep\"],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\"}" + ";154014" + ";办公" + ";季供求" + ";各单价段",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.RoomUsage\",\"Value\":\"办公\"},{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"总价价格段月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.Time.Quarter\",\"Value\":\"" + quarterlyDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Quarter\"],\"Columns\":[\"StatisticCenter.Dim.MonthData.AllMoneyStep\"],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\"}" + ";154015" + ";办公" + ";季供求" + ";各总价段"
    )
    quarterLink
  }

  def daySesondLink = {
    val daySesondLink = List(
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.DailyDataSecondHand.RoomUsage\",\"Value\":\"商品房\"},{\"Key\":\"StatisticCenter.Dim.DailyDataSecondHand.DataType\",\"Value\":\"全市\"},{\"Key\":\"StatisticCenter.Dim.Time.Day\",\"Value\":\"" + dayDate + "\"},{\"Key\":\"StatisticCenter.Dim.DailyDataSecondHand.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Day\"],\"Columns\":[],\"Outputs\":\"可售面积,可售套数,供应面积,供应套数,成交面积,成交套数,成交均价,成交金额\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"DailyDataSecondHand\"}" + ";150021" + ";商品房" + ";日供求" + ";全市二手房",

      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.DailyDataSecondHand.RoomUsage\",\"Value\":\"商品住宅\"},{\"Key\":\"StatisticCenter.Dim.DailyDataSecondHand.DataType\",\"Value\":\"全市\"},{\"Key\":\"StatisticCenter.Dim.Time.Day\",\"Value\":\"" + dayDate + "\"},{\"Key\":\"StatisticCenter.Dim.DailyDataSecondHand.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Day\"],\"Columns\":[],\"Outputs\":\"可售面积,可售套数,供应面积,供应套数,成交面积,成交套数,成交均价,成交金额\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"DailyDataSecondHand\",\"MdxSource\":2}" + ";151036" + ";商品房" + ";日供求" + ";全市二手房"
    )
    daySesondLink
  }

  def dayLink = {
    def dayLink = List(
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.DailyData.RoomUsage\",\"Value\":\"商品房\"},{\"Key\":\"StatisticCenter.Dim.Time.Day\",\"Value\":\"" + dayDate + "\"},{\"Key\":\"StatisticCenter.Dim.DailyData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Day\"],\"Columns\":[],\"Outputs\":\"可售面积,可售套数,供应面积,供应套数,成交面积,成交套数,成交均价,成交金额\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"DailyData\"}" + ";150002" + ";商品房" + ";日供求" + ";全市",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.DailyDataRegion.RoomUsage\",\"Value\":\"商品房\"},{\"Key\":\"StatisticCenter.Dim.DailyDataRegion.Region\",\"Value\":\"\"},{\"Key\":\"StatisticCenter.Dim.Time.Day\",\"Value\":\"" + dayDate + "\"},{\"Key\":\"StatisticCenter.Dim.DailyDataRegion.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Day\"],\"Columns\":[\"StatisticCenter.Dim.DailyDataRegion.Region\"],\"Outputs\":\"可售面积,可售套数,供应面积,供应套数,成交面积,成交套数,成交均价,成交金额\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"DailyDataRegion\"}" + ";150022" + ";商品房" + ";日供求" + ";各区域",

      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.DailyData.RoomUsage\",\"Value\":\"商品住宅\"},{\"Key\":\"StatisticCenter.Dim.Time.Day\",\"Value\":\"" + dayDate + "\"},{\"Key\":\"StatisticCenter.Dim.DailyData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Day\"],\"Columns\":[],\"Outputs\":\"可售面积,可售套数,供应面积,供应套数,成交面积,成交套数,成交均价,成交金额\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"DailyData\",\"MdxSource\":2}" + ";151002" + ";商品住宅" + ";日供求" + ";全市",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.DailyDataRegion.RoomUsage\",\"Value\":\"商品住宅\"},{\"Key\":\"StatisticCenter.Dim.DailyDataRegion.Region\",\"Value\":\"\"},{\"Key\":\"StatisticCenter.Dim.Time.Day\",\"Value\":\"" + dayDate + "\"},{\"Key\":\"StatisticCenter.Dim.DailyDataRegion.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Day\"],\"Columns\":[\"StatisticCenter.Dim.DailyDataRegion.Region\"],\"Outputs\":\"可售面积,可售套数,供应面积,供应套数,成交面积,成交套数,成交均价,成交金额\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"DailyDataRegion\",\"MdxSource\":2}" + ";151037" + ";商品住宅" + ";日供求" + ";各区域",

      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.DailyData.RoomUsage\",\"Value\":\"商业\"},{\"Key\":\"StatisticCenter.Dim.Time.Day\",\"Value\":\"" + dayDate + "\"},{\"Key\":\"StatisticCenter.Dim.DailyData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Day\"],\"Columns\":[],\"Outputs\":\"可售面积,可售套数,供应面积,供应套数,成交面积,成交套数,成交均价,成交金额\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"DailyData\"}" + ";153002" + ";商业" + ";日供求" + ";全市",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.DailyDataRegion.RoomUsage\",\"Value\":\"商业\"},{\"Key\":\"StatisticCenter.Dim.DailyDataRegion.Region\",\"Value\":\"\"},{\"Key\":\"StatisticCenter.Dim.Time.Day\",\"Value\":\"" + dayDate + "\"},{\"Key\":\"StatisticCenter.Dim.DailyDataRegion.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Day\"],\"Columns\":[\"StatisticCenter.Dim.DailyDataRegion.Region\"],\"Outputs\":\"可售面积,可售套数,供应面积,供应套数,成交面积,成交套数,成交均价,成交金额\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"DailyDataRegion\"}" + ";153082" + ";商业" + ";日供求" + ";各区域",

      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.DailyData.RoomUsage\",\"Value\":\"办公\"},{\"Key\":\"StatisticCenter.Dim.Time.Day\",\"Value\":\"" + dayDate + "\"},{\"Key\":\"StatisticCenter.Dim.DailyData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Day\"],\"Columns\":[],\"Outputs\":\"可售面积,可售套数,供应面积,供应套数,成交面积,成交套数,成交均价,成交金额\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"DailyData\"}" + ";154002" + ";办公" + ";日供求" + ";全市",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.DailyDataRegion.RoomUsage\",\"Value\":\"办公\"},{\"Key\":\"StatisticCenter.Dim.DailyDataRegion.Region\",\"Value\":\"\"},{\"Key\":\"StatisticCenter.Dim.Time.Day\",\"Value\":\"" + dayDate + "\"},{\"Key\":\"StatisticCenter.Dim.DailyDataRegion.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Day\"],\"Columns\":[\"StatisticCenter.Dim.DailyDataRegion.Region\"],\"Outputs\":\"可售面积,可售套数,供应面积,供应套数,成交面积,成交套数,成交均价,成交金额\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"DailyDataRegion\"}" + ";154082" + ";办公" + ";日供求" + ";各区域"
    )
    dayLink
  }

  def weekSecondLink = {
    val weekSecondLink = List(
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.DailyDataSecondHand.RoomUsage\",\"Value\":\"商品房\"},{\"Key\":\"StatisticCenter.Dim.DailyDataSecondHand.DataType\",\"Value\":\"全市\"},{\"Key\":\"StatisticCenter.Dim.Time.Week\",\"Value\":\"" + weekDate + "\"},{\"Key\":\"StatisticCenter.Dim.DailyDataSecondHand.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Week\"],\"Columns\":[],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"DailyDataSecondHand\"}" + ";150024" + ";商品房" + ";周供应" + ";全市二手房",

      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.DailyDataSecondHand.RoomUsage\",\"Value\":\"商品住宅\"},{\"Key\":\"StatisticCenter.Dim.DailyDataSecondHand.DataType\",\"Value\":\"全市\"},{\"Key\":\"StatisticCenter.Dim.Time.Week\",\"Value\":\"" + weekDate + "\"},{\"Key\":\"StatisticCenter.Dim.DailyDataSecondHand.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Week\"],\"Columns\":[],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"DailyDataSecondHand\",\"MdxSource\":2}" + ";151039" + ";商品房" + ";周供应" + ";全市二手房"
    )
    weekSecondLink
  }

  def weekLink = {
    val weekLink = List(
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.DailyData.RoomUsage\",\"Value\":\"商品房\"},{\"Key\":\"StatisticCenter.Dim.Time.Week\",\"Value\":\"" + weekDate + "\"},{\"Key\":\"StatisticCenter.Dim.DailyData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Week\"],\"Columns\":[],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"DailyData\"}" + ";150003" + ";商品房" + ";周供求" + ";全市",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.DailyDataRegion.RoomUsage\",\"Value\":\"商品房\"},{\"Key\":\"StatisticCenter.Dim.DailyDataRegion.Region\",\"Value\":\"\"},{\"Key\":\"StatisticCenter.Dim.Time.Week\",\"Value\":\"" + weekDate + "\"},{\"Key\":\"StatisticCenter.Dim.DailyDataRegion.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Week\"],\"Columns\":[\"StatisticCenter.Dim.DailyDataRegion.Region\"],\"Outputs\":\"成交面积,成交套数\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"DailyDataRegion\"}" + ";150025" + ";商品房" + ";周供求" + ";各区域",

      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.DailyData.RoomUsage\",\"Value\":\"商品住宅\"},{\"Key\":\"StatisticCenter.Dim.Time.Week\",\"Value\":\"" + weekDate + "\"},{\"Key\":\"StatisticCenter.Dim.DailyData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Week\"],\"Columns\":[],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"DailyData\",\"MdxSource\":2}" + ";151003" + ";商品住宅" + ";周供求" + ";全市",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.DailyDataRegion.RoomUsage\",\"Value\":\"商品住宅\"},{\"Key\":\"StatisticCenter.Dim.DailyDataRegion.Region\",\"Value\":\"\"},{\"Key\":\"StatisticCenter.Dim.Time.Week\",\"Value\":\"" + weekDate + "\"},{\"Key\":\"StatisticCenter.Dim.DailyDataRegion.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Week\"],\"Columns\":[\"StatisticCenter.Dim.DailyDataRegion.Region\"],\"Outputs\":\"成交面积,成交套数\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"DailyDataRegion\",\"MdxSource\":2}" + ";151040" + ";商品住宅" + ";周供求" + ";各区域",

      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.DailyData.RoomUsage\",\"Value\":\"商业\"},{\"Key\":\"StatisticCenter.Dim.Time.Week\",\"Value\":\"" + weekDate + "\"},{\"Key\":\"StatisticCenter.Dim.DailyData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Week\"],\"Columns\":[],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"DailyData\"}" + ";153003" + ";商业" + ";周供求" + ";全市",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.DailyDataRegion.RoomUsage\",\"Value\":\"商业\"},{\"Key\":\"StatisticCenter.Dim.DailyDataRegion.Region\",\"Value\":\"\"},{\"Key\":\"StatisticCenter.Dim.Time.Week\",\"Value\":\"" + weekDate + "\"},{\"Key\":\"StatisticCenter.Dim.DailyDataRegion.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Week\"],\"Columns\":[\"StatisticCenter.Dim.DailyDataRegion.Region\"],\"Outputs\":\"成交面积,成交套数\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"DailyDataRegion\"}" + ";153031" + ";商业" + ";周供求" + ";各区域",

      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.DailyData.RoomUsage\",\"Value\":\"办公\"},{\"Key\":\"StatisticCenter.Dim.Time.Week\",\"Value\":\"" + weekDate + "\"},{\"Key\":\"StatisticCenter.Dim.DailyData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Week\"],\"Columns\":[],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"DailyData\"}" + ";154003" + ";办公" + ";周供求" + ";全市",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.DailyDataRegion.RoomUsage\",\"Value\":\"办公\"},{\"Key\":\"StatisticCenter.Dim.DailyDataRegion.Region\",\"Value\":\"\"},{\"Key\":\"StatisticCenter.Dim.Time.Week\",\"Value\":\"" + weekDate + "\"},{\"Key\":\"StatisticCenter.Dim.DailyDataRegion.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Week\"],\"Columns\":[\"StatisticCenter.Dim.DailyDataRegion.Region\"],\"Outputs\":\"成交面积,成交套数\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"DailyDataRegion\"}" + ";154031" + ";办公" + ";周供求" + ";各区域"
    )
    weekLink
  }

  def hongGuanMonthLink = {
    val hongGuanMonthList = List(
      "国民经济核算;固定资产投资额;固定资产投资额;月度;" + task.num_city + ";" + hongGuanMonthStart + ";" + hongGuanMonthEnd + "",
      "国民经济核算;对外经济贸易;进出口贸易;月度;" + task.num_city + ";" + hongGuanMonthStart + ";" + hongGuanMonthEnd + "",
      "房地产开发;开发投资额;房地产开发投资额;月度;" + task.num_city + ";" + hongGuanMonthStart + ";" + hongGuanMonthEnd + "",
      "房地产开发;施工面积;房地产施工面积;月度;" + task.num_city + ";" + hongGuanMonthStart + ";" + hongGuanMonthEnd + "",
      "房地产开发;新开工面积;房地产新开工面积;月度;" + task.num_city + ";" + hongGuanMonthStart + ";" + hongGuanMonthEnd + "",
      "房地产开发;竣工面积;房地产竣工面积;月度;" + task.num_city + ";" + hongGuanMonthStart + ";" + hongGuanMonthEnd + "",
      "房地产开发;资金来源合计;资金来源合计;月度;" + task.num_city + ";" + hongGuanMonthStart + ";" + hongGuanMonthEnd + "",
      "房地产开发;土地开发情况;土地开发情况;月度;" + task.num_city + ";" + hongGuanMonthStart + ";" + hongGuanMonthEnd + "",
      "房地产销售;商品房销售面积;商品房销售面积;月度;" + task.num_city + ";" + hongGuanMonthStart + ";" + hongGuanMonthEnd + "",
      "房地产销售;商品房销售金额;商品房销售金额;月度;" + task.num_city + ";" + hongGuanMonthStart + ";" + hongGuanMonthEnd + "",
      "房地产销售;商品房销售价格;商品房销售价格;月度;" + task.num_city + ";" + hongGuanMonthStart + ";" + hongGuanMonthEnd + ""
    )
    hongGuanMonthList
  }

  def hongGuanLink = {
    val hongGuanList = List(
      "国民经济核算;城市总值指标;国内生产总值;季度;" + task.num_city + ";"+hgQuarterStart+";"+hgQuarterEnd+"",
      "国民经济核算;城市总值指标;国内生产总值;年度;" + task.num_city + ";"+hongGuanYearStart+";"+hongGuanYearEnd+"",
      "国民经济核算;人口;人口;年度;" + task.num_city + ";"+hongGuanYearStart+";"+hongGuanYearEnd+"",

      "国民经济核算;居民生活水平;居民生活水平;年度;" + task.num_city + ";"+hongGuanYearStart+";"+hongGuanYearEnd+"",
      "国民经济核算;居民收支与储蓄;居民收支与储蓄;年度;" + task.num_city + ";"+hongGuanYearStart+";"+hongGuanYearEnd+"",

      "国民经济核算;固定资产投资额;固定资产投资额;季度;" + task.num_city + ";"+hgQuarterStart+";"+hgQuarterEnd+"",
      "国民经济核算;固定资产投资额;固定资产投资额;年度;" + task.num_city + ";"+hongGuanYearStart+";"+hongGuanYearEnd+"",

      "国民经济核算;财政税收;财政收入与支出;年度;" + task.num_city + ";"+hongGuanYearStart+";"+hongGuanYearEnd+"",

      "国民经济核算;对外经济贸易;进出口贸易;季度;" + task.num_city + ";"+hgQuarterStart+";"+hgQuarterEnd+"",
      "国民经济核算;对外经济贸易;进出口贸易;年度;" + task.num_city + ";"+hongGuanYearStart+";"+hongGuanYearEnd+"",

      "房地产开发;开发投资额;房地产开发投资额;年度;" + task.num_city + ";"+hongGuanYearStart+";"+hongGuanYearEnd+"",

      "房地产开发;施工面积;房地产施工面积;年度;" + task.num_city + ";"+hongGuanYearStart+";"+hongGuanYearEnd+"",

      "房地产开发;新开工面积;房地产新开工面积;年度;" + task.num_city + ";"+hongGuanYearStart+";"+hongGuanYearEnd+"",

      "房地产开发;竣工面积;房地产竣工面积;年度;" + task.num_city + ";"+hongGuanYearStart+";"+hongGuanYearEnd+"",


      "房地产销售;商品房销售面积;商品房销售面积;年度;" + task.num_city + ";"+hongGuanYearStart+";"+hongGuanYearEnd+"",

      "房地产销售;商品房销售金额;商品房销售金额;年度;" + task.num_city + ";"+hongGuanYearStart+";"+hongGuanYearEnd+"",

      "房地产销售;商品房销售价格;商品房销售价格;年度;" + task.num_city + ";"+hongGuanYearStart+";"+hongGuanYearEnd+"",

      "房地产企业;房地产资金来源;房地产资金来源;年度;" + task.num_city + ";"+hongGuanYearStart+";"+hongGuanYearEnd+""
    )
    hongGuanList
  }

  def monthLandLink = {
    val monthLandList = List(
      List("{\"Dims\":[{\"Key\":\"MarketMonitor.Dim.LandTime.BiddingDateMonth\",\"Value\":\"" + monthDate + "\"},{\"Key\":\"MarketMonitor.Dim.ProjectRegion.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"MarketMonitor.Dim.LandTime.BiddingDateMonth\"],\"Columns\":[],\"Outputs\":\"成交幅数,成交占地面积,成交建筑面积,成交总价,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"reportcenter\"}" + ";152002" + ";土地" + ";月供求" + ";全市",
        "{\"Dims\":[{\"Key\":\"MarketMonitor.Dim.LandTime.ListingDateMonth\",\"Value\":\"" + monthDate + "\"},{\"Key\":\"MarketMonitor.Dim.ProjectRegion.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"MarketMonitor.Dim.LandTime.ListingDateMonth\"],\"Columns\":[],\"Outputs\":\"供应幅数,供应占地面积,供应建筑面积,,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"reportcenter\"}"),
      List("{\"Dims\":[{\"Key\":\"MarketMonitor.Dim.ProjectRegion.Region\",\"Value\":\"\"},{\"Key\":\"MarketMonitor.Dim.LandTime.BiddingDateMonth\",\"Value\":\"" + monthDate + "\"},{\"Key\":\"MarketMonitor.Dim.ProjectRegion.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"MarketMonitor.Dim.LandTime.BiddingDateMonth\"],\"Columns\":[\"MarketMonitor.Dim.ProjectRegion.Region\"],\"Outputs\":\"成交幅数,成交占地面积,成交建筑面积,成交总价,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"reportcenter\"}" + ";152003" + ";土地" + ";月供求" + ";各区域",
        "{\"Dims\":[{\"Key\":\"MarketMonitor.Dim.ProjectRegion.Region\",\"Value\":\"\"},{\"Key\":\"MarketMonitor.Dim.LandTime.ListingDateMonth\",\"Value\":\"" + monthDate + "\"},{\"Key\":\"MarketMonitor.Dim.ProjectRegion.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"MarketMonitor.Dim.LandTime.ListingDateMonth\"],\"Columns\":[\"MarketMonitor.Dim.ProjectRegion.Region\"],\"Outputs\":\"供应幅数,供应占地面积,供应建筑面积,,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"reportcenter\"}"),
      List("{\"Dims\":[{\"Key\":\"MarketMonitor.Dim.ProjectRegion.Circle\",\"Value\":\"\"},{\"Key\":\"MarketMonitor.Dim.LandTime.BiddingDateMonth\",\"Value\":\"" + monthDate + "\"},{\"Key\":\"MarketMonitor.Dim.ProjectRegion.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"MarketMonitor.Dim.LandTime.BiddingDateMonth\"],\"Columns\":[\"MarketMonitor.Dim.ProjectRegion.Circle\"],\"Outputs\":\"成交幅数,成交占地面积,成交建筑面积,成交总价,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"reportcenter\"}" + ";152004" + ";土地" + ";月供求" + ";各环线",
        "{\"Dims\":[{\"Key\":\"MarketMonitor.Dim.ProjectRegion.Circle\",\"Value\":\"\"},{\"Key\":\"MarketMonitor.Dim.LandTime.ListingDateMonth\",\"Value\":\"" + monthDate + "\"},{\"Key\":\"MarketMonitor.Dim.ProjectRegion.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"MarketMonitor.Dim.LandTime.ListingDateMonth\"],\"Columns\":[\"MarketMonitor.Dim.ProjectRegion.Circle\"],\"Outputs\":\"供应幅数,供应占地面积,供应建筑面积,,环比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"reportcenter\"}"),
      List("{\"Dims\":[{\"Key\":\"MarketMonitor.Dim.LandTime.BiddingDateMonth\",\"Value\":\"" + monthDate + "\"},{\"Key\":\"MarketMonitor.Dim.ProjectRegion.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"MarketMonitor.Dim.LandTime.BiddingDateMonth\"],\"Columns\":[\"MarketMonitor.Dim.LandStep.PlotRatio\"],\"Outputs\":\"成交幅数,成交占地面积,成交建筑面积,成交总价,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"reportcenter\"}" + ";152005" + ";土地" + ";月供求" + ";各容积率",
        "{\"Dims\":[{\"Key\":\"MarketMonitor.Dim.LandTime.ListingDateMonth\",\"Value\":\"" + monthDate + "\"},{\"Key\":\"MarketMonitor.Dim.ProjectRegion.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"MarketMonitor.Dim.LandTime.ListingDateMonth\"],\"Columns\":[\"MarketMonitor.Dim.LandStep.PlotRatio\"],\"Outputs\":\"供应幅数,供应占地面积,供应建筑面积,,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"reportcenter\"}"),
      List("{\"Dims\":[{\"Key\":\"MarketMonitor.Dim.LandTime.BiddingDateMonth\",\"Value\":\"" + monthDate + "\"},{\"Key\":\"MarketMonitor.Dim.ProjectRegion.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"MarketMonitor.Dim.LandTime.BiddingDateMonth\"],\"Columns\":[\"MarketMonitor.Dim.LandStep.LandAreaStep\"],\"Outputs\":\"成交幅数,成交占地面积,成交建筑面积,成交总价,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"reportcenter\"}" + ";152006" + ";土地" + ";月供求" + ";各土地面积",
        "{\"Dims\":[{\"Key\":\"MarketMonitor.Dim.LandTime.ListingDateMonth\",\"Value\":\"" + monthDate + "\"},{\"Key\":\"MarketMonitor.Dim.ProjectRegion.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"MarketMonitor.Dim.LandTime.ListingDateMonth\"],\"Columns\":[\"MarketMonitor.Dim.LandStep.LandAreaStep\"],\"Outputs\":\"供应幅数,供应占地面积,供应建筑面积,,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"reportcenter\"}")
    )
    monthLandList
  }

  def monthLink = {
    val monthLinkList = List(
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.RoomUsage\",\"Value\":\"商品房\"},{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"全市月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.Time.Month\",\"Value\":\"" + monthDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Month\"],\"Columns\":[],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\"}" + ";150004" + ";商品房" + ";月供求" + ";全市",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.RoomUsage\",\"Value\":\"商品房\"},{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"区域月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.MonthData.Region\",\"Value\":\"\"},{\"Key\":\"StatisticCenter.Dim.Time.Month\",\"Value\":\"" + monthDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Month\"],\"Columns\":[\"StatisticCenter.Dim.MonthData.Region\"],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\"}" + ";150005" + ";商品房" + ";月供求" + ";各区域",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.RoomUsage\",\"Value\":\"商品房\"},{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"环线月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.MonthData.Region\",\"Value\":\"\"},{\"Key\":\"StatisticCenter.Dim.Time.Month\",\"Value\":\"" + monthDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Month\"],\"Columns\":[\"StatisticCenter.Dim.MonthData.Region\"],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\"}" + ";150006" + ";商品房" + ";月供求" + ";各环线",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"分用途月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.Time.Month\",\"Value\":\"" + monthDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Month\"],\"Columns\":[\"StatisticCenter.Dim.MonthData.House\"],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\"}" + ";150007" + ";商品房" + ";月供求" + ";各物业属性",

      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.RoomUsage\",\"Value\":\"商品住宅（不含政策性用房）\"},{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"全市月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.Time.Month\",\"Value\":\"" + monthDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Month\"],\"Columns\":[],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\",\"MdxSource\":2}" + ";151004" + ";商品住宅" + ";月供求" + ";全市",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.RoomUsage\",\"Value\":\"商品住宅（不含政策性用房）\"},{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"区域月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.MonthData.Region\",\"Value\":\"\"},{\"Key\":\"StatisticCenter.Dim.Time.Month\",\"Value\":\"" + monthDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Month\"],\"Columns\":[\"StatisticCenter.Dim.MonthData.Region\"],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\",\"MdxSource\":2}" + ";151005" + ";商品住宅" + ";月供求" + ";各区域",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.RoomUsage\",\"Value\":\"商品住宅（不含政策性用房）\"},{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"板块月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.MonthData.Region\",\"Value\":\"\"},{\"Key\":\"StatisticCenter.Dim.Time.Month\",\"Value\":\"" + monthDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Month\"],\"Columns\":[\"StatisticCenter.Dim.MonthData.Region\"],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\",\"MdxSource\":2}" + ";151006" + ";商品住宅" + ";月供求" + ";各板块",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.RoomUsage\",\"Value\":\"商品住宅（不含政策性用房）\"},{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"环线月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.MonthData.Region\",\"Value\":\"\"},{\"Key\":\"StatisticCenter.Dim.Time.Month\",\"Value\":\"" + monthDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Month\"],\"Columns\":[\"StatisticCenter.Dim.MonthData.Region\"],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\",\"MdxSource\":2}" + ";151007" + ";商品住宅" + ";月供求" + ";各环线",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"分用途月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.Time.Month\",\"Value\":\"" + monthDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Month\"],\"Columns\":[\"StatisticCenter.Dim.MonthData.Home\"],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\",\"MdxSource\":2}" + ";151008" + ";商品住宅" + ";月供求" + ";各物业属性",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.RoomUsage\",\"Value\":\"商品住宅（不含政策性用房）\"},{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"分户型月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.Time.Month\",\"Value\":\"" + monthDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Month\"],\"Columns\":[\"StatisticCenter.Dim.MonthData.RoomType\"],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\",\"MdxSource\":2}" + ";151009" + ";商品住宅" + ";月供求" + ";各房型",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.RoomUsage\",\"Value\":\"商品住宅（不含政策性用房）\"},{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"面积段月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.Time.Month\",\"Value\":\"" + monthDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Month\"],\"Columns\":[\"StatisticCenter.Dim.MonthData.AreaStep\"],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\",\"MdxSource\":2}" + ";151010" + ";商品住宅" + ";月供求" + ";各面积段",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.RoomUsage\",\"Value\":\"商品住宅（不含政策性用房）\"},{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"单价价格段月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.Time.Month\",\"Value\":\"" + monthDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Month\"],\"Columns\":[\"StatisticCenter.Dim.MonthData.PriceStep\"],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\",\"MdxSource\":2}" + ";151011" + ";商品住宅" + ";月供求" + ";各单价段",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.RoomUsage\",\"Value\":\"商品住宅（不含政策性用房）\"},{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"总价价格段月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.Time.Month\",\"Value\":\"" + monthDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Month\"],\"Columns\":[\"StatisticCenter.Dim.MonthData.AllMoneyStep\"],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\",\"MdxSource\":2}" + ";151012" + ";商品住宅" + ";月供求" + ";各总价段",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthAvailData.RoomUsage\",\"Value\":\"商品住宅\"},{\"Key\":\"StatisticCenter.Dim.Time.Month\",\"Value\":\"" + monthDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthAvailData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Month\"],\"Columns\":[],\"Outputs\":\"面积$存量面积,套数$存量套数\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthAvailData\",\"MdxSource\":2}" + ";151042" + ";商品住宅" + ";月存量" + ";全市",

      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.RoomUsage\",\"Value\":\"商业\"},{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"全市月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.Time.Month\",\"Value\":\"" + monthDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Month\"],\"Columns\":[],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\"}" + ";151304" + ";商业" + ";月供求" + ";全市",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.RoomUsage\",\"Value\":\"商业\"},{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"区域月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.MonthData.Region\",\"Value\":\"\"},{\"Key\":\"StatisticCenter.Dim.Time.Month\",\"Value\":\"" + monthDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Month\"],\"Columns\":[\"StatisticCenter.Dim.MonthData.Region\"],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\"}" + ";151005" + ";商业" + ";月供求" + ";各区域",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.RoomUsage\",\"Value\":\"商业\"},{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"环线月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.MonthData.Region\",\"Value\":\"\"},{\"Key\":\"StatisticCenter.Dim.Time.Month\",\"Value\":\"" + monthDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Month\"],\"Columns\":[\"StatisticCenter.Dim.MonthData.Region\"],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\"}" + ";151006" + ";商业" + ";月供求" + ";各环线",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.RoomUsage\",\"Value\":\"商业\"},{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"面积段月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.Time.Month\",\"Value\":\"" + monthDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Month\"],\"Columns\":[\"StatisticCenter.Dim.MonthData.AreaStep\"],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\"}" + ";151007" + ";商业" + ";月供求" + ";各面积段",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.RoomUsage\",\"Value\":\"商业\"},{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"单价价格段月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.Time.Month\",\"Value\":\"" + monthDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Month\"],\"Columns\":[\"StatisticCenter.Dim.MonthData.PriceStep\"],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\"}" + ";151008" + ";商业" + ";月供求" + ";各单价段",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.RoomUsage\",\"Value\":\"商业\"},{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"总价价格段月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.Time.Month\",\"Value\":\"" + monthDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Month\"],\"Columns\":[\"StatisticCenter.Dim.MonthData.AllMoneyStep\"],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\"}" + ";151009" + ";商业" + ";月供求" + ";各总价段",

      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.RoomUsage\",\"Value\":\"办公\"},{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"全市月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.Time.Month\",\"Value\":\"" + monthDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Month\"],\"Columns\":[],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\"}" + ";154004" + ";办公" + ";月供求" + ";全市",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.RoomUsage\",\"Value\":\"办公\"},{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"区域月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.MonthData.Region\",\"Value\":\"\"},{\"Key\":\"StatisticCenter.Dim.Time.Month\",\"Value\":\"" + monthDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Month\"],\"Columns\":[\"StatisticCenter.Dim.MonthData.Region\"],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\"}" + ";154005" + ";办公" + ";月供求" + ";各区域",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.RoomUsage\",\"Value\":\"办公\"},{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"环线月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.MonthData.Region\",\"Value\":\"\"},{\"Key\":\"StatisticCenter.Dim.Time.Month\",\"Value\":\"" + monthDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Month\"],\"Columns\":[\"StatisticCenter.Dim.MonthData.Region\"],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\"}" + ";154006" + ";办公" + ";月供求" + ";各环线",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.RoomUsage\",\"Value\":\"办公\"},{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"面积段月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.Time.Month\",\"Value\":\"" + monthDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Month\"],\"Columns\":[\"StatisticCenter.Dim.MonthData.AreaStep\"],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\"}" + ";154007" + ";办公" + ";月供求" + ";各面积段",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.RoomUsage\",\"Value\":\"办公\"},{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"单价价格段月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.Time.Month\",\"Value\":\"" + monthDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Month\"],\"Columns\":[\"StatisticCenter.Dim.MonthData.PriceStep\"],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\"}" + ";154008" + ";办公" + ";月供求" + ";各单价段",
      "{\"Dims\":[{\"Key\":\"StatisticCenter.Dim.MonthData.RoomUsage\",\"Value\":\"办公\"},{\"Key\":\"StatisticCenter.Dim.MonthData.DataType\",\"Value\":\"总价价格段月度供求汇总\"},{\"Key\":\"StatisticCenter.Dim.Time.Month\",\"Value\":\"" + monthDate + "\"},{\"Key\":\"StatisticCenter.Dim.MonthData.City\",\"Value\":\"" + task.num_city + "\"}],\"Rows\":[\"StatisticCenter.Dim.Time.Month\"],\"Columns\":[\"StatisticCenter.Dim.MonthData.AllMoneyStep\"],\"Outputs\":\"供应面积,供应套数,成交面积,成交套数,成交均价,成交金额,环比,同比\",\"RowTotal\":true,\"RowNonEmpty\":false,\"ColumnNonEmpty\":false,\"DataSource\":\"MonthData\"}" + ";154009" + ";办公" + ";月供求" + ";各总价段"

    )
    monthLinkList


  }

}