//package com.IClrawler.TaskInfo
//
///**
// * Created by dell on 2015/11/11.
// */
//class NBS_YearTaskLink {
//  List("http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A0101%22%7D%5D"+"年度指标"+"综合"+"行政区划"+"null")
//  ("http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A0102%22%7D%5D"+"年度指标"+"综合"+"人均主要工农业产品产量"+"null")
//  ("http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A010301%22%7D%5D"+"年度指标"+"综合"+"法人单位数"+"三次产业法人单位数")
//  ("http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A010302%22%7D%5D"+"年度指标"+"综合"+"法人单位数"+"分机构类型法人单位数")
//  ("http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A010303%22%7D%5D"+"年度指标"+"综合"+"法人单位数"+"分行业法人单位数")
//  ("http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A010401%22%7D%5D"+"年度指标"+"综合"+"企业法人单位数"+"按控股情况分企业法人单位数")
//  ("http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A010402%22%7D%5D"+"年度指标"+"综合"+"企业法人单位数"+"按登记注册类型分企业法人单位数")
//
//  ("http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A010501%22%7D%5D"+"年度指标"+"综合"+"民族自治地方"+"民族自治地方行政区划")
//  ("http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A010502%22%7D%5D"+"年度指标"+"综合"+"民族自治地方"+"民族自治地方人口")
//  ("http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A010503%22%7D%5D"+"年度指标"+"综合"+"民族自治地方"+"民族自治地方国内生产总值")
//  ("http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A010504%22%7D%5D"+"年度指标"+"综合"+"民族自治地方"+"民族自治地方资产投资")
//  ("http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A010505%22%7D%5D"+"年度指标"+"综合"+"民族自治地方"+"民族自治地方财政")
//  ("http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A010506%22%7D%5D"+"年度指标"+"综合"+"民族自治地方"+"民族自治地方农业")
//  ("http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A010507%22%7D%5D"+"年度指标"+"综合"+"民族自治地方"+"民族自治地方工业")
//  ("http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A010508%22%7D%5D"+"年度指标"+"综合"+"民族自治地方"+"民族自治地方建筑业")
//  ("http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A010509%22%7D%5D"+"年度指标"+"综合"+"民族自治地方"+"民族自治地方邮电运输")
//  ("http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A01050A%22%7D%5D"+"年度指标"+"综合"+"民族自治地方"+"民族自治地方国内贸易")
//  ("http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A01050B%22%7D%5D"+"年度指标"+"综合"+"民族自治地方"+"民族自治地方对外经济")
//  ("http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A01050C%22%7D%5D"+"年度指标"+"综合"+"民族自治地方"+"民族自治地方国际旅游")
//  ("http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A01050D%22%7D%5D"+"年度指标"+"综合"+"民族自治地方"+"民族自治地方金融")
//  ("http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A01050E%22%7D%5D"+"年度指标"+"综合"+"民族自治地方"+"民族自治地方教育")
//  ("http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A01050F%22%7D%5D"+"年度指标"+"综合"+"民族自治地方"+"民族自治地方出版数量")
//  ("http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A01050G%22%7D%5D"+"年度指标"+"综合"+"民族自治地方"+"民族自治地方卫生")
//  ("http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A01050H%22%7D%5D"+"年度指标"+"综合"+"民族自治地方"+"民族自治地方社会服务")
//
//  ("地级区划数","地级市数","县级区划数","市辖区数","县级市数","县数","自治县数","乡镇级区划数","镇数","乡数","街道办事处")
//  ("粮食人均占有量","棉花人均占有量","油料人均占有量","糖料人均占有量","茶叶人均产量","水果人均占有量","猪牛羊肉人均占有量","水产品人均占有量","人均原煤产量","人均原油产量","人均纱产量","人均布产量","人均机制纸及纸板产量","人均水泥产量","人均粗钢产量","人均发电量")
//  ("第一产业法人单位数","第二产业法人单位数","工业法人单位数","第三产业法人单位数")
//  ("企业法人单位数","事业法人单位数","机关法人单位数","社会团体法人单位数","其他类型机构法人单位数")
//  ("法人单位数","农、林、牧、渔业法人单位数","采矿业法人单位数","制造业法人单位数","电力、燃气及水的生产和供应业法人单位数","建筑业法人单位数","交通运输、仓储和邮政业法人单位数","信息传输、计算机服务和软件业法人单位数","批发和零售业法人单位数","住宿和餐饮业法人单位数","金融业法人单位数","房地产业法人单位数","租赁和商务服务业法人单位数","科学研究、技术服务和地质勘查业法人单位数","水利、环境和公共设施管理业法人单位数","居民服务和其他服务业法人单位数","教育业法人单位数","卫生、社会保障和社会福利业法人单位数","文化、体育和娱乐业法人单位数","公共管理和社会组织法人单位数","国际组织业法人单位数")
//  ("企业法人单位数","国有控股企业法人单位数","集体控股企业法人单位数","私人控股企业法人单位数","港、澳、台商控股企业法人单位数","外商控股企业法人单位数","其他企业法人单位数")
//  ("企业法人单位数","内资企业法人单位数","国有企业法人单位数","集体企业法人单位数","股份合作企业法人单位数","联营企业法人单位数","有限责任公司法人单位数","股份有限公司法人单位数","私营企业法人单位数","港、澳、台商投资企业法人单位数","外商投资企业单位法人单位数")
//
//  ("民族自治地方地级区划数","民族自治地方地级市数","民族自治地方自治州数","民族自治地方县级区划数","民族自治地方县级市数","民族自治地方自治县(旗)数")
//  ("民族自治地方总人口数","民族自治地方少数民族人口数","蒙古族人口数","回族人口数","藏族人口数","维吾尔族人口数","苗族人口数","彝族人口数","壮族人口数","布依族人口数","朝鲜族人口数","满族人口数","侗族人口数","瑶族人口数","白族人口数","土家族人口数","哈尼族人口数","哈萨克族人口数","傣族人口数","黎族人口数","傈僳族人口数","佤族人口数","畲族人口数","高山族人口数","拉祜族人口数","水族人口数","东乡族人口数","纳西族人口数","景颇族人口数","柯尔克孜族人口数","土族人口数","达斡尔族人口数","仫佬族人口数","羌族人口数","布朗族人口数","撒拉族人口数","毛南族人口数","仡佬族人口数","锡伯族人口数","阿昌族人口数","普米族人口数","塔吉克族人口数","怒族人口数","乌孜别克族人口数","俄罗斯族人口数","鄂温克族人口数","德昂族人口数","保安族人口数","裕固族人口数","京族人口数","塔塔尔族人口数","独龙族人口数","鄂伦春族人口数","赫哲族人口数","门巴族人口数","珞巴族人口数","基诺族人口数")
//  ("民族自治地方国内生产总值","民族自治地方第一产业增加值","民族自治地方第二产业增加值","民族自治地方第三产业增加值","民族自治地方人均地区生产总值")
//  ("民族自治地方全社会固定资产投资总额","民族自治地方国有单位固定资产投资额")
//  ("民族自治地方财政收入","民族自治地方财政支出")
//  ("民族自治地方耕地面积","民族自治地方灌溉面积","民族自治地方农林牧渔总产值","民族自治地方粮食产量","民族自治地方棉花产量","民族自治地方油料产量","民族自治地方大牲畜年底头数","民族自治地方羊年底头数","民族自治地方猪年底头数")
//  ("民族自治地方工业总产值","民族自治地方布产量","民族自治地方机制纸及纸板产量","民族自治地方成品糖产量","民族自治地方原煤产量","民族自治地方原油产量","民族自治地方发电量","民族自治地方粗钢产量","民族自治地方生铁产量","民族自治地方水泥产量","民族自治地方木材产量")
//  ("民族自治地方建筑业企业人数","民族自治地方建筑业总产值","民族自治地方施工房屋面积","民族自治地方竣工房屋面积")
//  ("民族自治地方铁路营业里程","民族自治地方公路通车里程","民族自治地方邮电业务总量","民族自治地方邮路及农村投递线路总长度")
//  ("民族自治地方社会消费品零售总额")
//  ("民族自治地方进出口总额","民族自治地方出口额","民族自治地方进口额")
//  ("民族自治地方国际游客","民族自治地方旅游外汇收入")
//  ("民族自治地方金融机构各项存款","民族自治地方金融机构各项贷款")
//  ("民族自治地方普通高等学校在校学生数","民族自治地方普通中学在校学生数","民族自治地方普通小学在校学生数","民族自治地方普通高等学校专任教师数","民族自治地方普通中学专任教师数","民族自治地方普通小学专任教师数")
//  ("民族自治地方图书出版量","民族自治地方杂志出版量","民族自治地方报纸出版量")
//  ("民族自治地方医院、卫生院数","民族自治地方医院、卫生院床位")
//  ("民族自治地方福利类收养单位床位数","民族自治地方城镇社区服务设施数","民族自治地方城乡最低生活保障人数")
//  //国民经济核算///////////////////////////////////////////
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A0201%22%7D%5D"+"年度指标"+"国民经济核算"+"国内生产总值"+"null"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020201%22%7D%5D"+"年度指标"+"国民经济核算"+"国内生产总值指数"+"国内生产总数(上年=100)"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020202%22%7D%5D"+"年度指标"+"国民经济核算"+"国内生产总值指数"+"国内生产总数(1978年=100)"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A0203%22%7D%5D"+"年度指标"+"国民经济核算"+"第三次产业构成"+"国内生产总数(1978年=100)"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A0204%22%7D"+"年度指标"+"国民经济核算"+"分行业增加值"+"国内生产总数(1978年=100)"
//
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020501%22%7D%5D"+"年度指标"+"国民经济核算"+"分行业增加值指数"+"分行业增加值指数(上年=100)"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020501%22%7D%5D"+"年度指标"+"国民经济核算"+"分行业增加值指数"+"分行业增加值指数(1978年=100)"
//
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A0206%22%7D%5D"+"年度指标"+"国民经济核算"+"分行业增加值构成"+"null"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A0209%22%7D%5D"+"年度指标"+"国民经济核算"+"三次产业贡献"+"null"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020A%22%7D%5D"+"年度指标"+"国民经济核算"+"三次产业对国内生产总值增长的拉动"+"null"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020B%22%7D%5D"+"年度指标"+"国民经济核算"+"支出发过内生产总值"+"null"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020C%22%7D%5D"+"年度指标"+"国民经济核算"+"三大需求对国内生产总值增长的贡献率和拉动"+"null"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020D%22%7D%5D"+"年度指标"+"国民经济核算"+"居民消费水平"+"null"
//
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020E0101%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出基本流量表"+"中间使用部分"+"中间使用"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020E0102%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出基本流量表"+"中间使用部分"+"农 林 牧 渔业"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020E0103%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出基本流量表"+"中间使用部分"+"采矿业"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020E0104%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出基本流量表"+"中间使用部分"+"食品 饮料制造及烟草制品业"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020E0105%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出基本流量表"+"中间使用部分"+"纺织 服装及皮革产品制造业"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020E0106%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出基本流量表"+"中间使用部分"+"其他制造业"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020E0107%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出基本流量表"+"中间使用部分"+"电力 热力及水的生产和供应业"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020E0108%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出基本流量表"+"中间使用部分"+"炼焦 燃气及石油加工业"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020E0109%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出基本流量表"+"中间使用部分"+"化学工业"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020E010A%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出基本流量表"+"中间使用部分"+"非金属矿物制造业"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020E010B%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出基本流量表"+"中间使用部分"+"金属产品制造业"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020E010C%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出基本流量表"+"中间使用部分"+"机械设备制造业"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020E010D%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出基本流量表"+"中间使用部分"+"建筑业"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020E010E%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出基本流量表"+"中间使用部分"+"运输仓储邮政 信息传输 计算机服务和软件业"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020E010F%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出基本流量表"+"中间使用部分"+"批发零售贸易 住宿和餐饮业"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020E010G%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出基本流量表"+"中间使用部分"+"房地产业 租赁和商务服务业"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020E010H%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出基本流量表"+"中间使用部分"+"金融业"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020E010I%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出基本流量表"+"中间使用部分"+"其他服务业"
//
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020E0201%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出基本流量表"+"最终使用部分"+"农村居民消费"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020E0202%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出基本流量表"+"最终使用部分"+"城镇居民消费"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020E0203%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出基本流量表"+"最终使用部分"+"居民最终消费"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020E0204%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出基本流量表"+"最终使用部分"+"政府最终消费"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020E0205%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出基本流量表"+"最终使用部分"+"最终消费"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020E0206%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出基本流量表"+"最终使用部分"+"固定资本形成总额"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020E0207%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出基本流量表"+"最终使用部分"+"存货增加"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020E0208%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出基本流量表"+"最终使用部分"+"资本形成总额"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020E0209%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出基本流量表"+"最终使用部分"+"出口"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020E020A%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出基本流量表"+"最终使用部分"+"最终使用"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020E020B%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出基本流量表"+"最终使用部分"+"进口"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020E020C%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出基本流量表"+"最终使用部分"+"其他"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020E020D%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出基本流量表"+"最终使用部分"+"总产出"
//
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020F01%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出直接消耗系数"+"农 林 牧 渔业投入产出直接消耗系数"+"null"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020F02%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出直接消耗系数"+"采矿业投入产出直接消耗系数"+"null"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020F03%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出直接消耗系数"+"食品、饮料制造及烟草制品业投入产出直接消耗系数"+"null"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020F04%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出直接消耗系数"+"纺织、服装及皮革产品制造业投入产出直接消耗系数"+"null"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020F05%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出直接消耗系数"+"其他制造业投入产出直接消耗系数"+"null"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020F06%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出直接消耗系数"+"电力、热力及水的生产和供应业投入产出直接消耗系数"+"null"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020F07%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出直接消耗系数"+"炼焦、燃气及石油加工业投入产出直接消耗系数"+"null"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020F08%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出直接消耗系数"+"化学工业投入产出直接消耗系数"+"null"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020F09%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出直接消耗系数"+"非金属矿物制品业投入产出直接消耗系数"+"null"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020F0A%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出直接消耗系数"+"金属产品制造业投入产出直接消耗系数"+"null"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020F0B%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出直接消耗系数"+"机械设备制造业投入产出直接消耗系数"+"null"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020F0C%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出直接消耗系数"+"建筑业投入产出直接消耗系数"+"null"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020F0D%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出直接消耗系数"+"运输仓储邮政、信息传输、计算机服务和软件业投入产出直接消耗系数"+"null"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020F0E%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出直接消耗系数"+"批发零售贸易、住宿和餐饮业投入产出直接消耗系数"+"null"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020F0F%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出直接消耗系数"+"房地产业、租赁和商务服务业投入产出直接消耗系数"+"null"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020F0G%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出直接消耗系数"+"金融业投入产出直接消耗系数"+"null"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020F0H%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出直接消耗系数"+"其他服务业投入产出直接消耗系数"+"null"
//
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020G01%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出完全消耗系数"+"农 林 牧 渔业投入产出直接消耗系数"+"null"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020G02%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出完全消耗系数"+"采矿业投入产出直接消耗系数"+"null"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020G03%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出完全消耗系数"+"食品、饮料制造及烟草制品业投入产出直接消耗系数"+"null"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020G04%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出完全消耗系数"+"纺织、服装及皮革产品制造业投入产出直接消耗系数"+"null"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020G05%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出完全消耗系数"+"其他制造业投入产出直接消耗系数"+"null"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020G06%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出完全消耗系数"+"电力、热力及水的生产和供应业投入产出直接消耗系数"+"null"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020G07%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出完全消耗系数"+"炼焦、燃气及石油加工业投入产出直接消耗系数"+"null"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020G08%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出完全消耗系数"+"化学工业投入产出直接消耗系数"+"null"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020G09%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出完全消耗系数"+"非金属矿物制品业投入产出直接消耗系数"+"null"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020G0A%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出完全消耗系数"+"金属产品制造业投入产出直接消耗系数"+"null"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020G0B%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出完全消耗系数"+"机械设备制造业投入产出直接消耗系数"+"null"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020G0C%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出完全消耗系数"+"建筑业投入产出直接消耗系数"+"null"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020G0D%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出完全消耗系数"+"运输仓储邮政、信息传输、计算机服务和软件业投入产出直接消耗系数"+"null"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020G0E%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出完全消耗系数"+"批发零售贸易、住宿和餐饮业投入产出直接消耗系数"+"null"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020G0F%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出完全消耗系数"+"房地产业、租赁和商务服务业投入产出直接消耗系数"+"null"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020G0G%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出完全消耗系数"+"金融业投入产出直接消耗系数"+"null"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020G0H%22%7D%5D"+"年度指标"+"国民经济核算"+"投入产出完全消耗系数"+"其他服务业投入产出直接消耗系数"+"null"
//
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020H0101%22%7D%5D"+"年度指标"+"国民经济核算"+"资金流量表(实物交易)"+"实物交易"+"资金运用"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020H0102%22%7D%5D"+"年度指标"+"国民经济核算"+"资金流量表(实物交易)"+"实物交易"+"资金来源"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020H0201%22%7D%5D"+"年度指标"+"国民经济核算"+"资金流量表(实物交易)"+"非金融企业部门"+"资金运用"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020H0202%22%7D%5D"+"年度指标"+"国民经济核算"+"资金流量表(实物交易)"+"非金融企业部门"+"资金来源"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020H0301%22%7D%5D"+"年度指标"+"国民经济核算"+"资金流量表(实物交易)"+"金融机构部门"+"资金运用"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020H0302%22%7D%5D"+"年度指标"+"国民经济核算"+"资金流量表(实物交易)"+"金融机构部门"+"资金来源"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020H0401%22%7D%5D"+"年度指标"+"国民经济核算"+"资金流量表(实物交易)"+"政府部门"+"资金运用"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020H0402%22%7D%5D"+"年度指标"+"国民经济核算"+"资金流量表(实物交易)"+"政府部门"+"资金来源"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020H0501%22%7D%5D"+"年度指标"+"国民经济核算"+"资金流量表(实物交易)"+"住户部门"+"资金运用"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020H0502%22%7D%5D"+"年度指标"+"国民经济核算"+"资金流量表(实物交易)"+"住户部门"+"资金来源"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020H0601%22%7D%5D"+"年度指标"+"国民经济核算"+"资金流量表(实物交易)"+"国内"+"资金运用"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020H0602%22%7D%5D"+"年度指标"+"国民经济核算"+"资金流量表(实物交易)"+"国内"+"资金来源"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020H0701%22%7D%5D"+"年度指标"+"国民经济核算"+"资金流量表(实物交易)"+"国外部门"+"资金运用"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020H0702%22%7D%5D"+"年度指标"+"国民经济核算"+"资金流量表(实物交易)"+"国外部门"+"资金来源"
//
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020I0101%22%7D%5D"+"年度指标"+"国民经济核算"+"资金流量表(金融交易)"+"金融交易"+"资金运用"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020I0102%22%7D%5D"+"年度指标"+"国民经济核算"+"资金流量表(金融交易)"+"金融交易"+"资金来源"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020I0201%22%7D%5D"+"年度指标"+"国民经济核算"+"资金流量表(金融交易)"+"非金融企业部门"+"资金运用"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020I0202%22%7D%5D"+"年度指标"+"国民经济核算"+"资金流量表(金融交易)"+"非金融企业部门"+"资金来源"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020I0301%22%7D%5D"+"年度指标"+"国民经济核算"+"资金流量表(金融交易)"+"金融机构"+"资金运用"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020I0302%22%7D%5D"+"年度指标"+"国民经济核算"+"资金流量表(金融交易)"+"金融机构"+"资金来源"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020I0401%22%7D%5D"+"年度指标"+"国民经济核算"+"资金流量表(金融交易)"+"政府部门"+"资金运用"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020I0402%22%7D%5D"+"年度指标"+"国民经济核算"+"资金流量表(金融交易)"+"政府部门"+"资金来源"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020I0501%22%7D%5D"+"年度指标"+"国民经济核算"+"资金流量表(金融交易)"+"住户部门"+"资金运用"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020I0502%22%7D%5D"+"年度指标"+"国民经济核算"+"资金流量表(金融交易)"+"住户部门"+"资金来源"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020I0601%22%7D%5D"+"年度指标"+"国民经济核算"+"资金流量表(金融交易)"+"国内"+"资金运用"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020I0602%22%7D%5D"+"年度指标"+"国民经济核算"+"资金流量表(金融交易)"+"国内"+"资金来源"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020I0701%22%7D%5D"+"年度指标"+"国民经济核算"+"资金流量表(金融交易)"+"国外部门"+"资金运用"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020I0702%22%7D%5D"+"年度指标"+"国民经济核算"+"资金流量表(金融交易)"+"国外部门"+"资金来源"
//
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020J0101%22%7D%5D"+"年度指标"+"国民经济核算"+"国际收支平衡表"+"差额(贷-借)"+"经常项目差额(贷-借)"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020J0102%22%7D%5D"+"年度指标"+"国民经济核算"+"国际收支平衡表"+"差额(贷-借)"+"资本和金融项目差额(贷-借)"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020J0103%22%7D%5D"+"年度指标"+"国民经济核算"+"国际收支平衡表"+"差额(贷-借)"+"储备资产差额(贷-借)"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020J0104%22%7D%5D"+"年度指标"+"国民经济核算"+"国际收支平衡表"+"差额(贷-借)"+"净误差与遗漏差额(贷-借)"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020J0201%22%7D%5D"+"年度指标"+"国民经济核算"+"国际收支平衡表"+"贷方"+"贷方经常项目"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020J0202%22%7D%5D"+"年度指标"+"国民经济核算"+"国际收支平衡表"+"贷方"+"贷方资本和金融项目"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020J0203%22%7D%5D"+"年度指标"+"国民经济核算"+"国际收支平衡表"+"贷方"+"贷方存储资产"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020J0204%22%7D%5D"+"年度指标"+"国民经济核算"+"国际收支平衡表"+"贷方"+"贷方净误差与遗漏"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020J0301%22%7D%5D"+"年度指标"+"国民经济核算"+"国际收支平衡表"+"借方"+"借方经常项目"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020J0302%22%7D%5D"+"年度指标"+"国民经济核算"+"国际收支平衡表"+"借方"+"借方资本和金融项目"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020J0303%22%7D%5D"+"年度指标"+"国民经济核算"+"国际收支平衡表"+"借方"+"借方存储资产"
//  "http://data.stats.gov.cn/easyquery.htm?m=QueryData&dbcode=hgnd&rowcode=zb&colcode=sj&wds=%5B%5D&dfwds=%5B%7B%22wdcode%22%3A%22zb%22%2C%22valuecode%22%3A%22A020J0304%22%7D%5D"+"年度指标"+"国民经济核算"+"国际收支平衡表"+"借方"+"借方误差与遗漏"
//
//  "国民总收入","国内生产总值","第一产业增加值","第二产业增加值","第三产业增加值","人均国内生产总值","国民总收入指数(上年=100)","国内生产总值指数(上年=100)","第一产业增加值指数(上年=100)","第二产业增加值指数(上年=100)","第三产业增加值指数(上年=100)","人均国内生产总值指数(上年=100)"
//  "国民总收入指数(1978年=100)","国内生产总值指数(1978年=100)","第一产业增加值指数(1978年=100)","第二产业增加值指数(1978年=100)","第三产业增加值指数(1978年=100)","人均国内生产总值指数(1978年=100)"
//  "三次产业构成-国内生产总值","三次产业构成-第一产业增加值","三次产业构成-第二产业增加值","三次产业构成-第三产业增加值"
//  "国内生产总值","农林牧渔业增加值","工业增加值","建筑业增加值","批发和零售业增加值","交通运输、仓储和邮政业增加值","住宿和餐饮业增加值","金融业增加值","房地产业增加值","其他行业增加值"
//  "国内生产总值指数(上年=100)","农林牧渔业增加值指数(上年=100)","工业增加值指数(上年=100)","建筑业增加值指数(上年=100)","批发和零售业增加值指数(上年=100)","交通运输、仓储和邮政业增加值指数(上年=100)","住宿和餐饮业增加值指数(上年=100)","金融业增加值指数(上年=100)","房地产业增加值指数(上年=100)","其他行业增加值指数(上年=100)"
//  "国内生产总值指数(1978年=100)","农林牧渔业增加值指数(1978年=100)","工业增加值指数(1978年=100)","建筑业增加值指数(1978年=100)","批发和零售业增加值指数(1978年=100)","交通运输、仓储和邮政业增加值指数(1978年=100)","住宿和餐饮业增加值指数(1978年=100)","金融业增加值指数(1978年=100)","房地产业增加值指数(1978年=100)","其他行业增加值指数(1978年=100)"
//
//  "分行业增加值构成-国内生产总值","分行业增加值构成-农林牧渔业增加值","分行业增加值构成-工业增加值","分行业增加值构成-建筑业增加值","分行业增加值构成-批发和零售业增加值","分行业增加值构成-交通运输、仓储和邮政业增加值","分行业增加值构成-住宿和餐饮业增加值","分行业增加值构成-金融业增加值","分行业增加值构成-房地产业增加值","分行业增加值构成-其他行业增加值""三次产业贡献率","第一产业对GDP的贡献率","第二产业对GDP的贡献率","第三产业对GDP的贡献率"
//  "三次产业贡献率","第一产业对GDP的贡献率","第二产业对GDP的贡献率","第三产业对GDP的贡献率"
//  "国内生产总值增长","第一产业对国内生产总值增长的拉动","第二产业对国内生产总值增长的拉动","第三产业对国内生产总值增长的拉动""资本形成总额","固定资本形成总额","存货变动","货物和服务净出口","最终消费率","资本形成率"
//  "最终消费支出对国内生产总值增长贡献率","最终消费支出对国内生产总值增长拉动","资本形成总额对国内生产总值增长贡献率","资本形成总额对国内生产总值增长拉动","货物和服务净出口对国内生产总值增长贡献率","货物和服务净出口对国内生产总值增长拉动"
//  "居民消费水平","农村居民消费水平","城镇居民消费水平","居民消费水平指数(上年=100)","农村居民消费水平指数(上年=100)","城镇居民消费水平指数(上年=100)","居民消费水平指数(1978=100)","农村居民消费水平指数(1978=100)","城镇居民消费水平指数(1978=100)"
//
//  "总投入","中间投入","农、林、牧、渔业中间投入","采矿业中间投入","食品、饮料制造及烟草制品业中间投入","纺织、服装及皮革产品制造业中间投入","其他制造业中间投入","电力、热力及水的生产和供应业中间投入","炼焦、燃气及石油加工业中间投入","化学工业中间投入","非金属矿物制品业中间投入","金属产品制造业中间投入","机械设备制造业中间投入","建筑业中间投入","运输仓储邮政、信息传输、计算机服务和软件业中间投入","批发零售贸易、住宿和餐饮业中间投入","房地产业、租赁和商务服务业中间投入","金融业中间投入","其他服务业中间投入","增加值","固定资产折旧","劳动者报酬","生产税净额","营业盈余"
//  "农、林、牧、渔业总投入","农、林、牧、渔业中间使用","农、林、牧、渔业提供给农、林、牧、渔业的中间使用","采矿业提供给农、林、牧、渔业的中间使用","食品、饮料制造及烟草制品业提供给农、林、牧、渔业的中间使用","纺织、服装及皮革产品制造业提供给农、林、牧、渔业的中间使用","其他制造业提供给农、林、牧、渔业的中间使用","电力、热力及水的生产和供应业提供给农、林、牧、渔业的中间使用","炼焦、燃气及石油加工业提供给农、林、牧、渔业的中间使用","化学工业提供给农、林、牧、渔业的中间使用","非金属矿物制品业提供给农、林、牧、渔业的中间使用","金属产品制造业提供给农、林、牧、渔业的中间使用","机械设备制造业提供给农、林、牧、渔业的中间使用","建筑业提供给农、林、牧、渔业的中间使用","运输仓储邮政、信息传输、计算机服务和软件业提供给农、林、牧、渔业的中间使用","批发零售贸易、住宿和餐饮业提供给农、林、牧、渔业的中间使用","房地产业、租赁和商务服务业提供给农、林、牧、渔业的中间使用","金融业提供给农、林、牧、渔业的中间使用","其他服务业提供给农、林、牧、渔业的中间使用","农、林、牧、渔业增加值","农、林、牧、渔业固定资产折旧","农、林、牧、渔业劳动者报酬","农、林、牧、渔业生产税净额","农、林、牧、渔业营业盈余"
//  "采矿业总投入","采矿业中间使用","农、林、牧、渔业提供给采矿业的中间使用","采矿业提供给采矿业的中间使用","食品、饮料制造及烟草制品业提供给采矿业的中间使用","纺织、服装及皮革产品制造业提供给采矿业的中间使用","其他制造业提供给采矿业的中间使用","电力、热力及水的生产和供应业提供给采矿业的中间使用","炼焦、燃气及石油加工业提供给采矿业的中间使用","化学工业提供给采矿业的中间使用","非金属矿物制品业提供给采矿业的中间使用","金属产品制造业提供给采矿业的中间使用","机械设备制造业提供给采矿业的中间使用","建筑业提供给采矿业的中间使用","运输仓储邮政、信息传输、计算机服务和软件业提供给采矿业的中间使用","批发零售贸易、住宿和餐饮业提供给采矿业的中间使用","房地产业、租赁和商务服务业提供给采矿业的中间使用","金融业提供给采矿业的中间使用","其他服务业提供给采矿业的中间使用","采矿业增加值","采矿业固定资产折旧","采矿业劳动者报酬","采矿业生产税净额","采矿业营业盈余"
//  "食品、饮料制造及烟草制品业总投入","食品、饮料制造及烟草制品业中间使用","农、林、牧、渔业提供给食品、饮料制造及烟草制品业的中间使用","采矿业提供给食品、饮料制造及烟草制品业的中间使用","食品、饮料制造及烟草制品业提供给食品、饮料制造及烟草制品业的中间使用","纺织、服装及皮革产品制造业提供给食品、饮料制造及烟草制品业的中间使用","其他制造业提供给食品、饮料制造及烟草制品业的中间使用","电力、热力及水的生产和供应业提供给食品、饮料制造及烟草制品业的中间使用","炼焦、燃气及石油加工业提供给食品、饮料制造及烟草制品业的中间使用","化学工业提供给食品、饮料制造及烟草制品业的中间使用","非金属矿物制品业提供给食品、饮料制造及烟草制品业的中间使用","金属产品制造业提供给食品、饮料制造及烟草制品业的中间使用","机械设备制造业提供给食品、饮料制造及烟草制品业的中间使用","建筑业提供给食品、饮料制造及烟草制品业的中间使用","运输仓储邮政、信息传输、计算机服务和软件业提供给食品、饮料制造及烟草制品业的中间使用","批发零售贸易、住宿和餐饮业提供给食品、饮料制造及烟草制品业的中间使用","房地产业、租赁和商务服务业提供给食品、饮料制造及烟草制品业的中间使用","金融业提供给食品、饮料制造及烟草制品业的中间使用","其他服务业提供给食品、饮料制造及烟草制品业的中间使用","食品、饮料制造及烟草制品业增加值","食品、饮料制造及烟草制品业固定资产折旧","食品、饮料制造及烟草制品业劳动者报酬","食品、饮料制造及烟草制品业生产税净额","食品、饮料制造及烟草制品业营业盈余"
//  "纺织、服装及皮革产品制造业总投入","纺织、服装及皮革产品制造业中间使用","农、林、牧、渔业提供给纺织、服装及皮革产品制造业的中间使用","采矿业提供给纺织、服装及皮革产品制造业的中间使用","食品、饮料制造及烟草制品业提供给纺织、服装及皮革产品制造业的中间使用","纺织、服装及皮革产品制造业提供给纺织、服装及皮革产品制造业的中间使用","其他制造业提供给纺织、服装及皮革产品制造业的中间使用","电力、热力及水的生产和供应业提供给纺织、服装及皮革产品制造业的中间使用","炼焦、燃气及石油加工业提供给纺织、服装及皮革产品制造业的中间使用","化学工业提供给纺织、服装及皮革产品制造业的中间使用","非金属矿物制品业提供给纺织、服装及皮革产品制造业的中间使用","金属产品制造业提供给纺织、服装及皮革产品制造业的中间使用","机械设备制造业提供给纺织、服装及皮革产品制造业的中间使用","建筑业提供给纺织、服装及皮革产品制造业的中间使用","运输仓储邮政、信息传输、计算机服务和软件业提供给纺织、服装及皮革产品制造业的中间使用","批发零售贸易、住宿和餐饮业提供给纺织、服装及皮革产品制造业的中间使用","房地产业、租赁和商务服务业提供给纺织、服装及皮革产品制造业的中间使用","金融业提供给纺织、服装及皮革产品制造业的中间使用","其他服务业提供给纺织、服装及皮革产品制造业的中间使用","纺织、服装及皮革产品制造业增加值","纺织、服装及皮革产品制造业固定资产折旧","纺织、服装及皮革产品制造业劳动者报酬","纺织、服装及皮革产品制造业生产税净额","纺织、服装及皮革产品制造业营业盈余"
//  "其他制造业总投入","其他制造业中间使用","农、林、牧、渔业提供给其他制造业的中间使用","采矿业提供给其他制造业的中间使用","食品、饮料制造及烟草制品业提供给其他制造业的中间使用","纺织、服装及皮革产品制造业提供给其他制造业的中间使用","其他制造业提供给其他制造业的中间使用","电力、热力及水的生产和供应业提供给其他制造业的中间使用","炼焦、燃气及石油加工业提供给其他制造业的中间使用","化学工业提供给其他制造业的中间使用","非金属矿物制品业提供给其他制造业的中间使用","金属产品制造业提供给其他制造业的中间使用","机械设备制造业提供给其他制造业的中间使用","建筑业提供给其他制造业的中间使用","运输仓储邮政、信息传输、计算机服务和软件业提供给其他制造业的中间使用","批发零售贸易、住宿和餐饮业提供给其他制造业的中间使用","房地产业、租赁和商务服务业提供给其他制造业的中间使用","金融业提供给其他制造业的中间使用","其他服务业提供给其他制造业的中间使用","其他制造业增加值","其他制造业固定资产折旧","其他制造业劳动者报酬","其他制造业生产税净额","其他制造业营业盈余"
//  "电力、热力及水的生产和供应业总投入","电力、热力及水的生产和供应业中间使用","农、林、牧、渔业提供给电力、热力及水的生产和供应业的中间使用","采矿业提供给电力、热力及水的生产和供应业的中间使用","食品、饮料制造及烟草制品业提供给电力、热力及水的生产和供应业的中间使用","纺织、服装及皮革产品制造业提供给电力、热力及水的生产和供应业的中间使用","其他制造业提供给电力、热力及水的生产和供应业的中间使用","电力、热力及水的生产和供应业提供给电力、热力及水的生产和供应业的中间使用","炼焦、燃气及石油加工业提供给电力、热力及水的生产和供应业的中间使用","化学工业提供给电力、热力及水的生产和供应业的中间使用","非金属矿物制品业提供给电力、热力及水的生产和供应业的中间使用","金属产品制造业提供给电力、热力及水的生产和供应业的中间使用","机械设备制造业提供给电力、热力及水的生产和供应业的中间使用","建筑业提供给电力、热力及水的生产和供应业的中间使用","运输仓储邮政、信息传输、计算机服务和软件业提供给电力、热力及水的生产和供应业的中间使用","批发零售贸易、住宿和餐饮业提供给电力、热力及水的生产和供应业的中间使用","房地产业、租赁和商务服务业提供给电力、热力及水的生产和供应业的中间使用","金融业提供给电力、热力及水的生产和供应业的中间使用","其他服务业提供给电力、热力及水的生产和供应业的中间使用","电力、热力及水的生产和供应业增加值","电力、热力及水的生产和供应业固定资产折旧","电力、热力及水的生产和供应业劳动者报酬","电力、热力及水的生产和供应业生产税净额","电力、热力及水的生产和供应业营业盈余"
//  "炼焦、燃气及石油加工业总投入","炼焦、燃气及石油加工业中间使用","农、林、牧、渔业提供给炼焦、燃气及石油加工业的中间使用","采矿业提供给炼焦、燃气及石油加工业的中间使用","食品、饮料制造及烟草制品业提供给炼焦、燃气及石油加工业的中间使用","纺织、服装及皮革产品制造业提供给炼焦、燃气及石油加工业的中间使用","其他制造业提供给炼焦、燃气及石油加工业的中间使用","电力、热力及水的生产和供应业提供给炼焦、燃气及石油加工业的中间使用","炼焦、燃气及石油加工业提供给炼焦、燃气及石油加工业的中间使用","化学工业提供给炼焦、燃气及石油加工业的中间使用","非金属矿物制品业提供给炼焦、燃气及石油加工业的中间使用","金属产品制造业提供给炼焦、燃气及石油加工业的中间使用","机械设备制造业提供给炼焦、燃气及石油加工业的中间使用","建筑业提供给炼焦、燃气及石油加工业的中间使用","运输仓储邮政、信息传输、计算机服务和软件业提供给炼焦、燃气及石油加工业的中间使用","批发零售贸易、住宿和餐饮业提供给炼焦、燃气及石油加工业的中间使用","房地产业、租赁和商务服务业提供给炼焦、燃气及石油加工业的中间使用","金融业提供给炼焦、燃气及石油加工业的中间使用","其他服务业提供给炼焦、燃气及石油加工业的中间使用","炼焦、燃气及石油加工业增加值","炼焦、燃气及石油加工业固定资产折旧","炼焦、燃气及石油加工业劳动者报酬","炼焦、燃气及石油加工业生产税净额","炼焦、燃气及石油加工业营业盈余"
//  "化学工业总投入","化学工业中间使用","农、林、牧、渔业提供给化学工业的中间使用","采矿业提供给化学工业的中间使用","食品、饮料制造及烟草制品业提供给化学工业的中间使用","纺织、服装及皮革产品制造业提供给化学工业的中间使用","其他制造业提供给化学工业的中间使用","电力、热力及水的生产和供应业提供给化学工业的中间使用","炼焦、燃气及石油加工业提供给化学工业的中间使用","化学工业提供给化学工业的中间使用","非金属矿物制品业提供给化学工业的中间使用","金属产品制造业提供给化学工业的中间使用","机械设备制造业提供给化学工业的中间使用","建筑业提供给化学工业的中间使用","运输仓储邮政、信息传输、计算机服务和软件业提供给化学工业的中间使用","批发零售贸易、住宿和餐饮业提供给化学工业的中间使用","房地产业、租赁和商务服务业提供给化学工业的中间使用","金融业提供给化学工业的中间使用","其他服务业提供给化学工业的中间使用","化学工业增加值","化学工业固定资产折旧","化学工业劳动者报酬","化学工业生产税净额","化学工业营业盈余"
//  "非金属矿物制品业总投入","非金属矿物制品业中间使用","农、林、牧、渔业提供给非金属矿物制品业的中间使用","采矿业提供给非金属矿物制品业的中间使用","食品、饮料制造及烟草制品业提供给非金属矿物制品业的中间使用","纺织、服装及皮革产品制造业提供给非金属矿物制品业的中间使用","其他制造业提供给非金属矿物制品业的中间使用","电力、热力及水的生产和供应业提供给非金属矿物制品业的中间使用","炼焦、燃气及石油加工业提供给非金属矿物制品业的中间使用","化学工业提供给非金属矿物制品业的中间使用","非金属矿物制品业提供给非金属矿物制品业的中间使用","金属产品制造业提供给非金属矿物制品业的中间使用","机械设备制造业提供给非金属矿物制品业的中间使用","建筑业提供给非金属矿物制品业的中间使用","运输仓储邮政、信息传输、计算机服务和软件业提供给非金属矿物制品业的中间使用","批发零售贸易、住宿和餐饮业提供给非金属矿物制品业的中间使用","房地产业、租赁和商务服务业提供给非金属矿物制品业的中间使用","金融业提供给非金属矿物制品业的中间使用","其他服务业提供给非金属矿物制品业的中间使用","非金属矿物制品业增加值","非金属矿物制品业固定资产折旧","非金属矿物制品业劳动者报酬","非金属矿物制品业生产税净额","非金属矿物制品业营业盈余"
//  "金属产品制造业总投入","金属产品制造业中间使用","农、林、牧、渔业提供给金属产品制造业的中间使用","采矿业提供给金属产品制造业的中间使用","食品、饮料制造及烟草制品业提供给金属产品制造业的中间使用","纺织、服装及皮革产品制造业提供给金属产品制造业的中间使用","其他制造业提供给金属产品制造业的中间使用","电力、热力及水的生产和供应业提供给金属产品制造业的中间使用","炼焦、燃气及石油加工业提供给金属产品制造业的中间使用","化学工业提供给金属产品制造业的中间使用","非金属矿物制品业提供给金属产品制造业的中间使用","金属产品制造业提供给金属产品制造业的中间使用","机械设备制造业提供给金属产品制造业的中间使用","建筑业提供给金属产品制造业的中间使用","运输仓储邮政、信息传输、计算机服务和软件业提供给金属产品制造业的中间使用","批发零售贸易、住宿和餐饮业提供给金属产品制造业的中间使用","房地产业、租赁和商务服务业提供给金属产品制造业的中间使用","金融业提供给金属产品制造业的中间使用","其他服务业提供给金属产品制造业的中间使用","金属产品制造业增加值","金属产品制造业固定资产折旧","金属产品制造业劳动者报酬","金属产品制造业生产税净额","金属产品制造业营业盈余"
//  "机械设备制造业总投入","机械设备制造业中间使用","农、林、牧、渔业提供给机械设备制造业的中间使用","采矿业提供给机械设备制造业的中间使用","食品、饮料制造及烟草制品业提供给机械设备制造业的中间使用","纺织、服装及皮革产品制造业提供给机械设备制造业的中间使用","其他制造业提供给机械设备制造业的中间使用","电力、热力及水的生产和供应业提供给机械设备制造业的中间使用","炼焦、燃气及石油加工业提供给机械设备制造业的中间使用","化学工业提供给机械设备制造业的中间使用","非金属矿物制品业提供给机械设备制造业的中间使用","金属产品制造业提供给机械设备制造业的中间使用","机械设备制造业提供给机械设备制造业的中间使用","建筑业提供给机械设备制造业的中间使用","运输仓储邮政、信息传输、计算机服务和软件业提供给机械设备制造业的中间使用","批发零售贸易、住宿和餐饮业提供给机械设备制造业的中间使用","房地产业、租赁和商务服务业提供给机械设备制造业的中间使用","金融业提供给机械设备制造业的中间使用","其他服务业提供给机械设备制造业的中间使用","机械设备制造业增加值","机械设备制造业固定资产折旧","机械设备制造业劳动者报酬","机械设备制造业生产税净额","机械设备制造业营业盈余"
//  "建筑业总投入","建筑业中间使用","农、林、牧、渔业提供给建筑业的中间使用","采矿业提供给建筑业的中间使用","食品、饮料制造及烟草制品业提供给建筑业的中间使用","纺织、服装及皮革产品制造业提供给建筑业的中间使用","其他制造业提供给建筑业的中间使用","电力、热力及水的生产和供应业提供给建筑业的中间使用","炼焦、燃气及石油加工业提供给建筑业的中间使用","化学工业提供给建筑业的中间使用","非金属矿物制品业提供给建筑业的中间使用","金属产品制造业提供给建筑业的中间使用","机械设备制造业提供给建筑业的中间使用","建筑业提供给建筑业的中间使用","运输仓储邮政、信息传输、计算机服务和软件业提供给建筑业的中间使用","批发零售贸易、住宿和餐饮业提供给建筑业的中间使用","房地产业、租赁和商务服务业提供给建筑业的中间使用","金融业提供给建筑业的中间使用","其他服务业提供给建筑业的中间使用","建筑业增加值","建筑业固定资产折旧","建筑业劳动者报酬","建筑业生产税净额","建筑业营业盈余"
//  "运输仓储邮政、信息传输、计算机服务和软件业总投入","运输仓储邮政、信息传输、计算机服务和软件业中间使用","农、林、牧、渔业提供给运输仓储邮政、信息传输、计算机服务和软件业的中间使用","采矿业提供给运输仓储邮政、信息传输、计算机服务和软件业的中间使用","食品、饮料制造及烟草制品业提供给运输仓储邮政、信息传输、计算机服务和软件业的中间使用","纺织、服装及皮革产品制造业提供给运输仓储邮政、信息传输、计算机服务和软件业的中间使用","其他制造业提供给运输仓储邮政、信息传输、计算机服务和软件业的中间使用","电力、热力及水的生产和供应业提供给运输仓储邮政、信息传输、计算机服务和软件业的中间使用","炼焦、燃气及石油加工业提供给运输仓储邮政、信息传输、计算机服务和软件业的中间使用","化学工业提供给运输仓储邮政、信息传输、计算机服务和软件业的中间使用","非金属矿物制品业提供给运输仓储邮政、信息传输、计算机服务和软件业的中间使用","金属产品制造业提供给运输仓储邮政、信息传输、计算机服务和软件业的中间使用","机械设备制造业提供给运输仓储邮政、信息传输、计算机服务和软件业的中间使用","建筑业提供给运输仓储邮政、信息传输、计算机服务和软件业的中间使用","运输仓储邮政、信息传输、计算机服务和软件业提供给运输仓储邮政、信息传输、计算机服务和软件业的中间使用","批发零售贸易、住宿和餐饮业提供给运输仓储邮政、信息传输、计算机服务和软件业的中间使用","房地产业、租赁和商务服务业提供给运输仓储邮政、信息传输、计算机服务和软件业的中间使用","金融业提供给运输仓储邮政、信息传输、计算机服务和软件业的中间使用","其他服务业提供给运输仓储邮政、信息传输、计算机服务和软件业的中间使用","运输仓储邮政、信息传输、计算机服务和软件业增加值","运输仓储邮政、信息传输、计算机服务和软件业固定资产折旧","运输仓储邮政、信息传输、计算机服务和软件业劳动者报酬","运输仓储邮政、信息传输、计算机服务和软件业生产税净额","运输仓储邮政、信息传输、计算机服务和软件业营业盈余"
//  "批发零售贸易、住宿和餐饮业总投入","批发零售贸易、住宿和餐饮业中间使用","农、林、牧、渔业提供给批发零售贸易、住宿和餐饮业的中间使用","采矿业提供给批发零售贸易、住宿和餐饮业的中间使用","食品、饮料制造及烟草制品业提供给批发零售贸易、住宿和餐饮业的中间使用","纺织、服装及皮革产品制造业提供给批发零售贸易、住宿和餐饮业的中间使用","其他制造业提供给批发零售贸易、住宿和餐饮业的中间使用","电力、热力及水的生产和供应业提供给批发零售贸易、住宿和餐饮业的中间使用","炼焦、燃气及石油加工业提供给批发零售贸易、住宿和餐饮业的中间使用","化学工业提供给批发零售贸易、住宿和餐饮业的中间使用","非金属矿物制品业提供给批发零售贸易、住宿和餐饮业的中间使用","金属产品制造业提供给批发零售贸易、住宿和餐饮业的中间使用","机械设备制造业提供给批发零售贸易、住宿和餐饮业的中间使用","建筑业提供给批发零售贸易、住宿和餐饮业的中间使用","运输仓储邮政、信息传输、计算机服务和软件业提供给批发零售贸易、住宿和餐饮业的中间使用","批发零售贸易、住宿和餐饮业提供给批发零售贸易、住宿和餐饮业的中间使用","房地产业、租赁和商务服务业提供给批发零售贸易、住宿和餐饮业的中间使用","金融业提供给批发零售贸易、住宿和餐饮业的中间使用","其他服务业提供给批发零售贸易、住宿和餐饮业的中间使用","批发零售贸易、住宿和餐饮业增加值","批发零售贸易、住宿和餐饮业固定资产折旧","批发零售贸易、住宿和餐饮业劳动者报酬","批发零售贸易、住宿和餐饮业生产税净额","批发零售贸易、住宿和餐饮业营业盈余"
//  "房地产业、租赁和商务服务业总投入","房地产业、租赁和商务服务业中间使用","农、林、牧、渔业提供给房地产业、租赁和商务服务业的中间使用","采矿业提供给房地产业、租赁和商务服务业的中间使用","食品、饮料制造及烟草制品业提供给房地产业、租赁和商务服务业的中间使用","纺织、服装及皮革产品制造业提供给房地产业、租赁和商务服务业的中间使用","其他制造业提供给房地产业、租赁和商务服务业的中间使用","电力、热力及水的生产和供应业提供给房地产业、租赁和商务服务业的中间使用","炼焦、燃气及石油加工业提供给房地产业、租赁和商务服务业的中间使用","化学工业提供给房地产业、租赁和商务服务业的中间使用","非金属矿物制品业提供给房地产业、租赁和商务服务业的中间使用","金属产品制造业提供给房地产业、租赁和商务服务业的中间使用","机械设备制造业提供给房地产业、租赁和商务服务业的中间使用","建筑业提供给房地产业、租赁和商务服务业的中间使用","运输仓储邮政、信息传输、计算机服务和软件业提供给房地产业、租赁和商务服务业的中间使用","批发零售贸易、住宿和餐饮业提供给房地产业、租赁和商务服务业的中间使用","房地产业、租赁和商务服务业提供给房地产业、租赁和商务服务业的中间使用","金融业提供给房地产业、租赁和商务服务业的中间使用","其他服务业提供给房地产业、租赁和商务服务业的中间使用","房地产业、租赁和商务服务业增加值","房地产业、租赁和商务服务业固定资产折旧","房地产业、租赁和商务服务业劳动者报酬","房地产业、租赁和商务服务业生产税净额","房地产业、租赁和商务服务业营业盈余"
//  "金融业总投入","金融业中间使用","农、林、牧、渔业提供给金融业的中间使用","采矿业提供给金融业的中间使用","食品、饮料制造及烟草制品业提供给金融业的中间使用","纺织、服装及皮革产品制造业提供给金融业的中间使用","其他制造业提供给金融业的中间使用","电力、热力及水的生产和供应业提供给金融业的中间使用","炼焦、燃气及石油加工业提供给金融业的中间使用","化学工业提供给金融业的中间使用","非金属矿物制品业提供给金融业的中间使用","金属产品制造业提供给金融业的中间使用","机械设备制造业提供给金融业的中间使用","建筑业提供给金融业的中间使用","运输仓储邮政、信息传输、计算机服务和软件业提供给金融业的中间使用","批发零售贸易、住宿和餐饮业提供给金融业的中间使用","房地产业、租赁和商务服务业提供给金融业的中间使用","金融业提供给金融业的中间使用","其他服务业提供给金融业的中间使用","金融业增加值","金融业固定资产折旧","金融业劳动者报酬","金融业生产税净额","金融业营业盈余"
//  "其他服务业总投入","其他服务业中间使用","农、林、牧、渔业提供给其他服务业的中间使用","采矿业提供给其他服务业的中间使用","食品、饮料制造及烟草制品业提供给其他服务业的中间使用","纺织、服装及皮革产品制造业提供给其他服务业的中间使用","其他制造业提供给其他服务业的中间使用","电力、热力及水的生产和供应业提供给其他服务业的中间使用","炼焦、燃气及石油加工业提供给其他服务业的中间使用","化学工业提供给其他服务业的中间使用","非金属矿物制品业提供给其他服务业的中间使用","金属产品制造业提供给其他服务业的中间使用","机械设备制造业提供给其他服务业的中间使用","建筑业提供给其他服务业的中间使用","运输仓储邮政、信息传输、计算机服务和软件业提供给其他服务业的中间使用","批发零售贸易、住宿和餐饮业提供给其他服务业的中间使用","房地产业、租赁和商务服务业提供给其他服务业的中间使用","金融业提供给其他服务业的中间使用","其他服务业提供给其他服务业的中间使用","其他服务业增加值","其他服务业固定资产折旧","其他服务业劳动者报酬","其他服务业生产税净额","其他服务业营业盈余"
//
//  "农村居民消费","农、林、牧、渔业用于农村居民消费的金额","采矿业用于农村居民消费的金额","食品、饮料制造及烟草制品业用于农村居民消费的金额","纺织、服装及皮革产品制造业用于农村居民消费的金额","其他制造业用于农村居民消费的金额","电力、热力及水的生产和供应业用于农村居民消费的金额","炼焦、燃气及石油加工业用于农村居民消费的金额","化学工业用于农村居民消费的金额","非金属矿物制品业用于农村居民消费的金额","金属产品制造业用于农村居民消费的金额","机械设备制造业用于农村居民消费的金额","建筑业用于农村居民消费的金额","运输仓储邮政、信息传输、计算机服务和软件业用于农村居民消费的金额","批发零售贸易、住宿和餐饮业用于农村居民消费的金额","房地产业、租赁和商务服务业用于农村居民消费的金额","金融业用于农村居民消费的金额","其他服务业用于农村居民消费的金额"
//  "城镇居民消费","农、林、牧、渔业用于城镇居民消费的金额","采矿业用于城镇居民消费的金额","食品、饮料制造及烟草制品业用于城镇居民消费的金额","纺织、服装及皮革产品制造业用于城镇居民消费的金额","其他制造业用于城镇居民消费的金额","电力、热力及水的生产和供应业用于城镇居民消费的金额","炼焦、燃气及石油加工业用于城镇居民消费的金额","化学工业用于城镇居民消费的金额","非金属矿物制品业用于城镇居民消费的金额","金属产品制造业用于城镇居民消费的金额","机械设备制造业用于城镇居民消费的金额","建筑业用于城镇居民消费的金额","运输仓储邮政、信息传输、计算机服务和软件业用于城镇居民消费的金额","批发零售贸易、住宿和餐饮业用于城镇居民消费的金额","房地产业、租赁和商务服务业用于城镇居民消费的金额","金融业用于城镇居民消费的金额","其他服务业用于城镇居民消费的金额"
//  "居民最终消费","农、林、牧、渔业用于居民消费的金额","采矿业用于居民消费的金额","食品、饮料制造及烟草制品业用于居民消费的金额","纺织、服装及皮革产品制造业用于居民消费的金额","其他制造业用于居民消费的金额","电力、热力及水的生产和供应业用于居民消费的金额","炼焦、燃气及石油加工业用于居民消费的金额","化学工业用于居民消费的金额","非金属矿物制品业用于居民消费的金额","金属产品制造业用于居民消费的金额","机械设备制造业用于居民消费的金额","建筑业用于居民消费的金额","运输仓储邮政、信息传输、计算机服务和软件业用于居民消费的金额","批发零售贸易、住宿和餐饮业用于居民消费的金额","房地产业、租赁和商务服务业用于居民消费的金额","金融业用于居民消费的金额","其他服务业用于居民消费的金额"
//  "政府消费","农、林、牧、渔业用于政府消费的金额","采矿业用于政府消费的金额","食品、饮料制造及烟草制品业用于政府消费的金额","纺织、服装及皮革产品制造业用于政府消费的金额","其他制造业用于政府消费的金额","电力、热力及水的生产和供应业用于政府消费的金额","炼焦、燃气及石油加工业用于政府消费的金额","化学工业用于政府消费的金额","非金属矿物制品业用于政府消费的金额","金属产品制造业用于政府消费的金额","机械设备制造业用于政府消费的金额","建筑业用于政府消费的金额","运输仓储邮政、信息传输、计算机服务和软件业用于政府消费的金额","批发零售贸易、住宿和餐饮业用于政府消费的金额","房地产业、租赁和商务服务业用于政府消费的金额","金融业用于政府消费的金额","其他服务业用于政府消费的金额"
//  "最终消费","农、林、牧、渔业用于最终消费的金额","采矿业用于最终消费的金额","食品、饮料制造及烟草制品业用于最终消费的金额","纺织、服装及皮革产品制造业用于最终消费的金额","其他制造业用于最终消费的金额","电力、热力及水的生产和供应业用于最终消费的金额","炼焦、燃气及石油加工业用于最终消费的金额","化学工业用于最终消费的金额","非金属矿物制品业用于最终消费的金额","金属产品制造业用于最终消费的金额","机械设备制造业用于最终消费的金额","建筑业用于最终消费的金额","运输仓储邮政、信息传输、计算机服务和软件业用于最终消费的金额","批发零售贸易、住宿和餐饮业用于最终消费的金额","房地产业、租赁和商务服务业用于最终消费的金额","金融业用于最终消费的金额","其他服务业用于最终消费的金额"
//  "固定资本形成总额","农、林、牧、渔业用于固定资本形成总额的金额","采矿业用于固定资本形成总额的金额","食品、饮料制造及烟草制品业用于固定资本形成总额的金额","纺织、服装及皮革产品制造业用于固定资本形成总额的金额","其他制造业用于固定资本形成总额的金额","电力、热力及水的生产和供应业用于固定资本形成总额的金额","炼焦、燃气及石油加工业用于固定资本形成总额的金额","化学工业用于固定资本形成总额的金额","非金属矿物制品业用于固定资本形成总额的金额","金属产品制造业用于固定资本形成总额的金额","机械设备制造业用于固定资本形成总额的金额","建筑业用于固定资本形成总额的金额","运输仓储邮政、信息传输、计算机服务和软件业用于固定资本形成总额的金额","批发零售贸易、住宿和餐饮业用于固定资本形成总额的金额","房地产业、租赁和商务服务业用于固定资本形成总额的金额","金融业用于固定资本形成总额的金额","其他服务业用于固定资本形成总额的金额"
//  "存货增加","农、林、牧、渔业用于存货增加的金额","采矿业用于存货增加的金额","食品、饮料制造及烟草制品业用于存货增加的金额","纺织、服装及皮革产品制造业用于存货增加的金额","其他制造业用于存货增加的金额","电力、热力及水的生产和供应业用于存货增加的金额","炼焦、燃气及石油加用于存货增加的金额","化学用于存货增加的金额","非金属矿物制品业用于存货增加的金额","金属产品制造业用于存货增加的金额","机械设备制造业用于存货增加的金额","建筑业用于存货增加的金额","运输仓储邮政、信息传输、计算机服务和软件业用于存货增加的金额","批发零售贸易、住宿和餐饮业用于存货增加的金额","房地产业、租赁和商务服务业用于存货增加的金额","金融业用于存货增加的金额","其他服务业用于存货增加的金额"
//  "资本形成总额","农、林、牧、渔业用于资本形成总额的金额","采矿业用于资本形成总额的金额","食品、饮料制造及烟草制品业用于资本形成总额的金额","纺织、服装及皮革产品制造业用于资本形成总额的金额","其他制造业用于资本形成总额的金额","电力、热力及水的生产和供应业用于资本形成总额的金额","炼焦、燃气及石油加工业用于资本形成总额的金额","化学工业用于资本形成总额的金额","非金属矿物制品业用于资本形成总额的金额","金属产品制造业用于资本形成总额的金额","机械设备制造业用于资本形成总额的金额","建筑业用于资本形成总额的金额","运输仓储邮政、信息传输、计算机服务和软件业用于资本形成总额的金额","批发零售贸易、住宿和餐饮业用于资本形成总额的金额","房地产业、租赁和商务服务业用于资本形成总额的金额","金融业用于资本形成总额的金额","其他服务业用于资本形成总额的金额"
//  "出口","农、林、牧、渔业用于出口 的金额","采矿业用于出口的金额","食品、饮料制造及烟草制品业用于出口的金额","纺织、服装及皮革产品制造业用于出口的金额","其他制造业用于出口的金额","电力、热力及水的生产和供应业用于出口的金额","炼焦、燃气及石油加工业用于出口的金额","化学工业用于出口的金额","非金属矿物制品业用于出口的金额","金属产品制造业用于出口的金额","机械设备制造业用于出口的金额","建筑业用于出口的金额","运输仓储邮政、信息传输、计算机服务和软件业用于出口的金额","批发零售贸易、住宿和餐饮业用于出口的金额","房地产业、租赁和商务服务业用于出口的金额","金融业用于出口的金额","其他服务业用于出口的金额"
//  "其他","农、林、牧、渔业用于其他的金额","采矿业用于其他的金额","食品、饮料制造及烟草制品业用于其他的金额","纺织、服装及皮革产品制造业用于其他的金额","其他制造业用于其他的金额","电力、热力及水的生产和供应业用于其他的金额","炼焦、燃气及石油加工业用于其他的金额","化学工业用于其他的金额","非金属矿物制品业用于其他的金额","金属产品制造业用于其他的金额","机械设备制造业用于其他的金额","建筑业用于其他的金额","运输仓储邮政、信息传输、计算机服务和软件业用于其他的金额","批发零售贸易、住宿和餐饮业用于其他的金额","房地产业、租赁和商务服务业用于其他的金额","金融业用于其他的金额","其他服务业用于其他的金额"
//  "总产出","农、林、牧、渔业总产出金额","采矿业总产出金额","食品、饮料制造及烟草制品业总产出金额","纺织、服装及皮革产品制造业总产出金额","其他制造业总产出金额","电力、热力及水的生产和供应业总产出金额","炼焦、燃气及石油加工业总产出金额","化学工业总产出金额","非金属矿物制品业总产出金额","金属产品制造业总产出金额","机械设备制造业总产出金额","建筑业总产出金额","运输仓储邮政、信息传输、计算机服务和软件业总产出金额","批发零售贸易、住宿和餐饮业总产出金额","房地产业、租赁和商务服务业总产出金额","金融业总产出金额","其他服务业总产出金额"
//
//  "农、林、牧、渔业总投入","农、林、牧、渔业部门生产1单位总产出对中间投入产品的消耗量","农、林、牧、渔业部门生产1单位总产出对农、林、牧、渔业部门产品的消耗量","农、林、牧、渔业部门生产1单位总产出对采矿业部门产品的消耗量","农、林、牧、渔业部门生产1单位总产出对食品、饮料制造及烟草制品业部门产品的消耗量","农、林、牧、渔业部门生产1单位总产出对纺织、服装及皮革产品制造业部门产品的消耗量","农、林、牧、渔业部门生产1单位总产出对其他制造业部门产品的消耗量","农、林、牧、渔业部门生产1单位总产出对电力、热力及水的生产和供应业部门产品的消耗量","农、林、牧、渔业部门生产1单位总产出对炼焦、燃气及石油加工业部门产品的消耗量","农、林、牧、渔业部门生产1单位总产出对化学工业部门产品的消耗量","农、林、牧、渔业部门生产1单位总产出对非金属矿物制品业部门产品的消耗量","农、林、牧、渔业部门生产1单位总产出对金属产品制造业部门产品的消耗量","农、林、牧、渔业部门生产1单位总产出对机械设备制造业部门产品的消耗量","农、林、牧、渔业部门生产1单位总产出对建筑业部门产品的消耗量","农、林、牧、渔业部门生产1单位总产出对运输仓储邮政、信息传输、计算机服务和软件业部门产品的消耗量","农、林、牧、渔业部门生产1单位总产出对批发零售贸易、住宿和餐饮业部门产品的消耗量","农、林、牧、渔业部门生产1单位总产出对房地产业、租赁和商务服务业部门产品的消耗量","农、林、牧、渔业部门生产1单位总产出对金融业部门产品的消耗量","农、林、牧、渔业部门生产1单位总产出对其他服务业部门产品的消耗量","农、林、牧、渔业部门生产1单位总产出对增加值产品的消耗量","农、林、牧、渔业部门生产1单位总产出对劳动者报酬产品的消耗量","农、林、牧、渔业部门生产1单位总产出对生产税净额产品的消耗量","农、林、牧、渔业部门生产1单位总产出对固定资产折旧产品的消耗量","农、林、牧、渔业部门生产1单位总产出对营业盈余产品的消耗量"
//  "采矿业总投入","采矿业部门生产1单位总产出对中间投入产品的消耗量","采矿业部门生产1单位总产出对农、林、牧、渔业部门产品的消耗量","采矿业部门生产1单位总产出对采矿业部门产品的消耗量","采矿业部门生产1单位总产出对食品、饮料制造及烟草制品业部门产品的消耗量","采矿业部门生产1单位总产出对纺织、服装及皮革产品制造业部门产品的消耗量","采矿业部门生产1单位总产出对其他制造业部门产品的消耗量","采矿业部门生产1单位总产出对电力、热力及水的生产和供应业部门产品的消耗量","采矿业部门生产1单位总产出对炼焦、燃气及石油加工业部门产品的消耗量","采矿业部门生产1单位总产出对化学工业部门产品的消耗量","采矿业部门生产1单位总产出对非金属矿物制品业部门产品的消耗量","采矿业部门生产1单位总产出对金属产品制造业部门产品的消耗量","采矿业部门生产1单位总产出对机械设备制造业部门产品的消耗量","采矿业部门生产1单位总产出对建筑业部门产品的消耗量","采矿业部门生产1单位总产出对运输仓储邮政、信息传输、计算机服务和软件业部门产品的消耗量","采矿业部门生产1单位总产出对批发零售贸易、住宿和餐饮业部门产品的消耗量","采矿业部门生产1单位总产出对房地产业、租赁和商务服务业部门产品的消耗量","采矿业部门生产1单位总产出对金融业部门产品的消耗量","采矿业部门生产1单位总产出对其他服务业部门产品的消耗量","采矿业部门生产1单位总产出对增加值产品的消耗量","采矿业部门生产1单位总产出对劳动者报酬产品的消耗量","采矿业部门生产1单位总产出对生产税净额产品的消耗量","采矿业部门生产1单位总产出对固定资产折旧产品的消耗量","采矿业部门生产1单位总产出对营业盈余产品的消耗量"
//  "食品、饮料制造及烟草制品业总投入","食品、饮料制造及烟草制品业部门生产1单位总产出对中间投入产品的消耗量","食品、饮料制造及烟草制品业部门生产1单位总产出对农、林、牧、渔业部门产品的消耗量","食品、饮料制造及烟草制品业部门生产1单位总产出对采矿业部门产品的消耗量","食品、饮料制造及烟草制品业部门生产1单位总产出对食品、饮料制造及烟草制品业部门产品的消耗量","食品、饮料制造及烟草制品业部门生产1单位总产出对纺织、服装及皮革产品制造业部门产品的消耗量","食品、饮料制造及烟草制品业部门生产1单位总产出对其他制造业部门产品的消耗量","食品、饮料制造及烟草制品业部门生产1单位总产出对电力、热力及水的生产和供应业部门产品的消耗量","食品、饮料制造及烟草制品业部门生产1单位总产出对炼焦、燃气及石油加工业部门产品的消耗量","食品、饮料制造及烟草制品业部门生产1单位总产出对化学工业部门产品的消耗量","食品、饮料制造及烟草制品业部门生产1单位总产出对非金属矿物制品业部门产品的消耗量","食品、饮料制造及烟草制品业部门生产1单位总产出对金属产品制造业部门产品的消耗量","食品、饮料制造及烟草制品业部门生产1单位总产出对机械设备制造业部门产品的消耗量","食品、饮料制造及烟草制品业部门生产1单位总产出对建筑业部门产品的消耗量","食品、饮料制造及烟草制品业部门生产1单位总产出对运输仓储邮政、信息传输、计算机服务和软件业部门产品的消耗量","食品、饮料制造及烟草制品业部门生产1单位总产出对批发零售贸易、住宿和餐饮业部门产品的消耗量","食品、饮料制造及烟草制品业部门生产1单位总产出对房地产业、租赁和商务服务业部门产品的消耗量","食品、饮料制造及烟草制品业部门生产1单位总产出对金融业部门产品的消耗量","食品、饮料制造及烟草制品业部门生产1单位总产出对其他服务业部门产品的消耗量","食品、饮料制造及烟草制品业部门生产1单位总产出对增加值产品的消耗量","食品、饮料制造及烟草制品业部门生产1单位总产出对劳动者报酬产品的消耗量","食品、饮料制造及烟草制品业部门生产1单位总产出对生产税净额产品的消耗量","食品、饮料制造及烟草制品业部门生产1单位总产出对固定资产折旧产品的消耗量","食品、饮料制造及烟草制品业部门生产1单位总产出对营业盈余产品的消耗量"
//  "纺织、服装及皮革产品制造业总投入","纺织、服装及皮革产品制造业部门生产1单位总产出对中间投入产品的消耗量","纺织、服装及皮革产品制造业部门生产1单位总产出对农、林、牧、渔业部门产品的消耗量","纺织、服装及皮革产品制造业部门生产1单位总产出对采矿业部门产品的消耗量","纺织、服装及皮革产品制造业部门生产1单位总产出对食品、饮料制造及烟草制品业部门产品的消耗量","纺织、服装及皮革产品制造业部门生产1单位总产出对纺织、服装及皮革产品制造业部门产品的消耗量","纺织、服装及皮革产品制造业部门生产1单位总产出对其他制造业部门产品的消耗量","纺织、服装及皮革产品制造业部门生产1单位总产出对电力、热力及水的生产和供应业部门产品的消耗量","纺织、服装及皮革产品制造业部门生产1单位总产出对炼焦、燃气及石油加工业部门产品的消耗量","纺织、服装及皮革产品制造业部门生产1单位总产出对化学工业部门产品的消耗量","纺织、服装及皮革产品制造业部门生产1单位总产出对非金属矿物制品业部门产品的消耗量","纺织、服装及皮革产品制造业部门生产1单位总产出对金属产品制造业部门产品的消耗量","纺织、服装及皮革产品制造业部门生产1单位总产出对机械设备制造业部门产品的消耗量","纺织、服装及皮革产品制造业部门生产1单位总产出对建筑业部门产品的消耗量","纺织、服装及皮革产品制造业部门生产1单位总产出对运输仓储邮政、信息传输、计算机服务和软件业部门产品的消耗量","纺织、服装及皮革产品制造业部门生产1单位总产出对批发零售贸易、住宿和餐饮业部门产品的消耗量","纺织、服装及皮革产品制造业部门生产1单位总产出对房地产业、租赁和商务服务业部门产品的消耗量","纺织、服装及皮革产品制造业部门生产1单位总产出对金融业部门产品的消耗量","纺织、服装及皮革产品制造业部门生产1单位总产出对其他服务业部门产品的消耗量","纺织、服装及皮革产品制造业部门生产1单位总产出对增加值产品的消耗量","纺织、服装及皮革产品制造业部门生产1单位总产出对劳动者报酬产品的消耗量","纺织、服装及皮革产品制造业部门生产1单位总产出对生产税净额产品的消耗量","纺织、服装及皮革产品制造业部门生产1单位总产出对固定资产折旧产品的消耗量","纺织、服装及皮革产品制造业部门生产1单位总产出对营业盈余产品的消耗量"
//  "其他制造业总投入","其他制造业部门生产1单位总产出对中间投入产品的消耗量","其他制造业部门生产1单位总产出对农、林、牧、渔业部门产品的消耗量","其他制造业部门生产1单位总产出对采矿业部门产品的消耗量","其他制造业部门生产1单位总产出对食品、饮料制造及烟草制品业部门产品的消耗量","其他制造业部门生产1单位总产出对纺织、服装及皮革产品制造业部门产品的消耗量","其他制造业部门生产1单位总产出对其他制造业部门产品的消耗量","其他制造业部门生产1单位总产出对电力、热力及水的生产和供应业部门产品的消耗量","其他制造业部门生产1单位总产出对炼焦、燃气及石油加工业部门产品的消耗量","其他制造业部门生产1单位总产出对化学工业部门产品的消耗量","其他制造业部门生产1单位总产出对非金属矿物制品业部门产品的消耗量","其他制造业部门生产1单位总产出对金属产品制造业部门产品的消耗量","其他制造业部门生产1单位总产出对机械设备制造业部门产品的消耗量","其他制造业部门生产1单位总产出对建筑业部门产品的消耗量","其他制造业部门生产1单位总产出对运输仓储邮政、信息传输、计算机服务和软件业部门产品的消耗量","其他制造业部门生产1单位总产出对批发零售贸易、住宿和餐饮业部门产品的消耗量","其他制造业部门生产1单位总产出对房地产业、租赁和商务服务业部门产品的消耗量","其他制造业部门生产1单位总产出对金融业部门产品的消耗量","其他制造业部门生产1单位总产出对其他服务业部门产品的消耗量","其他制造业部门生产1单位总产出对增加值产品的消耗量","其他制造业部门生产1单位总产出对劳动者报酬产品的消耗量","其他制造业部门生产1单位总产出对生产税净额产品的消耗量","其他制造业部门生产1单位总产出对固定资产折旧产品的消耗量","其他制造业部门生产1单位总产出对营业盈余产品的消耗量"
//  "电力、热力及水的生产和供应业总投入","电力、热力及水的生产和供应业部门生产1单位总产出对中间投入产品的消耗量","电力、热力及水的生产和供应业部门生产1单位总产出对农、林、牧、渔业部门产品的消耗量","电力、热力及水的生产和供应业部门生产1单位总产出对采矿业部门产品的消耗量","电力、热力及水的生产和供应业部门生产1单位总产出对食品、饮料制造及烟草制品业部门产品的消耗量","电力、热力及水的生产和供应业部门生产1单位总产出对纺织、服装及皮革产品制造业部门产品的消耗量","电力、热力及水的生产和供应业部门生产1单位总产出对其他制造业部门产品的消耗量","电力、热力及水的生产和供应业部门生产1单位总产出对电力、热力及水的生产和供应业部门产品的消耗量","电力、热力及水的生产和供应业部门生产1单位总产出对炼焦、燃气及石油加工业部门产品的消耗量","电力、热力及水的生产和供应业部门生产1单位总产出对化学工业部门产品的消耗量","电力、热力及水的生产和供应业部门生产1单位总产出对非金属矿物制品业部门产品的消耗量","电力、热力及水的生产和供应业部门生产1单位总产出对金属产品制造业部门产品的消耗量","电力、热力及水的生产和供应业部门生产1单位总产出对机械设备制造业部门产品的消耗量","电力、热力及水的生产和供应业部门生产1单位总产出对建筑业部门产品的消耗量","电力、热力及水的生产和供应业部门生产1单位总产出对运输仓储邮政、信息传输、计算机服务和软件业部门产品的消耗量","电力、热力及水的生产和供应业部门生产1单位总产出对批发零售贸易、住宿和餐饮业部门产品的消耗量","电力、热力及水的生产和供应业部门生产1单位总产出对房地产业、租赁和商务服务业部门产品的消耗量","电力、热力及水的生产和供应业部门生产1单位总产出对金融业部门产品的消耗量","电力、热力及水的生产和供应业部门生产1单位总产出对其他服务业部门产品的消耗量","电力、热力及水的生产和供应业部门生产1单位总产出对增加值产品的消耗量","电力、热力及水的生产和供应业部门生产1单位总产出对劳动者报酬产品的消耗量","电力、热力及水的生产和供应业部门生产1单位总产出对生产税净额产品的消耗量","电力、热力及水的生产和供应业部门生产1单位总产出对固定资产折旧产品的消耗量","电力、热力及水的生产和供应业部门生产1单位总产出对营业盈余产品的消耗量"
//  "炼焦、燃气及石油加工业总投入","炼焦、燃气及石油加工业部门生产1单位总产出对中间投入产品的消耗量","炼焦、燃气及石油加工业部门生产1单位总产出对农、林、牧、渔业部门产品的消耗量","炼焦、燃气及石油加工业部门生产1单位总产出对采矿业部门产品的消耗量","炼焦、燃气及石油加工业部门生产1单位总产出对食品、饮料制造及烟草制品业部门产品的消耗量","炼焦、燃气及石油加工业部门生产1单位总产出对纺织、服装及皮革产品制造业部门产品的消耗量","炼焦、燃气及石油加工业部门生产1单位总产出对其他制造业部门产品的消耗量","炼焦、燃气及石油加工业部门生产1单位总产出对电力、热力及水的生产和供应业部门产品的消耗量","炼焦、燃气及石油加工业部门生产1单位总产出对炼焦、燃气及石油加工业部门产品的消耗量","炼焦、燃气及石油加工业部门生产1单位总产出对化学工业部门产品的消耗量","炼焦、燃气及石油加工业部门生产1单位总产出对非金属矿物制品业部门产品的消耗量","炼焦、燃气及石油加工业部门生产1单位总产出对金属产品制造业部门产品的消耗量","炼焦、燃气及石油加工业部门生产1单位总产出对机械设备制造业部门产品的消耗量","炼焦、燃气及石油加工业部门生产1单位总产出对建筑业部门产品的消耗量","炼焦、燃气及石油加工业部门生产1单位总产出对运输仓储邮政、信息传输、计算机服务和软件业部门产品的消耗量","炼焦、燃气及石油加工业部门生产1单位总产出对批发零售贸易、住宿和餐饮业部门产品的消耗量","炼焦、燃气及石油加工业部门生产1单位总产出对房地产业、租赁和商务服务业部门产品的消耗量","炼焦、燃气及石油加工业部门生产1单位总产出对金融业部门产品的消耗量","炼焦、燃气及石油加工业部门生产1单位总产出对其他服务业部门产品的消耗量","炼焦、燃气及石油加工业部门生产1单位总产出对增加值产品的消耗量","炼焦、燃气及石油加工业部门生产1单位总产出对劳动者报酬产品的消耗量","炼焦、燃气及石油加工业部门生产1单位总产出对生产税净额产品的消耗量","炼焦、燃气及石油加工业部门生产1单位总产出对固定资产折旧产品的消耗量","炼焦、燃气及石油加工业部门生产1单位总产出对营业盈余产品的消耗量"
//  "化学工业总投入","化学工业部门生产1单位总产出对中间投入产品的消耗量","化学工业部门生产1单位总产出对农、林、牧、渔业部门产品的消耗量","化学工业部门生产1单位总产出对采矿业部门产品的消耗量","化学工业部门生产1单位总产出对食品、饮料制造及烟草制品业部门产品的消耗量","化学工业部门生产1单位总产出对纺织、服装及皮革产品制造业部门产品的消耗量","化学工业部门生产1单位总产出对其他制造业部门产品的消耗量","化学工业部门生产1单位总产出对电力、热力及水的生产和供应业部门产品的消耗量","化学工业部门生产1单位总产出对炼焦、燃气及石油加工业部门产品的消耗量","化学工业部门生产1单位总产出对化学工业部门产品的消耗量","化学工业部门生产1单位总产出对非金属矿物制品业部门产品的消耗量","化学工业部门生产1单位总产出对金属产品制造业部门产品的消耗量","化学工业部门生产1单位总产出对机械设备制造业部门产品的消耗量","化学工业部门生产1单位总产出对建筑业部门产品的消耗量","化学工业部门生产1单位总产出对运输仓储邮政、信息传输、计算机服务和软件业部门产品的消耗量","化学工业部门生产1单位总产出对批发零售贸易、住宿和餐饮业部门产品的消耗量","化学工业部门生产1单位总产出对房地产业、租赁和商务服务业部门产品的消耗量","化学工业部门生产1单位总产出对金融业部门产品的消耗量","化学工业部门生产1单位总产出对其他服务业部门产品的消耗量","化学工业部门生产1单位总产出对增加值产品的消耗量","化学工业部门生产1单位总产出对劳动者报酬产品的消耗量","化学工业部门生产1单位总产出对生产税净额产品的消耗量","化学工业部门生产1单位总产出对固定资产折旧产品的消耗量","化学工业部门生产1单位总产出对营业盈余产品的消耗量"
//  "非金属矿物制品业总投入","非金属矿物制品业部门生产1单位总产出对中间投入产品的消耗量","非金属矿物制品业部门生产1单位总产出对农、林、牧、渔业部门产品的消耗量","非金属矿物制品业部门生产1单位总产出对采矿业部门产品的消耗量","非金属矿物制品业部门生产1单位总产出对食品、饮料制造及烟草制品业部门产品的消耗量","非金属矿物制品业部门生产1单位总产出对纺织、服装及皮革产品制造业部门产品的消耗量","非金属矿物制品业部门生产1单位总产出对其他制造业部门产品的消耗量","非金属矿物制品业部门生产1单位总产出对电力、热力及水的生产和供应业部门产品的消耗量","非金属矿物制品业部门生产1单位总产出对炼焦、燃气及石油加工业部门产品的消耗量","非金属矿物制品业部门生产1单位总产出对化学工业部门产品的消耗量","非金属矿物制品业部门生产1单位总产出对非金属矿物制品业部门产品的消耗量","非金属矿物制品业部门生产1单位总产出对金属产品制造业部门产品的消耗量","非金属矿物制品业部门生产1单位总产出对机械设备制造业部门产品的消耗量","非金属矿物制品业部门生产1单位总产出对建筑业部门产品的消耗量","非金属矿物制品业部门生产1单位总产出对运输仓储邮政、信息传输、计算机服务和软件业部门产品的消耗量","非金属矿物制品业部门生产1单位总产出对批发零售贸易、住宿和餐饮业部门产品的消耗量","非金属矿物制品业部门生产1单位总产出对房地产业、租赁和商务服务业部门产品的消耗量","非金属矿物制品业部门生产1单位总产出对金融业部门产品的消耗量","非金属矿物制品业部门生产1单位总产出对其他服务业部门产品的消耗量","非金属矿物制品业部门生产1单位总产出对增加值产品的消耗量","非金属矿物制品业部门生产1单位总产出对劳动者报酬产品的消耗量","非金属矿物制品业部门生产1单位总产出对生产税净额产品的消耗量","非金属矿物制品业部门生产1单位总产出对固定资产折旧产品的消耗量","非金属矿物制品业部门生产1单位总产出对营业盈余产品的消耗量"
//  "金属产品制造业总投入","金属产品制造业部门生产1单位总产出对中间投入产品的消耗量","金属产品制造业部门生产1单位总产出对农、林、牧、渔业部门产品的消耗量","金属产品制造业部门生产1单位总产出对采矿业部门产品的消耗量","金属产品制造业部门生产1单位总产出对食品、饮料制造及烟草制品业部门产品的消耗量","金属产品制造业部门生产1单位总产出对纺织、服装及皮革产品制造业部门产品的消耗量","金属产品制造业部门生产1单位总产出对其他制造业部门产品的消耗量","金属产品制造业部门生产1单位总产出对电力、热力及水的生产和供应业部门产品的消耗量","金属产品制造业部门生产1单位总产出对炼焦、燃气及石油加工业部门产品的消耗量","金属产品制造业部门生产1单位总产出对化学工业部门产品的消耗量","金属产品制造业部门生产1单位总产出对非金属矿物制品业部门产品的消耗量","金属产品制造业部门生产1单位总产出对金属产品制造业部门产品的消耗量","金属产品制造业部门生产1单位总产出对机械设备制造业部门产品的消耗量","金属产品制造业部门生产1单位总产出对建筑业部门产品的消耗量","金属产品制造业部门生产1单位总产出对运输仓储邮政、信息传输、计算机服务和软件业部门产品的消耗量","金属产品制造业部门生产1单位总产出对批发零售贸易、住宿和餐饮业部门产品的消耗量","金属产品制造业部门生产1单位总产出对房地产业、租赁和商务服务业部门产品的消耗量","金属产品制造业部门生产1单位总产出对金融业部门产品的消耗量","金属产品制造业部门生产1单位总产出对其他服务业部门产品的消耗量","金属产品制造业部门生产1单位总产出对增加值产品的消耗量","金属产品制造业部门生产1单位总产出对劳动者报酬产品的消耗量","金属产品制造业部门生产1单位总产出对生产税净额产品的消耗量","金属产品制造业部门生产1单位总产出对固定资产折旧产品的消耗量","金属产品制造业部门生产1单位总产出对营业盈余产品的消耗量"
//  "机械设备制造业总投入","机械设备制造业部门生产1单位总产出对中间投入产品的消耗量","机械设备制造业部门生产1单位总产出对农、林、牧、渔业部门产品的消耗量","机械设备制造业部门生产1单位总产出对采矿业部门产品的消耗量","机械设备制造业部门生产1单位总产出对食品、饮料制造及烟草制品业部门产品的消耗量","机械设备制造业部门生产1单位总产出对纺织、服装及皮革产品制造业部门产品的消耗量","机械设备制造业部门生产1单位总产出对其他制造业部门产品的消耗量","机械设备制造业部门生产1单位总产出对电力、热力及水的生产和供应业部门产品的消耗量","机械设备制造业部门生产1单位总产出对炼焦、燃气及石油加工业部门产品的消耗量","机械设备制造业部门生产1单位总产出对化学工业部门产品的消耗量","机械设备制造业部门生产1单位总产出对非金属矿物制品业部门产品的消耗量","机械设备制造业部门生产1单位总产出对金属产品制造业部门产品的消耗量","机械设备制造业部门生产1单位总产出对机械设备制造业部门产品的消耗量","机械设备制造业部门生产1单位总产出对建筑业部门产品的消耗量","机械设备制造业部门生产1单位总产出对运输仓储邮政、信息传输、计算机服务和软件业部门产品的消耗量","机械设备制造业部门生产1单位总产出对批发零售贸易、住宿和餐饮业部门产品的消耗量","机械设备制造业部门生产1单位总产出对房地产业、租赁和商务服务业部门产品的消耗量","机械设备制造业部门生产1单位总产出对金融业部门产品的消耗量","机械设备制造业部门生产1单位总产出对其他服务业部门产品的消耗量","机械设备制造业部门生产1单位总产出对增加值产品的消耗量","机械设备制造业部门生产1单位总产出对劳动者报酬产品的消耗量","机械设备制造业部门生产1单位总产出对生产税净额产品的消耗量","机械设备制造业部门生产1单位总产出对固定资产折旧产品的消耗量","机械设备制造业部门生产1单位总产出对营业盈余产品的消耗量"
//  "建筑业总投入","建筑业部门生产1单位总产出对中间投入产品的消耗量","建筑业部门生产1单位总产出对农、林、牧、渔业部门产品的消耗量","建筑业部门生产1单位总产出对采矿业部门产品的消耗量","建筑业部门生产1单位总产出对食品、饮料制造及烟草制品业部门产品的消耗量","建筑业部门生产1单位总产出对纺织、服装及皮革产品制造业部门产品的消耗量","建筑业部门生产1单位总产出对其他制造业部门产品的消耗量","建筑业部门生产1单位总产出对电力、热力及水的生产和供应业部门产品的消耗量","建筑业部门生产1单位总产出对炼焦、燃气及石油加工业部门产品的消耗量","建筑业部门生产1单位总产出对化学工业部门产品的消耗量","建筑业部门生产1单位总产出对非金属矿物制品业部门产品的消耗量","建筑业部门生产1单位总产出对金属产品制造业部门产品的消耗量","建筑业部门生产1单位总产出对机械设备制造业部门产品的消耗量","建筑业部门生产1单位总产出对建筑业部门产品的消耗量","建筑业部门生产1单位总产出对运输仓储邮政、信息传输、计算机服务和软件业部门产品的消耗量","建筑业部门生产1单位总产出对批发零售贸易、住宿和餐饮业部门产品的消耗量","建筑业部门生产1单位总产出对房地产业、租赁和商务服务业部门产品的消耗量","建筑业部门生产1单位总产出对金融业部门产品的消耗量","建筑业部门生产1单位总产出对其他服务业部门产品的消耗量","建筑业部门生产1单位总产出对增加值产品的消耗量","建筑业部门生产1单位总产出对劳动者报酬产品的消耗量","建筑业部门生产1单位总产出对生产税净额产品的消耗量","建筑业部门生产1单位总产出对固定资产折旧产品的消耗量","建筑业部门生产1单位总产出对营业盈余产品的消耗量"
//  "运输仓储邮政、信息传输、计算机服务和软件业总投入","运输仓储邮政、信息传输、计算机服务和软件业部门生产1单位总产出对中间投入产品的消耗量","运输仓储邮政、信息传输、计算机服务和软件业部门生产1单位总产出对农、林、牧、渔业部门产品的消耗量","运输仓储邮政、信息传输、计算机服务和软件业部门生产1单位总产出对采矿业部门产品的消耗量","运输仓储邮政、信息传输、计算机服务和软件业部门生产1单位总产出对食品、饮料制造及烟草制品业部门产品的消耗量","运输仓储邮政、信息传输、计算机服务和软件业部门生产1单位总产出对纺织、服装及皮革产品制造业部门产品的消耗量","运输仓储邮政、信息传输、计算机服务和软件业部门生产1单位总产出对其他制造业部门产品的消耗量","运输仓储邮政、信息传输、计算机服务和软件业部门生产1单位总产出对电力、热力及水的生产和供应业部门产品的消耗量","运输仓储邮政、信息传输、计算机服务和软件业部门生产1单位总产出对炼焦、燃气及石油加工业部门产品的消耗量","运输仓储邮政、信息传输、计算机服务和软件业部门生产1单位总产出对化学工业部门产品的消耗量","运输仓储邮政、信息传输、计算机服务和软件业部门生产1单位总产出对非金属矿物制品业部门产品的消耗量","运输仓储邮政、信息传输、计算机服务和软件业部门生产1单位总产出对金属产品制造业部门产品的消耗量","运输仓储邮政、信息传输、计算机服务和软件业部门生产1单位总产出对机械设备制造业部门产品的消耗量","运输仓储邮政、信息传输、计算机服务和软件业部门生产1单位总产出对建筑业部门产品的消耗量","运输仓储邮政、信息传输、计算机服务和软件业部门生产1单位总产出对运输仓储邮政、信息传输、计算机服务和软件业部门产品的消耗量","运输仓储邮政、信息传输、计算机服务和软件业部门生产1单位总产出对批发零售贸易、住宿和餐饮业部门产品的消耗量","运输仓储邮政、信息传输、计算机服务和软件业部门生产1单位总产出对房地产业、租赁和商务服务业部门产品的消耗量","运输仓储邮政、信息传输、计算机服务和软件业部门生产1单位总产出对金融业部门产品的消耗量","运输仓储邮政、信息传输、计算机服务和软件业部门生产1单位总产出对其他服务业部门产品的消耗量","运输仓储邮政、信息传输、计算机服务和软件业部门生产1单位总产出对增加值产品的消耗量","运输仓储邮政、信息传输、计算机服务和软件业部门生产1单位总产出对劳动者报酬产品的消耗量","运输仓储邮政、信息传输、计算机服务和软件业部门生产1单位总产出对生产税净额产品的消耗量","运输仓储邮政、信息传输、计算机服务和软件业部门生产1单位总产出对固定资产折旧产品的消耗量","运输仓储邮政、信息传输、计算机服务和软件业部门生产1单位总产出对营业盈余产品的消耗量"
//  "批发零售贸易、住宿和餐饮业总投入","批发零售贸易、住宿和餐饮业部门生产1单位总产出对中间投入产品的消耗量","批发零售贸易、住宿和餐饮业部门生产1单位总产出对农、林、牧、渔业部门产品的消耗量","批发零售贸易、住宿和餐饮业部门生产1单位总产出对采矿业部门产品的消耗量","批发零售贸易、住宿和餐饮业部门生产1单位总产出对食品、饮料制造及烟草制品业部门产品的消耗量","批发零售贸易、住宿和餐饮业部门生产1单位总产出对纺织、服装及皮革产品制造业部门产品的消耗量","批发零售贸易、住宿和餐饮业部门生产1单位总产出对其他制造业部门产品的消耗量","批发零售贸易、住宿和餐饮业部门生产1单位总产出对电力、热力及水的生产和供应业部门产品的消耗量","批发零售贸易、住宿和餐饮业部门生产1单位总产出对炼焦、燃气及石油加工业部门产品的消耗量","批发零售贸易、住宿和餐饮业部门生产1单位总产出对化学工业部门产品的消耗量","批发零售贸易、住宿和餐饮业部门生产1单位总产出对非金属矿物制品业部门产品的消耗量","批发零售贸易、住宿和餐饮业部门生产1单位总产出对金属产品制造业部门产品的消耗量","批发零售贸易、住宿和餐饮业部门生产1单位总产出对机械设备制造业部门产品的消耗量","批发零售贸易、住宿和餐饮业部门生产1单位总产出对建筑业部门产品的消耗量","批发零售贸易、住宿和餐饮业部门生产1单位总产出对运输仓储邮政、信息传输、计算机服务和软件业部门产品的消耗量","批发零售贸易、住宿和餐饮业部门生产1单位总产出对批发零售贸易、住宿和餐饮业部门产品的消耗量","批发零售贸易、住宿和餐饮业部门生产1单位总产出对房地产业、租赁和商务服务业部门产品的消耗量","批发零售贸易、住宿和餐饮业部门生产1单位总产出对金融业部门产品的消耗量","批发零售贸易、住宿和餐饮业部门生产1单位总产出对其他服务业部门产品的消耗量","批发零售贸易、住宿和餐饮业部门生产1单位总产出对增加值产品的消耗量","批发零售贸易、住宿和餐饮业部门生产1单位总产出对劳动者报酬产品的消耗量","批发零售贸易、住宿和餐饮业部门生产1单位总产出对生产税净额产品的消耗量","批发零售贸易、住宿和餐饮业部门生产1单位总产出对固定资产折旧产品的消耗量","批发零售贸易、住宿和餐饮业部门生产1单位总产出对营业盈余产品的消耗量"
//  "房地产业、租赁和商务服务业总投入","房地产业、租赁和商务服务业部门生产1单位总产出对中间投入产品的消耗量","房地产业、租赁和商务服务业部门生产1单位总产出对农、林、牧、渔业部门产品的消耗量","房地产业、租赁和商务服务业部门生产1单位总产出对采矿业部门产品的消耗量","房地产业、租赁和商务服务业部门生产1单位总产出对食品、饮料制造及烟草制品业部门产品的消耗量","房地产业、租赁和商务服务业部门生产1单位总产出对纺织、服装及皮革产品制造业部门产品的消耗量","房地产业、租赁和商务服务业部门生产1单位总产出对其他制造业部门产品的消耗量","房地产业、租赁和商务服务业部门生产1单位总产出对电力、热力及水的生产和供应业部门产品的消耗量","房地产业、租赁和商务服务业部门生产1单位总产出对炼焦、燃气及石油加工业部门产品的消耗量","房地产业、租赁和商务服务业部门生产1单位总产出对化学工业部门产品的消耗量","房地产业、租赁和商务服务业部门生产1单位总产出对非金属矿物制品业部门产品的消耗量","房地产业、租赁和商务服务业部门生产1单位总产出对金属产品制造业部门产品的消耗量","房地产业、租赁和商务服务业部门生产1单位总产出对机械设备制造业部门产品的消耗量","房地产业、租赁和商务服务业部门生产1单位总产出对建筑业部门产品的消耗量","房地产业、租赁和商务服务业部门生产1单位总产出对运输仓储邮政、信息传输、计算机服务和软件业部门产品的消耗量","房地产业、租赁和商务服务业部门生产1单位总产出对批发零售贸易、住宿和餐饮业部门产品的消耗量","房地产业、租赁和商务服务业部门生产1单位总产出对房地产业、租赁和商务服务业部门产品的消耗量","房地产业、租赁和商务服务业部门生产1单位总产出对金融业部门产品的消耗量","房地产业、租赁和商务服务业部门生产1单位总产出对其他服务业部门产品的消耗量","房地产业、租赁和商务服务业部门生产1单位总产出对增加值产品的消耗量","房地产业、租赁和商务服务业部门生产1单位总产出对劳动者报酬产品的消耗量","房地产业、租赁和商务服务业部门生产1单位总产出对生产税净额产品的消耗量","房地产业、租赁和商务服务业部门生产1单位总产出对固定资产折旧产品的消耗量","房地产业、租赁和商务服务业部门生产1单位总产出对营业盈余产品的消耗量"
//  "金融业总投入","金融业部门生产1单位总产出对中间投入产品的消耗量","金融业部门生产1单位总产出对农、林、牧、渔业部门产品的消耗量","金融业部门生产1单位总产出对采矿业部门产品的消耗量","金融业部门生产1单位总产出对食品、饮料制造及烟草制品业部门产品的消耗量","金融业部门生产1单位总产出对纺织、服装及皮革产品制造业部门产品的消耗量","金融业部门生产1单位总产出对其他制造业部门产品的消耗量","金融业部门生产1单位总产出对电力、热力及水的生产和供应业部门产品的消耗量","金融业部门生产1单位总产出对炼焦、燃气及石油加工业部门产品的消耗量","金融业部门生产1单位总产出对化学工业部门产品的消耗量","金融业部门生产1单位总产出对非金属矿物制品业部门产品的消耗量","金融业部门生产1单位总产出对金属产品制造业部门产品的消耗量","金融业部门生产1单位总产出对机械设备制造业部门产品的消耗量","金融业部门生产1单位总产出对建筑业部门产品的消耗量","金融业部门生产1单位总产出对运输仓储邮政、信息传输、计算机服务和软件业部门产品的消耗量","金融业部门生产1单位总产出对批发零售贸易、住宿和餐饮业部门产品的消耗量","金融业部门生产1单位总产出对房地产业、租赁和商务服务业部门产品的消耗量","金融业部门生产1单位总产出对金融业部门产品的消耗量","金融业部门生产1单位总产出对其他服务业部门产品的消耗量","金融业部门生产1单位总产出对增加值产品的消耗量","金融业部门生产1单位总产出对劳动者报酬产品的消耗量","金融业部门生产1单位总产出对生产税净额产品的消耗量","金融业部门生产1单位总产出对固定资产折旧产品的消耗量","金融业部门生产1单位总产出对营业盈余产品的消耗量"
//  "其他服务业总投入","其他服务业部门生产1单位总产出对中间投入产品的消耗量","其他服务业部门生产1单位总产出对农、林、牧、渔业部门产品的消耗量","其他服务业部门生产1单位总产出对采矿业部门产品的消耗量","其他服务业部门生产1单位总产出对食品、饮料制造及烟草制品业部门产品的消耗量","其他服务业部门生产1单位总产出对纺织、服装及皮革产品制造业部门产品的消耗量","其他服务业部门生产1单位总产出对其他制造业部门产品的消耗量","其他服务业部门生产1单位总产出对电力、热力及水的生产和供应业部门产品的消耗量","其他服务业部门生产1单位总产出对炼焦、燃气及石油加工业部门产品的消耗量","其他服务业部门生产1单位总产出对化学工业部门产品的消耗量","其他服务业部门生产1单位总产出对非金属矿物制品业部门产品的消耗量","其他服务业部门生产1单位总产出对金属产品制造业部门产品的消耗量","其他服务业部门生产1单位总产出对机械设备制造业部门产品的消耗量","其他服务业部门生产1单位总产出对建筑业部门产品的消耗量","其他服务业部门生产1单位总产出对运输仓储邮政、信息传输、计算机服务和软件业部门产品的消耗量","其他服务业部门生产1单位总产出对批发零售贸易、住宿和餐饮业部门产品的消耗量","其他服务业部门生产1单位总产出对房地产业、租赁和商务服务业部门产品的消耗量","其他服务业部门生产1单位总产出对金融业部门产品的消耗量","其他服务业部门生产1单位总产出对其他服务业部门产品的消耗量","其他服务业部门生产1单位总产出对增加值产品的消耗量","其他服务业部门生产1单位总产出对劳动者报酬产品的消耗量","其他服务业部门生产1单位总产出对生产税净额产品的消耗量","其他服务业部门生产1单位总产出对固定资产折旧产品的消耗量","其他服务业部门生产1单位总产出对营业盈余产品的消耗量"
//
//  "为生产农、林、牧、渔业部门单位最终产品，对农、林、牧、渔业部门中间产品的完全消耗量","为生产农、林、牧、渔业部门单位最终产品，对采矿业部门中间产品的完全消耗量","为生产农、林、牧、渔业部门单位最终产品，对食品、饮料制造及烟草制品业部门中间产品的完全消耗量","为生产农、林、牧、渔业部门单位最终产品，对纺织、服装及皮革产品制造业部门中间产品的完全消耗量","为生产农、林、牧、渔业部门单位最终产品，对其他制造业部门中间产品的完全消耗量","为生产农、林、牧、渔业部门单位最终产品，对电力、热力及水的生产和供应业部门中间产品的完全消耗量","为生产农、林、牧、渔业部门单位最终产品，对炼焦、燃气及石油加工业部门中间产品的完全消耗量","为生产农、林、牧、渔业部门单位最终产品，对化学工业部门中间产品的完全消耗量","为生产农、林、牧、渔业部门单位最终产品，对非金属矿物制品业部门中间产品的完全消耗量","为生产农、林、牧、渔业部门单位最终产品，对金属产品制造业部门中间产品的完全消耗量","为生产农、林、牧、渔业部门单位最终产品，对机械设备制造业部门中间产品的完全消耗量","为生产农、林、牧、渔业部门单位最终产品，对建筑业部门中间产品的完全消耗量","为生产农、林、牧、渔业部门单位最终产品，对运输仓储邮政、信息传输、计算机服务和软件业部门中间产品的完全消耗量","为生产农、林、牧、渔业部门单位最终产品，对批发零售贸易、住宿和餐饮业部门中间产品的完全消耗量","为生产农、林、牧、渔业部门单位最终产品，对房地产业、租赁和商务服务业部门中间产品的完全消耗量","为生产农、林、牧、渔业部门单位最终产品，对金融业部门中间产品的完全消耗量","为生产农、林、牧、渔业部门单位最终产品，对其他服务业部门中间产品的完全消耗量"
//  "为生产采矿业部门单位最终产品，对农、林、牧、渔业部门中间产品的完全消耗量","为生产采矿业部门单位最终产品，对采矿业部门中间产品的完全消耗量","为生产采矿业部门单位最终产品，对食品、饮料制造及烟草制品业部门中间产品的完全消耗量","为生产采矿业部门单位最终产品，对纺织、服装及皮革产品制造业部门中间产品的完全消耗量","为生产采矿业部门单位最终产品，对其他制造业部门中间产品的完全消耗量","为生产采矿业部门单位最终产品，对电力、热力及水的生产和供应业部门中间产品的完全消耗量","为生产采矿业部门单位最终产品，对炼焦、燃气及石油加工业部门中间产品的完全消耗量","为生产采矿业部门单位最终产品，对化学工业部门中间产品的完全消耗量","为生产采矿业部门单位最终产品，对非金属矿物制品业部门中间产品的完全消耗量","为生产采矿业部门单位最终产品，对金属产品制造业部门中间产品的完全消耗量","为生产采矿业部门单位最终产品，对机械设备制造业部门中间产品的完全消耗量","为生产采矿业部门单位最终产品，对建筑业部门中间产品的完全消耗量","为生产采矿业部门单位最终产品，对运输仓储邮政、信息传输、计算机服务和软件业部门中间产品的完全消耗量","为生产采矿业部门单位最终产品，对批发零售贸易、住宿和餐饮业部门中间产品的完全消耗量","为生产采矿业部门单位最终产品，对房地产业、租赁和商务服务业部门中间产品的完全消耗量","为生产采矿业部门单位最终产品，对金融业部门中间产品的完全消耗量","为生产采矿业部门单位最终产品，对其他服务业部门中间产品的完全消耗量"
//  "为生产食品、饮料制造及烟草制品业部门单位最终产品，对农、林、牧、渔业部门中间产品的完全消耗量","为生产食品、饮料制造及烟草制品业部门单位最终产品，对采矿业部门中间产品的完全消耗量","为生产食品、饮料制造及烟草制品业部门单位最终产品，对食品、饮料制造及烟草制品业部门中间产品的完全消耗量","为生产食品、饮料制造及烟草制品业部门单位最终产品，对纺织、服装及皮革产品制造业部门中间产品的完全消耗量","为生产食品、饮料制造及烟草制品业部门单位最终产品，对其他制造业部门中间产品的完全消耗量","为生产食品、饮料制造及烟草制品业部门单位最终产品，对电力、热力及水的生产和供应业部门中间产品的完全消耗量","为生产食品、饮料制造及烟草制品业部门单位最终产品，对炼焦、燃气及石油加工业部门中间产品的完全消耗量","为生产食品、饮料制造及烟草制品业部门单位最终产品，对化学工业部门中间产品的完全消耗量","为生产食品、饮料制造及烟草制品业部门单位最终产品，对非金属矿物制品业部门中间产品的完全消耗量","为生产食品、饮料制造及烟草制品业部门单位最终产品，对金属产品制造业部门中间产品的完全消耗量","为生产食品、饮料制造及烟草制品业部门单位最终产品，对机械设备制造业部门中间产品的完全消耗量","为生产食品、饮料制造及烟草制品业部门单位最终产品，对建筑业部门中间产品的完全消耗量","为生产食品、饮料制造及烟草制品业部门单位最终产品，对运输仓储邮政、信息传输、计算机服务和软件业部门中间产品的完全消耗量","为生产食品、饮料制造及烟草制品业部门单位最终产品，对批发零售贸易、住宿和餐饮业部门中间产品的完全消耗量","为生产食品、饮料制造及烟草制品业部门单位最终产品，对房地产业、租赁和商务服务业部门中间产品的完全消耗量","为生产食品、饮料制造及烟草制品业部门单位最终产品，对金融业部门中间产品的完全消耗量","为生产食品、饮料制造及烟草制品业部门单位最终产品，对其他服务业部门中间产品的完全消耗量"
//  "为生产纺织、服装及皮革产品制造业部门单位最终产品，对农、林、牧、渔业部门中间产品的完全消耗量","为生产纺织、服装及皮革产品制造业部门单位最终产品，对采矿业部门中间产品的完全消耗量","为生产纺织、服装及皮革产品制造业部门单位最终产品，对食品、饮料制造及烟草制品业部门中间产品的完全消耗量","为生产纺织、服装及皮革产品制造业部门单位最终产品，对纺织、服装及皮革产品制造业部门中间产品的完全消耗量","为生产纺织、服装及皮革产品制造业部门单位最终产品，对其他制造业部门中间产品的完全消耗量","为生产纺织、服装及皮革产品制造业部门单位最终产品，对电力、热力及水的生产和供应业部门中间产品的完全消耗量","为生产纺织、服装及皮革产品制造业部门单位最终产品，对炼焦、燃气及石油加工业部门中间产品的完全消耗量","为生产纺织、服装及皮革产品制造业部门单位最终产品，对化学工业部门中间产品的完全消耗量","为生产纺织、服装及皮革产品制造业部门单位最终产品，对非金属矿物制品业部门中间产品的完全消耗量","为生产纺织、服装及皮革产品制造业部门单位最终产品，对金属产品制造业部门中间产品的完全消耗量","为生产纺织、服装及皮革产品制造业部门单位最终产品，对机械设备制造业部门中间产品的完全消耗量","为生产纺织、服装及皮革产品制造业部门单位最终产品，对建筑业部门中间产品的完全消耗量","为生产纺织、服装及皮革产品制造业部门单位最终产品，对运输仓储邮政、信息传输、计算机服务和软件业部门中间产品的完全消耗量","为生产纺织、服装及皮革产品制造业部门单位最终产品，对批发零售贸易、住宿和餐饮业部门中间产品的完全消耗量","为生产纺织、服装及皮革产品制造业部门单位最终产品，对房地产业、租赁和商务服务业部门中间产品的完全消耗量","为生产纺织、服装及皮革产品制造业部门单位最终产品，对金融业部门中间产品的完全消耗量","为生产纺织、服装及皮革产品制造业部门单位最终产品，对其他服务业部门中间产品的完全消耗量"
//  "为生产其他制造业部门单位最终产品，对农、林、牧、渔业部门中间产品的完全消耗量","为生产其他制造业部门单位最终产品，对采矿业部门中间产品的完全消耗量","为生产其他制造业部门单位最终产品，对食品、饮料制造及烟草制品业部门中间产品的完全消耗量","为生产其他制造业部门单位最终产品，对纺织、服装及皮革产品制造业部门中间产品的完全消耗量","为生产其他制造业部门单位最终产品，对其他制造业部门中间产品的完全消耗量","为生产其他制造业部门单位最终产品，对电力、热力及水的生产和供应业部门中间产品的完全消耗量","为生产其他制造业部门单位最终产品，对炼焦、燃气及石油加工业部门中间产品的完全消耗量","为生产其他制造业部门单位最终产品，对化学工业部门中间产品的完全消耗量","为生产其他制造业部门单位最终产品，对非金属矿物制品业部门中间产品的完全消耗量","为生产其他制造业部门单位最终产品，对金属产品制造业部门中间产品的完全消耗量","为生产其他制造业部门单位最终产品，对机械设备制造业部门中间产品的完全消耗量","为生产其他制造业部门单位最终产品，对建筑业部门中间产品的完全消耗量","为生产其他制造业部门单位最终产品，对运输仓储邮政、信息传输、计算机服务和软件业部门中间产品的完全消耗量","为生产其他制造业部门单位最终产品，对批发零售贸易、住宿和餐饮业部门中间产品的完全消耗量","为生产其他制造业部门单位最终产品，对房地产业、租赁和商务服务业部门中间产品的完全消耗量","为生产其他制造业部门单位最终产品，对金融业部门中间产品的完全消耗量","为生产其他制造业部门单位最终产品，对其他服务业部门中间产品的完全消耗量"
//  "为生产电力、热力及水的生产和供应业部门单位最终产品，对农、林、牧、渔业部门中间产品的完全消耗量","为生产电力、热力及水的生产和供应业部门单位最终产品，对采矿业部门中间产品的完全消耗量","为生产电力、热力及水的生产和供应业部门单位最终产品，对食品、饮料制造及烟草制品业部门中间产品的完全消耗量","为生产电力、热力及水的生产和供应业部门单位最终产品，对纺织、服装及皮革产品制造业部门中间产品的完全消耗量","为生产电力、热力及水的生产和供应业部门单位最终产品，对其他制造业部门中间产品的完全消耗量","为生产电力、热力及水的生产和供应业部门单位最终产品，对电力、热力及水的生产和供应业部门中间产品的完全消耗量","为生产电力、热力及水的生产和供应业部门单位最终产品，对炼焦、燃气及石油加工业部门中间产品的完全消耗量","为生产电力、热力及水的生产和供应业部门单位最终产品，对化学工业部门中间产品的完全消耗量","为生产电力、热力及水的生产和供应业部门单位最终产品，对非金属矿物制品业部门中间产品的完全消耗量","为生产电力、热力及水的生产和供应业部门单位最终产品，对金属产品制造业部门中间产品的完全消耗量","为生产电力、热力及水的生产和供应业部门单位最终产品，对机械设备制造业部门中间产品的完全消耗量","为生产电力、热力及水的生产和供应业部门单位最终产品，对建筑业部门中间产品的完全消耗量","为生产电力、热力及水的生产和供应业部门单位最终产品，对运输仓储邮政、信息传输、计算机服务和软件业部门中间产品的完全消耗量","为生产电力、热力及水的生产和供应业部门单位最终产品，对批发零售贸易、住宿和餐饮业部门中间产品的完全消耗量","为生产电力、热力及水的生产和供应业部门单位最终产品，对房地产业、租赁和商务服务业部门中间产品的完全消耗量","为生产电力、热力及水的生产和供应业部门单位最终产品，对金融业部门中间产品的完全消耗量","为生产电力、热力及水的生产和供应业部门单位最终产品，对其他服务业部门中间产品的完全消耗量"
//  "为生产炼焦、燃气及石油加工业部门单位最终产品，对农、林、牧、渔业部门中间产品的完全消耗量","为生产炼焦、燃气及石油加工业部门单位最终产品，对采矿业部门中间产品的完全消耗量","为生产炼焦、燃气及石油加工业部门单位最终产品，对食品、饮料制造及烟草制品业部门中间产品的完全消耗量","为生产炼焦、燃气及石油加工业部门单位最终产品，对纺织、服装及皮革产品制造业部门中间产品的完全消耗量","为生产炼焦、燃气及石油加工业部门单位最终产品，对其他制造业部门中间产品的完全消耗量","为生产炼焦、燃气及石油加工业部门单位最终产品，对电力、热力及水的生产和供应业部门中间产品的完全消耗量","为生产炼焦、燃气及石油加工业部门单位最终产品，对炼焦、燃气及石油加工业部门中间产品的完全消耗量","为生产炼焦、燃气及石油加工业部门单位最终产品，对化学工业部门中间产品的完全消耗量","为生产炼焦、燃气及石油加工业部门单位最终产品，对非金属矿物制品业部门中间产品的完全消耗量","为生产炼焦、燃气及石油加工业部门单位最终产品，对金属产品制造业部门中间产品的完全消耗量","为生产炼焦、燃气及石油加工业部门单位最终产品，对机械设备制造业部门中间产品的完全消耗量","为生产炼焦、燃气及石油加工业部门单位最终产品，对建筑业部门中间产品的完全消耗量","为生产炼焦、燃气及石油加工业部门单位最终产品，对运输仓储邮政、信息传输、计算机服务和软件业部门中间产品的完全消耗量","为生产炼焦、燃气及石油加工业部门单位最终产品，对批发零售贸易、住宿和餐饮业部门中间产品的完全消耗量","为生产炼焦、燃气及石油加工业部门单位最终产品，对房地产业、租赁和商务服务业部门中间产品的完全消耗量","为生产炼焦、燃气及石油加工业部门单位最终产品，对金融业部门中间产品的完全消耗量","为生产炼焦、燃气及石油加工业部门单位最终产品，对其他服务业部门中间产品的完全消耗量"
//  "为生产化学工业部门单位最终产品，对农、林、牧、渔业部门中间产品的完全消耗量","为生产化学工业部门单位最终产品，对采矿业部门中间产品的完全消耗量","为生产化学工业部门单位最终产品，对食品、饮料制造及烟草制品业部门中间产品的完全消耗量","为生产化学工业部门单位最终产品，对纺织、服装及皮革产品制造业部门中间产品的完全消耗量","为生产化学工业部门单位最终产品，对其他制造业部门中间产品的完全消耗量","为生产化学工业部门单位最终产品，对电力、热力及水的生产和供应业部门中间产品的完全消耗量","为生产化学工业部门单位最终产品，对炼焦、燃气及石油加工业部门中间产品的完全消耗量","为生产化学工业部门单位最终产品，对化学工业部门中间产品的完全消耗量","为生产化学工业部门单位最终产品，对非金属矿物制品业部门中间产品的完全消耗量","为生产化学工业部门单位最终产品，对金属产品制造业部门中间产品的完全消耗量","为生产化学工业部门单位最终产品，对机械设备制造业部门中间产品的完全消耗量","为生产化学工业部门单位最终产品，对建筑业部门中间产品的完全消耗量","为生产化学工业部门单位最终产品，对运输仓储邮政、信息传输、计算机服务和软件业部门中间产品的完全消耗量","为生产化学工业部门单位最终产品，对批发零售贸易、住宿和餐饮业部门中间产品的完全消耗量","为生产化学工业部门单位最终产品，对房地产业、租赁和商务服务业部门中间产品的完全消耗量","为生产化学工业部门单位最终产品，对金融业部门中间产品的完全消耗量","为生产化学工业部门单位最终产品，对其他服务业部门中间产品的完全消耗量"
//  "为生产非金属矿物制品业部门单位最终产品，对农、林、牧、渔业部门中间产品的完全消耗量","为生产非金属矿物制品业部门单位最终产品，对采矿业部门中间产品的完全消耗量","为生产非金属矿物制品业部门单位最终产品，对食品、饮料制造及烟草制品业部门中间产品的完全消耗量","为生产非金属矿物制品业部门单位最终产品，对纺织、服装及皮革产品制造业部门中间产品的完全消耗量","为生产非金属矿物制品业部门单位最终产品，对其他制造业部门中间产品的完全消耗量","为生产非金属矿物制品业部门单位最终产品，对电力、热力及水的生产和供应业部门中间产品的完全消耗量","为生产非金属矿物制品业部门单位最终产品，对炼焦、燃气及石油加工业部门中间产品的完全消耗量","为生产非金属矿物制品业部门单位最终产品，对化学工业部门中间产品的完全消耗量","为生产非金属矿物制品业部门单位最终产品，对非金属矿物制品业部门中间产品的完全消耗量","为生产非金属矿物制品业部门单位最终产品，对金属产品制造业部门中间产品的完全消耗量","为生产非金属矿物制品业部门单位最终产品，对机械设备制造业部门中间产品的完全消耗量","为生产非金属矿物制品业部门单位最终产品，对建筑业部门中间产品的完全消耗量","为生产非金属矿物制品业部门单位最终产品，对运输仓储邮政、信息传输、计算机服务和软件业部门中间产品的完全消耗量","为生产非金属矿物制品业部门单位最终产品，对批发零售贸易、住宿和餐饮业部门中间产品的完全消耗量","为生产非金属矿物制品业部门单位最终产品，对房地产业、租赁和商务服务业部门中间产品的完全消耗量","为生产非金属矿物制品业部门单位最终产品，对金融业部门中间产品的完全消耗量","为生产非金属矿物制品业部门单位最终产品，对其他服务业部门中间产品的完全消耗量"
//  "为生产金属产品制造业部门单位最终产品，对农、林、牧、渔业部门中间产品的完全消耗量","为生产金属产品制造业部门单位最终产品，对采矿业部门中间产品的完全消耗量","为生产金属产品制造业部门单位最终产品，对食品、饮料制造及烟草制品业部门中间产品的完全消耗量","为生产金属产品制造业部门单位最终产品，对纺织、服装及皮革产品制造业部门中间产品的完全消耗量","为生产金属产品制造业部门单位最终产品，对其他制造业部门中间产品的完全消耗量","为生产金属产品制造业部门单位最终产品，对电力、热力及水的生产和供应业部门中间产品的完全消耗量","为生产金属产品制造业部门单位最终产品，对炼焦、燃气及石油加工业部门中间产品的完全消耗量","为生产金属产品制造业部门单位最终产品，对化学工业部门中间产品的完全消耗量","为生产金属产品制造业部门单位最终产品，对非金属矿物制品业部门中间产品的完全消耗量","为生产金属产品制造业部门单位最终产品，对金属产品制造业部门中间产品的完全消耗量","为生产金属产品制造业部门单位最终产品，对机械设备制造业部门中间产品的完全消耗量","为生产金属产品制造业部门单位最终产品，对建筑业部门中间产品的完全消耗量","为生产金属产品制造业部门单位最终产品，对运输仓储邮政、信息传输、计算机服务和软件业部门中间产品的完全消耗量","为生产金属产品制造业部门单位最终产品，对批发零售贸易、住宿和餐饮业部门中间产品的完全消耗量","为生产金属产品制造业部门单位最终产品，对房地产业、租赁和商务服务业部门中间产品的完全消耗量","为生产金属产品制造业部门单位最终产品，对金融业部门中间产品的完全消耗量","为生产金属产品制造业部门单位最终产品，对其他服务业部门中间产品的完全消耗量"
//  "为生产机械设备制造业部门单位最终产品，对农、林、牧、渔业部门中间产品的完全消耗量","为生产机械设备制造业部门单位最终产品，对采矿业部门中间产品的完全消耗量","为生产机械设备制造业部门单位最终产品，对食品、饮料制造及烟草制品业部门中间产品的完全消耗量","为生产机械设备制造业部门单位最终产品，对纺织、服装及皮革产品制造业部门中间产品的完全消耗量","为生产机械设备制造业部门单位最终产品，对其他制造业部门中间产品的完全消耗量","为生产机械设备制造业部门单位最终产品，对电力、热力及水的生产和供应业部门中间产品的完全消耗量","为生产机械设备制造业部门单位最终产品，对炼焦、燃气及石油加工业部门中间产品的完全消耗量","为生产机械设备制造业部门单位最终产品，对化学工业部门中间产品的完全消耗量","为生产机械设备制造业部门单位最终产品，对非金属矿物制品业部门中间产品的完全消耗量","为生产机械设备制造业部门单位最终产品，对金属产品制造业部门中间产品的完全消耗量","为生产机械设备制造业部门单位最终产品，对机械设备制造业部门中间产品的完全消耗量","为生产机械设备制造业部门单位最终产品，对建筑业部门中间产品的完全消耗量","为生产机械设备制造业部门单位最终产品，对运输仓储邮政、信息传输、计算机服务和软件业部门中间产品的完全消耗量","为生产机械设备制造业部门单位最终产品，对批发零售贸易、住宿和餐饮业部门中间产品的完全消耗量","为生产机械设备制造业部门单位最终产品，对房地产业、租赁和商务服务业部门中间产品的完全消耗量","为生产机械设备制造业部门单位最终产品，对金融业部门中间产品的完全消耗量","为生产机械设备制造业部门单位最终产品，对其他服务业部门中间产品的完全消耗量"
//  "为生产建筑业部门单位最终产品，对农、林、牧、渔业部门中间产品的完全消耗量","为生产建筑业部门单位最终产品，对采矿业部门中间产品的完全消耗量","为生产建筑业部门单位最终产品，对食品、饮料制造及烟草制品业部门中间产品的完全消耗量","为生产建筑业部门单位最终产品，对纺织、服装及皮革产品制造业部门中间产品的完全消耗量","为生产建筑业部门单位最终产品，对其他制造业部门中间产品的完全消耗量","为生产建筑业部门单位最终产品，对电力、热力及水的生产和供应业部门中间产品的完全消耗量","为生产建筑业部门单位最终产品，对炼焦、燃气及石油加工业部门中间产品的完全消耗量","为生产建筑业部门单位最终产品，对化学工业部门中间产品的完全消耗量","为生产建筑业部门单位最终产品，对非金属矿物制品业部门中间产品的完全消耗量","为生产建筑业部门单位最终产品，对金属产品制造业部门中间产品的完全消耗量","为生产建筑业部门单位最终产品，对机械设备制造业部门中间产品的完全消耗量","为生产建筑业部门单位最终产品，对建筑业部门中间产品的完全消耗量","为生产建筑业部门单位最终产品，对运输仓储邮政、信息传输、计算机服务和软件业部门中间产品的完全消耗量","为生产建筑业部门单位最终产品，对批发零售贸易、住宿和餐饮业部门中间产品的完全消耗量","为生产建筑业部门单位最终产品，对房地产业、租赁和商务服务业部门中间产品的完全消耗量","为生产建筑业部门单位最终产品，对金融业部门中间产品的完全消耗量","为生产建筑业部门单位最终产品，对其他服务业部门中间产品的完全消耗量"
//  "为生产运输仓储邮政、信息传输、计算机服务和软件业部门单位最终产品，对农、林、牧、渔业部门中间产品的完全消耗量","为生产运输仓储邮政、信息传输、计算机服务和软件业部门单位最终产品，对采矿业部门中间产品的完全消耗量","为生产运输仓储邮政、信息传输、计算机服务和软件业部门单位最终产品，对食品、饮料制造及烟草制品业部门中间产品的完全消耗量","为生产运输仓储邮政、信息传输、计算机服务和软件业部门单位最终产品，对纺织、服装及皮革产品制造业部门中间产品的完全消耗量","为生产运输仓储邮政、信息传输、计算机服务和软件业部门单位最终产品，对其他制造业部门中间产品的完全消耗量","为生产运输仓储邮政、信息传输、计算机服务和软件业部门单位最终产品，对电力、热力及水的生产和供应业部门中间产品的完全消耗量","为生产运输仓储邮政、信息传输、计算机服务和软件业部门单位最终产品，对炼焦、燃气及石油加工业部门中间产品的完全消耗量","为生产运输仓储邮政、信息传输、计算机服务和软件业部门单位最终产品，对化学工业部门中间产品的完全消耗量","为生产运输仓储邮政、信息传输、计算机服务和软件业部门单位最终产品，对非金属矿物制品业部门中间产品的完全消耗量","为生产运输仓储邮政、信息传输、计算机服务和软件业部门单位最终产品，对金属产品制造业部门中间产品的完全消耗量","为生产运输仓储邮政、信息传输、计算机服务和软件业部门单位最终产品，对机械设备制造业部门中间产品的完全消耗量","为生产运输仓储邮政、信息传输、计算机服务和软件业部门单位最终产品，对建筑业部门中间产品的完全消耗量","为生产运输仓储邮政、信息传输、计算机服务和软件业部门单位最终产品，对运输仓储邮政、信息传输、计算机服务和软件业部门中间产品的完全消耗量","为生产运输仓储邮政、信息传输、计算机服务和软件业部门单位最终产品，对批发零售贸易、住宿和餐饮业部门中间产品的完全消耗量","为生产运输仓储邮政、信息传输、计算机服务和软件业部门单位最终产品，对房地产业、租赁和商务服务业部门中间产品的完全消耗量","为生产运输仓储邮政、信息传输、计算机服务和软件业部门单位最终产品，对金融业部门中间产品的完全消耗量","为生产运输仓储邮政、信息传输、计算机服务和软件业部门单位最终产品，对其他服务业部门中间产品的完全消耗量"
//  "为生产批发零售贸易、住宿和餐饮业部门单位最终产品，对农、林、牧、渔业部门中间产品的完全消耗量","为生产批发零售贸易、住宿和餐饮业部门单位最终产品，对采矿业部门中间产品的完全消耗量","为生产批发零售贸易、住宿和餐饮业部门单位最终产品，对食品、饮料制造及烟草制品业部门中间产品的完全消耗量","为生产批发零售贸易、住宿和餐饮业部门单位最终产品，对纺织、服装及皮革产品制造业部门中间产品的完全消耗量","为生产批发零售贸易、住宿和餐饮业部门单位最终产品，对其他制造业部门中间产品的完全消耗量","为生产批发零售贸易、住宿和餐饮业部门单位最终产品，对电力、热力及水的生产和供应业部门中间产品的完全消耗量","为生产批发零售贸易、住宿和餐饮业部门单位最终产品，对炼焦、燃气及石油加工业部门中间产品的完全消耗量","为生产批发零售贸易、住宿和餐饮业部门单位最终产品，对化学工业部门中间产品的完全消耗量","为生产批发零售贸易、住宿和餐饮业部门单位最终产品，对非金属矿物制品业部门中间产品的完全消耗量","为生产批发零售贸易、住宿和餐饮业部门单位最终产品，对金属产品制造业部门中间产品的完全消耗量","为生产批发零售贸易、住宿和餐饮业部门单位最终产品，对机械设备制造业部门中间产品的完全消耗量","为生产批发零售贸易、住宿和餐饮业部门单位最终产品，对建筑业部门中间产品的完全消耗量","为生产批发零售贸易、住宿和餐饮业部门单位最终产品，对运输仓储邮政、信息传输、计算机服务和软件业部门中间产品的完全消耗量","为生产批发零售贸易、住宿和餐饮业部门单位最终产品，对批发零售贸易、住宿和餐饮业部门中间产品的完全消耗量","为生产批发零售贸易、住宿和餐饮业部门单位最终产品，对房地产业、租赁和商务服务业部门中间产品的完全消耗量","为生产批发零售贸易、住宿和餐饮业部门单位最终产品，对金融业部门中间产品的完全消耗量","为生产批发零售贸易、住宿和餐饮业部门单位最终产品，对其他服务业部门中间产品的完全消耗量"
//  "为生产房地产业、租赁和商务服务业部门单位最终产品，对农、林、牧、渔业部门中间产品的完全消耗量","为生产房地产业、租赁和商务服务业部门单位最终产品，对采矿业部门中间产品的完全消耗量","为生产房地产业、租赁和商务服务业部门单位最终产品，对食品、饮料制造及烟草制品业部门中间产品的完全消耗量","为生产房地产业、租赁和商务服务业部门单位最终产品，对纺织、服装及皮革产品制造业部门中间产品的完全消耗量","为生产房地产业、租赁和商务服务业部门单位最终产品，对其他制造业部门中间产品的完全消耗量","为生产房地产业、租赁和商务服务业部门单位最终产品，对电力、热力及水的生产和供应业部门中间产品的完全消耗量","为生产房地产业、租赁和商务服务业部门单位最终产品，对炼焦、燃气及石油加工业部门中间产品的完全消耗量","为生产房地产业、租赁和商务服务业部门单位最终产品，对化学工业部门中间产品的完全消耗量","为生产房地产业、租赁和商务服务业部门单位最终产品，对非金属矿物制品业部门中间产品的完全消耗量","为生产房地产业、租赁和商务服务业部门单位最终产品，对金属产品制造业部门中间产品的完全消耗量","为生产房地产业、租赁和商务服务业部门单位最终产品，对机械设备制造业部门中间产品的完全消耗量","为生产房地产业、租赁和商务服务业部门单位最终产品，对建筑业部门中间产品的完全消耗量","为生产房地产业、租赁和商务服务业部门单位最终产品，对运输仓储邮政、信息传输、计算机服务和软件业部门中间产品的完全消耗量","为生产房地产业、租赁和商务服务业部门单位最终产品，对批发零售贸易、住宿和餐饮业部门中间产品的完全消耗量","为生产房地产业、租赁和商务服务业部门单位最终产品，对房地产业、租赁和商务服务业部门中间产品的完全消耗量","为生产房地产业、租赁和商务服务业部门单位最终产品，对金融业部门中间产品的完全消耗量","为生产房地产业、租赁和商务服务业部门单位最终产品，对其他服务业部门中间产品的完全消耗量"
//  "为生产金融业部门单位最终产品，对农、林、牧、渔业部门中间产品的完全消耗量","为生产金融业部门单位最终产品，对采矿业部门中间产品的完全消耗量","为生产金融业部门单位最终产品，对食品、饮料制造及烟草制品业部门中间产品的完全消耗量","为生产金融业部门单位最终产品，对纺织、服装及皮革产品制造业部门中间产品的完全消耗量","为生产金融业部门单位最终产品，对其他制造业部门中间产品的完全消耗量","为生产金融业部门单位最终产品，对电力、热力及水的生产和供应业部门中间产品的完全消耗量","为生产金融业部门单位最终产品，对炼焦、燃气及石油加工业部门中间产品的完全消耗量","为生产金融业部门单位最终产品，对化学工业部门中间产品的完全消耗量","为生产金融业部门单位最终产品，对非金属矿物制品业部门中间产品的完全消耗量","为生产金融业部门单位最终产品，对金属产品制造业部门中间产品的完全消耗量","为生产金融业部门单位最终产品，对机械设备制造业部门中间产品的完全消耗量","为生产金融业部门单位最终产品，对建筑业部门中间产品的完全消耗量","为生产金融业部门单位最终产品，对运输仓储邮政、信息传输、计算机服务和软件业部门中间产品的完全消耗量","为生产金融业部门单位最终产品，对批发零售贸易、住宿和餐饮业部门中间产品的完全消耗量","为生产金融业部门单位最终产品，对房地产业、租赁和商务服务业部门中间产品的完全消耗量","为生产金融业部门单位最终产品，对金融业部门中间产品的完全消耗量","为生产金融业部门单位最终产品，对其他服务业部门中间产品的完全消耗量"
//  "为生产其他服务业部门单位最终产品，对农、林、牧、渔业部门中间产品的完全消耗量","为生产其他服务业部门单位最终产品，对采矿业部门中间产品的完全消耗量","为生产其他服务业部门单位最终产品，对食品、饮料制造及烟草制品业部门中间产品的完全消耗量","为生产其他服务业部门单位最终产品，对纺织、服装及皮革产品制造业部门中间产品的完全消耗量","为生产其他服务业部门单位最终产品，对其他制造业部门中间产品的完全消耗量","为生产其他服务业部门单位最终产品，对电力、热力及水的生产和供应业部门中间产品的完全消耗量","为生产其他服务业部门单位最终产品，对炼焦、燃气及石油加工业部门中间产品的完全消耗量","为生产其他服务业部门单位最终产品，对化学工业部门中间产品的完全消耗量","为生产其他服务业部门单位最终产品，对非金属矿物制品业部门中间产品的完全消耗量","为生产其他服务业部门单位最终产品，对金属产品制造业部门中间产品的完全消耗量","为生产其他服务业部门单位最终产品，对机械设备制造业部门中间产品的完全消耗量","为生产其他服务业部门单位最终产品，对建筑业部门中间产品的完全消耗量","为生产其他服务业部门单位最终产品，对运输仓储邮政、信息传输、计算机服务和软件业部门中间产品的完全消耗量","为生产其他服务业部门单位最终产品，对批发零售贸易、住宿和餐饮业部门中间产品的完全消耗量","为生产其他服务业部门单位最终产品，对房地产业、租赁和商务服务业部门中间产品的完全消耗量","为生产其他服务业部门单位最终产品，对金融业部门中间产品的完全消耗量","为生产其他服务业部门单位最终产品，对其他服务业部门中间产品的完全消耗量"
//
//  "实物交易资金运用_净出口","实物交易资金运用_增加值","实物交易资金运用_劳动者报酬","实物交易资金运用_工资及工资性收入","实物交易资金运用_单位社会保险付款","实物交易资金运用_生产税净额","实物交易资金运用_生产税","实物交易资金运用_生产补贴","实物交易资金运用_财产收入","实物交易资金运用_利息","实物交易资金运用_红利","实物交易资金运用_地租","实物交易资金运用_其他财产收入","实物交易资金运用_初次分配总收入","实物交易资金运用_经常转移","实物交易资金运用_收入税","实物交易资金运用_社会保险缴款","实物交易资金运用_社会保险福利","实物交易资金运用_社会补助","实物交易资金运用_其他经常转移","实物交易资金运用_可支配总收入","实物交易资金运用_最终消费","实物交易资金运用_居民消费","实物交易资金运用_政府消费","实物交易资金运用_总储蓄","实物交易资金运用_资本转移","实物交易资金运用_投资性补助","实物交易资金运用_其他资本转移","实物交易资金运用_资本形成总额","实物交易资金运用_固定资本形成总额","实物交易资金运用_存货增加","实物交易资金运用_其他非金融资产获得减处置","实物交易资金运用_净金融投资"
//  "实物交易资金来源_净出口","实物交易资金来源_增加值","实物交易资金来源_劳动者报酬","实物交易资金来源_工资及工资性收入","实物交易资金来源_单位社会保险付款","实物交易资金来源_生产税净额","实物交易资金来源_生产税","实物交易资金来源_生产补贴","实物交易资金来源_财产收入","实物交易资金来源_利息","实物交易资金来源_红利","实物交易资金来源_地租","实物交易资金来源_其他财产收入","实物交易资金来源_初次分配总收入","实物交易资金来源_经常转移","实物交易资金来源_收入税","实物交易资金来源_社会保险缴款","实物交易资金来源_社会保险福利","实物交易资金来源_社会补助","实物交易资金来源_其他经常转移","实物交易资金来源_可支配总收入","实物交易资金来源_最终消费","实物交易资金来源_居民消费","实物交易资金来源_政府消费","实物交易资金来源_总储蓄","实物交易资金来源_资本转移","实物交易资金来源_投资性补助","实物交易资金来源_其他资本转移","实物交易资金来源_资本形成总额","实物交易资金来源_固定资本形成总额","实物交易资金来源_存货增加","实物交易资金来源_其他非金融资产获得减处置","实物交易资金来源_净金融投资"
//
//  "非金融企业部门实物交易资金运用_净出口","非金融企业部门实物交易资金运用_增加值","非金融企业部门实物交易资金运用_劳动者报酬","非金融企业部门实物交易资金运用_工资及工资性收入","非金融企业部门实物交易资金运用_单位社会保险付款","非金融企业部门实物交易资金运用_生产税净额","非金融企业部门实物交易资金运用_生产税","非金融企业部门实物交易资金运用_生产补贴","非金融企业部门实物交易资金运用_财产收入","非金融企业部门实物交易资金运用_利息","非金融企业部门实物交易资金运用_红利","非金融企业部门实物交易资金运用_地租","非金融企业部门实物交易资金运用_其他财产收入","非金融企业部门实物交易资金运用_初次分配总收入","非金融企业部门实物交易资金运用_经常转移","非金融企业部门实物交易资金运用_收入税","非金融企业部门实物交易资金运用_社会保险缴款","非金融企业部门实物交易资金运用_社会保险福利","非金融企业部门实物交易资金运用_社会补助","非金融企业部门实物交易资金运用_其他经常转移","非金融企业部门实物交易资金运用_可支配总收入","非金融企业部门实物交易资金运用_最终消费","非金融企业部门实物交易资金运用_居民消费","非金融企业部门实物交易资金运用_政府消费","非金融企业部门实物交易资金运用_总储蓄","非金融企业部门实物交易资金运用_资本转移","非金融企业部门实物交易资金运用_投资性补助","非金融企业部门实物交易资金运用_其他资本转移","非金融企业部门实物交易资金运用_资本形成总额","非金融企业部门实物交易资金运用_固定资本形成总额","非金融企业部门实物交易资金运用_存货增加","非金融企业部门实物交易资金运用_其他非金融资产获得减处置","非金融企业部门实物交易资金运用_净金融投资"
//  "非金融企业部门实物交易资金来源_净出口","非金融企业部门实物交易资金来源_增加值","非金融企业部门实物交易资金来源_劳动者报酬","非金融企业部门实物交易资金来源_工资及工资性收入","非金融企业部门实物交易资金来源_单位社会保险付款","非金融企业部门实物交易资金来源_生产税净额","非金融企业部门实物交易资金来源_生产税","非金融企业部门实物交易资金来源_生产补贴","非金融企业部门实物交易资金来源_财产收入","非金融企业部门实物交易资金来源_利息","非金融企业部门实物交易资金来源_红利","非金融企业部门实物交易资金来源_地租","非金融企业部门实物交易资金来源_其他财产收入","非金融企业部门实物交易资金来源_初次分配总收入","非金融企业部门实物交易资金来源_经常转移","非金融企业部门实物交易资金来源_收入税","非金融企业部门实物交易资金来源_社会保险缴款","非金融企业部门实物交易资金来源_社会保险福利","非金融企业部门实物交易资金来源_社会补助","非金融企业部门实物交易资金来源_其他经常转移","非金融企业部门实物交易资金来源_可支配总收入","非金融企业部门实物交易资金来源_最终消费","非金融企业部门实物交易资金来源_居民消费","非金融企业部门实物交易资金来源_政府消费","非金融企业部门实物交易资金来源_总储蓄","非金融企业部门实物交易资金来源_资本转移","非金融企业部门实物交易资金来源_投资性补助","非金融企业部门实物交易资金来源_其他资本转移","非金融企业部门实物交易资金来源_资本形成总额","非金融企业部门实物交易资金来源_固定资本形成总额","非金融企业部门实物交易资金来源_存货增加","非金融企业部门实物交易资金来源_其他非金融资产获得减处置","非金融企业部门实物交易资金来源_净金融投资"
//
//  "金融机构部门实物交易资金运用_净出口","金融机构部门实物交易资金运用_增加值","金融机构部门实物交易资金运用_劳动者报酬","金融机构部门实物交易资金运用_工资及工资性收入","金融机构部门实物交易资金运用_单位社会保险付款","金融机构部门实物交易资金运用_生产税净额","金融机构部门实物交易资金运用_生产税","金融机构部门实物交易资金运用_生产补贴","金融机构部门实物交易资金运用_财产收入","金融机构部门实物交易资金运用_利息","金融机构部门实物交易资金运用_红利","金融机构部门实物交易资金运用_地租","金融机构部门实物交易资金运用_其他财产收入","金融机构部门实物交易资金运用_初次分配总收入","金融机构部门实物交易资金运用_经常转移","金融机构部门实物交易资金运用_收入税","金融机构部门实物交易资金运用_社会保险缴款","金融机构部门实物交易资金运用_社会保险福利","金融机构部门实物交易资金运用_社会补助","金融机构部门实物交易资金运用_其他经常转移","金融机构部门实物交易资金运用_可支配总收入","金融机构部门实物交易资金运用_最终消费","金融机构部门实物交易资金运用_居民消费","金融机构部门实物交易资金运用_政府消费","金融机构部门实物交易资金运用_总储蓄","金融机构部门实物交易资金运用_资本转移","金融机构部门实物交易资金运用_投资性补助","金融机构部门实物交易资金运用_其他资本转移","金融机构部门实物交易资金运用_资本形成总额","金融机构部门实物交易资金运用_固定资本形成总额","金融机构部门实物交易资金运用_存货增加","金融机构部门实物交易资金运用_其他非金融资产获得减处置","金融机构部门实物交易资金运用_净金融投资"
//  "金融机构部门实物交易资金来源_净出口","金融机构部门实物交易资金来源_增加值","金融机构部门实物交易资金来源_劳动者报酬","金融机构部门实物交易资金来源_工资及工资性收入","金融机构部门实物交易资金来源_单位社会保险付款","金融机构部门实物交易资金来源_生产税净额","金融机构部门实物交易资金来源_生产税","金融机构部门实物交易资金来源_生产补贴","金融机构部门实物交易资金来源_财产收入","金融机构部门实物交易资金来源_利息","金融机构部门实物交易资金来源_红利","金融机构部门实物交易资金来源_地租","金融机构部门实物交易资金来源_其他财产收入","金融机构部门实物交易资金来源_初次分配总收入","金融机构部门实物交易资金来源_经常转移","金融机构部门实物交易资金来源_收入税","金融机构部门实物交易资金来源_社会保险缴款","金融机构部门实物交易资金来源_社会保险福利","金融机构部门实物交易资金来源_社会补助","金融机构部门实物交易资金来源_其他经常转移","金融机构部门实物交易资金来源_可支配总收入","金融机构部门实物交易资金来源_最终消费","金融机构部门实物交易资金来源_居民消费","金融机构部门实物交易资金来源_政府消费","金融机构部门实物交易资金来源_总储蓄","金融机构部门实物交易资金来源_资本转移","金融机构部门实物交易资金来源_投资性补助","金融机构部门实物交易资金来源_其他资本转移","金融机构部门实物交易资金来源_资本形成总额","金融机构部门实物交易资金来源_固定资本形成总额","金融机构部门实物交易资金来源_存货增加","金融机构部门实物交易资金来源_其他非金融资产获得减处置","金融机构部门实物交易资金来源_净金融投资"
//
//  "政府部门实物交易资金运用_净出口","政府部门实物交易资金运用_增加值","政府部门实物交易资金运用_劳动者报酬","政府部门实物交易资金运用_工资及工资性收入","政府部门实物交易资金运用_单位社会保险付款","政府部门实物交易资金运用_生产税净额","政府部门实物交易资金运用_生产税","政府部门实物交易资金运用_生产补贴","政府部门实物交易资金运用_财产收入","政府部门实物交易资金运用_利息","政府部门实物交易资金运用_红利","政府部门实物交易资金运用_地租","政府部门实物交易资金运用_其他财产收入","政府部门实物交易资金运用_初次分配总收入","政府部门实物交易资金运用_经常转移","政府部门实物交易资金运用_收入税","政府部门实物交易资金运用_社会保险缴款","政府部门实物交易资金运用_社会保险福利","政府部门实物交易资金运用_社会补助","政府部门实物交易资金运用_其他经常转移","政府部门实物交易资金运用_可支配总收入","政府部门实物交易资金运用_最终消费","政府部门实物交易资金运用_居民消费","政府部门实物交易资金运用_政府消费","政府部门实物交易资金运用_总储蓄","政府部门实物交易资金运用_资本转移","政府部门实物交易资金运用_投资性补助","政府部门实物交易资金运用_其他资本转移","政府部门实物交易资金运用_资本形成总额","政府部门实物交易资金运用_固定资本形成总额","政府部门实物交易资金运用_存货增加","政府部门实物交易资金运用_其他非金融资产获得减处置","政府部门实物交易资金运用_净金融投资"
//  "政府部门实物交易资金来源_净出口","政府部门实物交易资金来源_增加值","政府部门实物交易资金来源_劳动者报酬","政府部门实物交易资金来源_工资及工资性收入","政府部门实物交易资金来源_单位社会保险付款","政府部门实物交易资金来源_生产税净额","政府部门实物交易资金来源_生产税","政府部门实物交易资金来源_生产补贴","政府部门实物交易资金来源_财产收入","政府部门实物交易资金来源_利息","政府部门实物交易资金来源_红利","政府部门实物交易资金来源_地租","政府部门实物交易资金来源_其他财产收入","政府部门实物交易资金来源_初次分配总收入","政府部门实物交易资金来源_经常转移","政府部门实物交易资金来源_收入税","政府部门实物交易资金来源_社会保险缴款","政府部门实物交易资金来源_社会保险福利","政府部门实物交易资金来源_社会补助","政府部门实物交易资金来源_其他经常转移","政府部门实物交易资金来源_可支配总收入","政府部门实物交易资金来源_最终消费","政府部门实物交易资金来源_居民消费","政府部门实物交易资金来源_政府消费","政府部门实物交易资金来源_总储蓄","政府部门实物交易资金来源_资本转移","政府部门实物交易资金来源_投资性补助","政府部门实物交易资金来源_其他资本转移","政府部门实物交易资金来源_资本形成总额","政府部门实物交易资金来源_固定资本形成总额","政府部门实物交易资金来源_存货增加","政府部门实物交易资金来源_其他非金融资产获得减处置","政府部门实物交易资金来源_净金融投资"
//
//  "住户部门实物交易资金运用_净出口","住户部门实物交易资金运用_增加值","住户部门实物交易资金运用_劳动者报酬","住户部门实物交易资金运用_工资及工资性收入","住户部门实物交易资金运用_单位社会保险付款","住户部门实物交易资金运用_生产税净额","住户部门实物交易资金运用_生产税","住户部门实物交易资金运用_生产补贴","住户部门实物交易资金运用_财产收入","住户部门实物交易资金运用_利息","住户部门实物交易资金运用_红利","住户部门实物交易资金运用_地租","住户部门实物交易资金运用_其他财产收入","住户部门实物交易资金运用_初次分配总收入","住户部门实物交易资金运用_经常转移","住户部门实物交易资金运用_收入税","住户部门实物交易资金运用_社会保险缴款","住户部门实物交易资金运用_社会保险福利","住户部门实物交易资金运用_社会补助","住户部门实物交易资金运用_其他经常转移","住户部门实物交易资金运用_可支配总收入","住户部门实物交易资金运用_最终消费","住户部门实物交易资金运用_居民消费","住户部门实物交易资金运用_政府消费","住户部门实物交易资金运用_总储蓄","住户部门实物交易资金运用_资本转移","住户部门实物交易资金运用_投资性补助","住户部门实物交易资金运用_其他资本转移","住户部门实物交易资金运用_资本形成总额","住户部门实物交易资金运用_固定资本形成总额","住户部门实物交易资金运用_存货增加","住户部门实物交易资金运用_其他非金融资产获得减处置","住户部门实物交易资金运用_净金融投资"
//  "住户部门实物交易资金来源_净出口","住户部门实物交易资金来源_增加值","住户部门实物交易资金来源_劳动者报酬","住户部门实物交易资金来源_工资及工资性收入","住户部门实物交易资金来源_单位社会保险付款","住户部门实物交易资金来源_生产税净额","住户部门实物交易资金来源_生产税","住户部门实物交易资金来源_生产补贴","住户部门实物交易资金来源_财产收入","住户部门实物交易资金来源_利息","住户部门实物交易资金来源_红利","住户部门实物交易资金来源_地租","住户部门实物交易资金来源_其他财产收入","住户部门实物交易资金来源_初次分配总收入","住户部门实物交易资金来源_经常转移","住户部门实物交易资金来源_收入税","住户部门实物交易资金来源_社会保险缴款","住户部门实物交易资金来源_社会保险福利","住户部门实物交易资金来源_社会补助","住户部门实物交易资金来源_其他经常转移","住户部门实物交易资金来源_可支配总收入","住户部门实物交易资金来源_最终消费","住户部门实物交易资金来源_居民消费","住户部门实物交易资金来源_政府消费","住户部门实物交易资金来源_总储蓄","住户部门实物交易资金来源_资本转移","住户部门实物交易资金来源_投资性补助","住户部门实物交易资金来源_其他资本转移","住户部门实物交易资金来源_资本形成总额","住户部门实物交易资金来源_固定资本形成总额","住户部门实物交易资金来源_存货增加","住户部门实物交易资金来源_其他非金融资产获得减处置","住户部门实物交易资金来源_净金融投资"
//
//  "国内实物交易资金运用_净出口","国内实物交易资金运用_增加值","国内实物交易资金运用_劳动者报酬","国内实物交易资金运用_工资及工资性收入","国内实物交易资金运用_单位社会保险付款","国内实物交易资金运用_生产税净额","国内实物交易资金运用_生产税","国内实物交易资金运用_生产补贴","国内实物交易资金运用_财产收入","国内实物交易资金运用_利息","国内实物交易资金运用_红利","国内实物交易资金运用_地租","国内实物交易资金运用_其他财产收入","国内实物交易资金运用_初次分配总收入","国内实物交易资金运用_经常转移","国内实物交易资金运用_收入税","国内实物交易资金运用_社会保险缴款","国内实物交易资金运用_社会保险福利","国内实物交易资金运用_社会补助","国内实物交易资金运用_其他经常转移","国内实物交易资金运用_可支配总收入","国内实物交易资金运用_最终消费","国内实物交易资金运用_居民消费","国内实物交易资金运用_政府消费","国内实物交易资金运用_总储蓄","国内实物交易资金运用_资本转移","国内实物交易资金运用_投资性补助","国内实物交易资金运用_其他资本转移","国内实物交易资金运用_资本形成总额","国内实物交易资金运用_固定资本形成总额","国内实物交易资金运用_存货增加","国内实物交易资金运用_其他非金融资产获得减处置","国内实物交易资金运用_净金融投资"
//  "国内实物交易资金来源_净出口","国内实物交易资金来源_增加值","国内实物交易资金来源_劳动者报酬","国内实物交易资金来源_工资及工资性收入","国内实物交易资金来源_单位社会保险付款","国内实物交易资金来源_生产税净额","国内实物交易资金来源_生产税","国内实物交易资金来源_生产补贴","国内实物交易资金来源_财产收入","国内实物交易资金来源_利息","国内实物交易资金来源_红利","国内实物交易资金来源_地租","国内实物交易资金来源_其他财产收入","国内实物交易资金来源_初次分配总收入","国内实物交易资金来源_经常转移","国内实物交易资金来源_收入税","国内实物交易资金来源_社会保险缴款","国内实物交易资金来源_社会保险福利","国内实物交易资金来源_社会补助","国内实物交易资金来源_其他经常转移","国内实物交易资金来源_可支配总收入","国内实物交易资金来源_最终消费","国内实物交易资金来源_居民消费","国内实物交易资金来源_政府消费","国内实物交易资金来源_总储蓄","国内实物交易资金来源_资本转移","国内实物交易资金来源_投资性补助","国内实物交易资金来源_其他资本转移","国内实物交易资金来源_资本形成总额","国内实物交易资金来源_固定资本形成总额","国内实物交易资金来源_存货增加","国内实物交易资金来源_其他非金融资产获得减处置","国内实物交易资金来源_净金融投资"
//
//  "国外部门实物交易资金运用_净出口","国外部门实物交易资金运用_增加值","国外部门实物交易资金运用_劳动者报酬","国外部门实物交易资金运用_工资及工资性收入","国外部门实物交易资金运用_单位社会保险付款","国外部门实物交易资金运用_生产税净额","国外部门实物交易资金运用_生产税","国外部门实物交易资金运用_生产补贴","国外部门实物交易资金运用_财产收入","国外部门实物交易资金运用_利息","国外部门实物交易资金运用_红利","国外部门实物交易资金运用_地租","国外部门实物交易资金运用_其他财产收入","国外部门实物交易资金运用_初次分配总收入","国外部门实物交易资金运用_经常转移","国外部门实物交易资金运用_收入税","国外部门实物交易资金运用_社会保险缴款","国外部门实物交易资金运用_社会保险福利","国外部门实物交易资金运用_社会补助","国外部门实物交易资金运用_其他经常转移","国外部门实物交易资金运用_可支配总收入","国外部门实物交易资金运用_最终消费","国外部门实物交易资金运用_居民消费","国外部门实物交易资金运用_政府消费","国外部门实物交易资金运用_总储蓄","国外部门实物交易资金运用_资本转移","国外部门实物交易资金运用_投资性补助","国外部门实物交易资金运用_其他资本转移","国外部门实物交易资金运用_资本形成总额","国外部门实物交易资金运用_固定资本形成总额","国外部门实物交易资金运用_存货增加","国外部门实物交易资金运用_其他非金融资产获得减处置","国外部门实物交易资金运用_净金融投资"
//  "国外部门实物交易资金来源_净出口","国外部门实物交易资金来源_增加值","国外部门实物交易资金来源_劳动者报酬","国外部门实物交易资金来源_工资及工资性收入","国外部门实物交易资金来源_单位社会保险付款","国外部门实物交易资金来源_生产税净额","国外部门实物交易资金来源_生产税","国外部门实物交易资金来源_生产补贴","国外部门实物交易资金来源_财产收入","国外部门实物交易资金来源_利息","国外部门实物交易资金来源_红利","国外部门实物交易资金来源_地租","国外部门实物交易资金来源_其他财产收入","国外部门实物交易资金来源_初次分配总收入","国外部门实物交易资金来源_经常转移","国外部门实物交易资金来源_收入税","国外部门实物交易资金来源_社会保险缴款","国外部门实物交易资金来源_社会保险福利","国外部门实物交易资金来源_社会补助","国外部门实物交易资金来源_其他经常转移","国外部门实物交易资金来源_可支配总收入","国外部门实物交易资金来源_最终消费","国外部门实物交易资金来源_居民消费","国外部门实物交易资金来源_政府消费","国外部门实物交易资金来源_总储蓄","国外部门实物交易资金来源_资本转移","国外部门实物交易资金来源_投资性补助","国外部门实物交易资金来源_其他资本转移","国外部门实物交易资金来源_资本形成总额","国外部门实物交易资金来源_固定资本形成总额","国外部门实物交易资金来源_存货增加","国外部门实物交易资金来源_其他非金融资产获得减处置","国外部门实物交易资金来源_净金融投资"
//
//  "金融交易资金运用_净金融投资","金融交易资金运用_资金运用","金融交易资金运用_资金来源","金融交易资金运用_通货","金融交易资金运用_存款","金融交易资金运用_贷款","金融交易资金运用_证券","金融交易资金运用_证券投资基金份额","金融交易资金运用_证券公司客户保证金","金融交易资金运用_保险准备金","金融交易资金运用_未贴现的银行承兑汇票","金融交易资金运用_金融机构往来","金融交易资金运用_准备金","金融交易资金运用_库存现金","金融交易资金运用_中央银行贷款","金融交易资金运用_其他(净)","金融交易资金运用_直接投资","金融交易资金运用_其他对外债权债务","金融交易资金运用_国际储备资产","金融交易资金运用_国际收支错误与遗漏"
//  "金融交易资金来源_净金融投资","金融交易资金来源_资金运用","金融交易资金来源_资金来源","金融交易资金来源_通货","金融交易资金来源_存款","金融交易资金来源_贷款","金融交易资金来源_证券","金融交易资金来源_证券投资基金份额","金融交易资金来源_证券公司客户保证金","金融交易资金来源_保险准备金","金融交易资金来源_未贴现的银行承兑汇票","金融交易资金来源_金融机构往来","金融交易资金来源_准备金","金融交易资金来源_库存现金","金融交易资金来源_中央银行贷款","金融交易资金来源_其他(净)","金融交易资金来源_直接投资","金融交易资金来源_其他对外债权债务","金融交易资金来源_国际储备资产","金融交易资金来源_国际收支错误与遗漏"
//
//  "非金融企业部门金融交易资金运用_净金融投资","非金融企业部门金融交易资金运用_资金运用","非金融企业部门金融交易资金运用_资金来源","非金融企业部门金融交易资金运用_通货","非金融企业部门金融交易资金运用_存款","非金融企业部门金融交易资金运用_贷款","非金融企业部门金融交易资金运用_证券","非金融企业部门金融交易资金运用_证券投资基金份额","非金融企业部门金融交易资金运用_证券公司客户保证金","非金融企业部门金融交易资金运用_保险准备金","非金融企业部门金融交易资金运用_未贴现的银行承兑汇票","非金融企业部门金融交易资金运用_金融机构往来","非金融企业部门金融交易资金运用_准备金","非金融企业部门金融交易资金运用_库存现金","非金融企业部门金融交易资金运用_中央银行贷款","非金融企业部门金融交易资金运用_其他(净)","非金融企业部门金融交易资金运用_直接投资","非金融企业部门金融交易资金运用_其他对外债权债务","非金融企业部门金融交易资金运用_国际储备资产","非金融企业部门金融交易资金运用_国际收支错误与遗漏"
//  "非金融企业部门金融交易资金来源_净金融投资","非金融企业部门金融交易资金来源_资金运用","非金融企业部门金融交易资金来源_资金来源","非金融企业部门金融交易资金来源_通货","非金融企业部门金融交易资金来源_存款","非金融企业部门金融交易资金来源_贷款","非金融企业部门金融交易资金来源_证券","非金融企业部门金融交易资金来源_证券投资基金份额","非金融企业部门金融交易资金来源_证券公司客户保证金","非金融企业部门金融交易资金来源_保险准备金","非金融企业部门金融交易资金来源_未贴现的银行承兑汇票","非金融企业部门金融交易资金来源_金融机构往来","非金融企业部门金融交易资金来源_准备金","非金融企业部门金融交易资金来源_库存现金","非金融企业部门金融交易资金来源_中央银行贷款","非金融企业部门金融交易资金来源_其他(净)","非金融企业部门金融交易资金来源_直接投资","非金融企业部门金融交易资金来源_其他对外债权债务","非金融企业部门金融交易资金来源_国际储备资产","非金融企业部门金融交易资金来源_国际收支错误与遗漏"
//
//  "金融机构部门金融交易资金运用_净金融投资","金融机构部门金融交易资金运用_资金运用","金融机构部门金融交易资金运用_资金来源","金融机构部门金融交易资金运用_通货","金融机构部门金融交易资金运用_存款","金融机构部门金融交易资金运用_贷款","金融机构部门金融交易资金运用_证券","金融机构部门金融交易资金运用_证券投资基金份额","金融机构部门金融交易资金运用_证券公司客户保证金","金融机构部门金融交易资金运用_保险准备金","金融机构部门金融交易资金运用_未贴现的银行承兑汇票","金融机构部门金融交易资金运用_金融机构往来","金融机构部门金融交易资金运用_准备金","金融机构部门金融交易资金运用_库存现金","金融机构部门金融交易资金运用_中央银行贷款","金融机构部门金融交易资金运用_其他(净)","金融机构部门金融交易资金运用_直接投资","金融机构部门金融交易资金运用_其他对外债权债务","金融机构部门金融交易资金运用_国际储备资产","金融机构部门金融交易资金运用_国际收支错误与遗漏"
//  "金融机构部门金融交易资金来源_净金融投资","金融机构部门金融交易资金来源_资金运用","金融机构部门金融交易资金来源_资金来源","金融机构部门金融交易资金来源_通货","金融机构部门金融交易资金来源_存款","金融机构部门金融交易资金来源_贷款","金融机构部门金融交易资金来源_证券","金融机构部门金融交易资金来源_证券投资基金份额","金融机构部门金融交易资金来源_证券公司客户保证金","金融机构部门金融交易资金来源_保险准备金","金融机构部门金融交易资金来源_未贴现的银行承兑汇票","金融机构部门金融交易资金来源_金融机构往来","金融机构部门金融交易资金来源_准备金","金融机构部门金融交易资金来源_库存现金","金融机构部门金融交易资金来源_中央银行贷款","金融机构部门金融交易资金来源_其他(净)","金融机构部门金融交易资金来源_直接投资","金融机构部门金融交易资金来源_其他对外债权债务","金融机构部门金融交易资金来源_国际储备资产","金融机构部门金融交易资金来源_国际收支错误与遗漏"
//
//  "政府部门金融交易资金运用_净金融投资","政府部门金融交易资金运用_资金运用","政府部门金融交易资金运用_资金来源","政府部门金融交易资金运用_通货","政府部门金融交易资金运用_存款","政府部门金融交易资金运用_贷款","政府部门金融交易资金运用_证券","政府部门金融交易资金运用_证券投资基金份额","政府部门金融交易资金运用_证券公司客户保证金","政府部门金融交易资金运用_保险准备金","政府部门金融交易资金运用_未贴现的银行承兑汇票","政府部门金融交易资金运用_金融机构往来","政府部门金融交易资金运用_准备金","政府部门金融交易资金运用_库存现金","政府部门金融交易资金运用_中央银行贷款","政府部门金融交易资金运用_其他(净)","政府部门金融交易资金运用_直接投资","政府部门金融交易资金运用_其他对外债权债务","政府部门金融交易资金运用_国际储备资产","政府部门金融交易资金运用_国际收支错误与遗漏"
//  "政府部门金融交易资金来源_净金融投资","政府部门金融交易资金来源_资金运用","政府部门金融交易资金来源_资金来源","政府部门金融交易资金来源_通货","政府部门金融交易资金来源_存款","政府部门金融交易资金来源_贷款","政府部门金融交易资金来源_证券","政府部门金融交易资金来源_证券投资基金份额","政府部门金融交易资金来源_证券公司客户保证金","政府部门金融交易资金来源_保险准备金","政府部门金融交易资金来源_未贴现的银行承兑汇票","政府部门金融交易资金来源_金融机构往来","政府部门金融交易资金来源_准备金","政府部门金融交易资金来源_库存现金","政府部门金融交易资金来源_中央银行贷款","政府部门金融交易资金来源_其他(净)","政府部门金融交易资金来源_直接投资","政府部门金融交易资金来源_其他对外债权债务","政府部门金融交易资金来源_国际储备资产","政府部门金融交易资金来源_国际收支错误与遗漏"
//
//  "住户部门金融交易资金运用_净金融投资","住户部门金融交易资金运用_资金运用","住户部门金融交易资金运用_资金来源","住户部门金融交易资金运用_通货","住户部门金融交易资金运用_存款","住户部门金融交易资金运用_贷款","住户部门金融交易资金运用_证券","住户部门金融交易资金运用_证券投资基金份额","住户部门金融交易资金运用_证券公司客户保证金","住户部门金融交易资金运用_保险准备金","住户部门金融交易资金运用_未贴现的银行承兑汇票","住户部门金融交易资金运用_金融机构往来","住户部门金融交易资金运用_准备金","住户部门金融交易资金运用_库存现金","住户部门金融交易资金运用_中央银行贷款","住户部门金融交易资金运用_其他(净)","住户部门金融交易资金运用_直接投资","住户部门金融交易资金运用_其他对外债权债务","住户部门金融交易资金运用_国际储备资产","住户部门金融交易资金运用_国际收支错误与遗漏"
//  "住户部门金融交易资金来源_净金融投资","住户部门金融交易资金来源_资金运用","住户部门金融交易资金来源_资金来源","住户部门金融交易资金来源_通货","住户部门金融交易资金来源_存款","住户部门金融交易资金来源_贷款","住户部门金融交易资金来源_证券","住户部门金融交易资金来源_证券投资基金份额","住户部门金融交易资金来源_证券公司客户保证金","住户部门金融交易资金来源_保险准备金","住户部门金融交易资金来源_未贴现的银行承兑汇票","住户部门金融交易资金来源_金融机构往来","住户部门金融交易资金来源_准备金","住户部门金融交易资金来源_库存现金","住户部门金融交易资金来源_中央银行贷款","住户部门金融交易资金来源_其他(净)","住户部门金融交易资金来源_直接投资","住户部门金融交易资金来源_其他对外债权债务","住户部门金融交易资金来源_国际储备资产","住户部门金融交易资金来源_国际收支错误与遗漏"
//
//  "国内金融交易资金运用_净金融投资","国内金融交易资金运用_资金运用","国内金融交易资金运用_资金来源","国内金融交易资金运用_通货","国内金融交易资金运用_存款","国内金融交易资金运用_贷款","国内金融交易资金运用_证券","国内金融交易资金运用_证券投资基金份额","国内金融交易资金运用_证券公司客户保证金","国内金融交易资金运用_保险准备金","国内金融交易资金运用_未贴现的银行承兑汇票","国内金融交易资金运用_金融机构往来","国内金融交易资金运用_准备金","国内金融交易资金运用_库存现金","国内金融交易资金运用_中央银行贷款","国内金融交易资金运用_其他(净)","国内金融交易资金运用_直接投资","国内金融交易资金运用_其他对外债权债务","国内金融交易资金运用_国际储备资产","国内金融交易资金运用_国际收支错误与遗漏"
//  "国内金融交易资金来源_净金融投资","国内金融交易资金来源_资金运用","国内金融交易资金来源_资金来源","国内金融交易资金来源_通货","国内金融交易资金来源_存款","国内金融交易资金来源_贷款","国内金融交易资金来源_证券","国内金融交易资金来源_证券投资基金份额","国内金融交易资金来源_证券公司客户保证金","国内金融交易资金来源_保险准备金","国内金融交易资金来源_未贴现的银行承兑汇票","国内金融交易资金来源_金融机构往来","国内金融交易资金来源_准备金","国内金融交易资金来源_库存现金","国内金融交易资金来源_中央银行贷款","国内金融交易资金来源_其他(净)","国内金融交易资金来源_直接投资","国内金融交易资金来源_其他对外债权债务","国内金融交易资金来源_国际储备资产","国内金融交易资金来源_国际收支错误与遗漏"
//
//  "国外部门金融交易资金运用_净金融投资","国外部门金融交易资金运用_资金运用","国外部门金融交易资金运用_资金来源","国外部门金融交易资金运用_通货","国外部门金融交易资金运用_存款","国外部门金融交易资金运用_贷款","国外部门金融交易资金运用_证券","国外部门金融交易资金运用_证券投资基金份额","国外部门金融交易资金运用_证券公司客户保证金","国外部门金融交易资金运用_保险准备金","国外部门金融交易资金运用_未贴现的银行承兑汇票","国外部门金融交易资金运用_金融机构往来","国外部门金融交易资金运用_准备金","国外部门金融交易资金运用_库存现金","国外部门金融交易资金运用_中央银行贷款","国外部门金融交易资金运用_其他(净)","国外部门金融交易资金运用_直接投资","国外部门金融交易资金运用_其他对外债权债务","国外部门金融交易资金运用_国际储备资产","国外部门金融交易资金运用_国际收支错误与遗漏"
//  "国外部门金融交易资金来源_净金融投资","国外部门金融交易资金来源_资金运用","国外部门金融交易资金来源_资金来源","国外部门金融交易资金来源_通货","国外部门金融交易资金来源_存款","国外部门金融交易资金来源_贷款","国外部门金融交易资金来源_证券","国外部门金融交易资金来源_证券投资基金份额","国外部门金融交易资金来源_证券公司客户保证金","国外部门金融交易资金来源_保险准备金","国外部门金融交易资金来源_未贴现的银行承兑汇票","国外部门金融交易资金来源_金融机构往来","国外部门金融交易资金来源_准备金","国外部门金融交易资金来源_库存现金","国外部门金融交易资金来源_中央银行贷款","国外部门金融交易资金来源_其他(净)","国外部门金融交易资金来源_直接投资","国外部门金融交易资金来源_其他对外债权债务","国外部门金融交易资金来源_国际储备资产","国外部门金融交易资金来源_国际收支错误与遗漏"
//
//
//  "经常项目差额(贷-借)","经常项目货物和服务差额(贷-借)","经常项目货物差额(贷-借)","经常项目服务差额(贷-借)","经常项目运输服务差额(贷-借)","经常项目旅游服务差额(贷-借)","经常项目通讯服务差额(贷-借)","经常项目建筑服务差额(贷-借)","经常项目保险服务差额(贷-借)","经常项目金融服务差额(贷-借)","经常项目计算机和信息服务差额(贷-借)","经常项目专有权利使用费和特许费差额(贷-借)","经常项目咨询服务差额(贷-借)","经常项目广告、宣传服务差额(贷-借)","经常项目电影、音像服务差额(贷-借)","经常项目其它商业服务差额(贷-借)","经常项目别处未提及的政府服务差额(贷-借)","经常项目收益差额(贷-借)","经常项目职工报酬收益差额(贷-借)","经常项目投资收益差额(贷-借)","经常项目经常转移差额(贷-借)","经常项目各级政府经常转移差额(贷-借)","经常项目其它部门经常转移差额(贷-借)"
//  "资本和金融项目差额(贷-借)","资本项目差额(贷-借)","金融项目差额(贷-借)","金融项目中直接投资差额(贷-借)","金融项目中我国在外直接投资差额(贷-借)","金融项目中外国在华直接投资差额(贷-借)","金融项目中证券投资差额(贷-借)","金融项目中证券投资的资产差额(贷-借)","金融项目中股本证券投资的资产差额(贷-借)","金融项目中债务证券投资的资产差额(贷-借)","金融项目中(中)长期债券的债务证券投资资产差额(贷-借)","金融项目中货币市场工具的债务证券投资资产差额(贷-借)","金融项目中证券投资的负债差额(贷-借)","金融项目中股本证券投资的负债差额(贷-借)","金融项目中债务证券投资的负债差额(贷-借)","金融项目中(中)长期债券的债务证券投资的负债差额(贷-借)","金融项目中货币市场工具的债务证券投资的负债差额(贷-借)","金融项目中其它投资差额(贷-借)","金融项目中其它投资的资产差额(贷-借)","金融项目中其它投资的贸易信贷资产差额(贷-借)","金融项目中其它投资的长期贸易信贷资产差额(贷-借)","金融项目中其它投资的短期贸易信贷资产差额(贷-借)","金融项目中其它投资的贷款资产差额(贷-借)","金融项目中其它投资的长期贷款资产差额(贷-借)","金融项目中其它投资的短期贷款资产差额(贷-借)","金融项目中其它投资的货币和存款资产差额(贷-借)","金融项目中其它投资的其它资产差额(贷-借)","金融项目中其它投资的长期其它资产差额(贷-借)","金融项目中其它投资的短期其它资产差额(贷-借)","金融项目中其它投资的负债差额(贷-借)","金融项目中其它投资的贸易信贷负债差额(贷-借)","金融项目中其它投资的长期贸易信贷负债差额(贷-借)","金融项目中其它投资的短期贸易信贷负债差额(贷-借)","金融项目中其它投资的贷款负债差额(贷-借)","金融项目中其它投资的长期贷款负债差额(贷-借)","金融项目中其它投资的短期贷款负债差额(贷-借)","金融项目中其它投资的货币和存款负债差额(贷-借)","金融项目中其它投资的其它负债差额(贷-借)","金融项目中其它投资的长期其它负债差额(贷-借)","金融项目中其它投资的短期其它负债差额(贷-借)"
//  "储备资产差额(贷-借)","储备资产中货币黄金差额(贷-借)","储备资产中特别提款权差额(贷-借)","储备资产在基金组织的储备头寸差额(贷-借)","储备资产中外汇差额(贷-借)","储备资产中其它债权差额(贷-借)"
//  "净误差与遗漏差额(贷-借)"
//
//  "贷方经常项目","贷方经常项目中货物和服务","贷方经常项目中货物","贷方经常项目中服务","贷方经常项目中运输服务","贷方经常项目中旅游服务","贷方经常项目中通讯服务","贷方经常项目中建筑服务","贷方经常项目中保险服务","贷方经常项目中金融服务","贷方经常项目中计算机和信息服务","贷方经常项目中专有权利使用费和特许费","贷方经常项目中咨询服务","贷方经常项目中广告、宣传服务","贷方经常项目中电影、音像服务","贷方经常项目中其它商业服务","贷方经常项目中别处未提及的政府服务","贷方经常项目中收益","贷方经常项目中职工报酬收益","贷方经常项目中投资收益","贷方经常项目中经常转移","贷方经常项目中各级政府经常转移","贷方经常项目中其它部门经常转移"
//  "贷方资本和金融项目","贷方资本项目","贷方金融项目","贷方金融项目中直接投资","贷方金融项目中我国在外直接投资","贷方金融项目中外国在华直接投资","贷方金融项目中证券投资","贷方金融项目中证券投资资产","贷方金融项目中证券投资的股本证券资产","贷方金融项目中证券投资的债务证券资产","贷方金融项目中证券投资的(中)长期债务证券资产","贷方金融项目中证券投资的货币市场工具债务证券资产","贷方金融项目中证券投资负债","贷方金融项目中证券投资的股本证券负债","贷方金融项目中证券投资的债务证券负债","贷方金融项目中证券投资的(中)长期债券证券负债","贷方金融项目中证券投资的货币市场工具债券证券负债","贷方金融项目中其它投资","贷方金融项目中其它投资资产","贷方金融项目中其它投资的贸易信贷资产","贷方金融项目中其它投资的长期贸易信贷资产","贷方金融项目中其它投资的短期贸易信贷资产","贷方金融项目中其它投资的贷款资产","贷方金融项目中其它投资的长期资产贷款","贷方金融项目中其它投资的短期贷款资产","贷方金融项目中其它投资的货币和存款资产","贷方金融项目中其它投资的其它资产","贷方金融项目中其它投资的中长期其它资产","贷方金融项目中其它投资的短期其它资产","贷方金融项目中其它投资的负债","贷方金融项目中其它投资的贸易信贷负债","贷方金融项目中其它投资长期贸易信贷负债","贷方金融项目中其它投资短期贸易信贷负债","贷方金融项目中其它投资贷款负债","贷方金融项目中其它投资长期贷款负债","贷方金融项目中其它投资短期贷款负债","贷方金融项目中其它投资货币和存款负债","贷方金融项目中其它投资的其它负债","贷方金融项目中其它投资的长期其它负债","贷方金融项目中其它投资的短期其它负债"
//  "贷方储备资产","贷方货币黄金储备资产","贷方特别提款权储备资产","贷方在基金组织的储备头寸储备资产","贷方外汇储备资产","贷方其它债权储备资产"
//  "贷方净误差与遗漏"
//
//  "借方经常项目","借方经常项目中货物和服务","借方经常项目中货物","借方经常项目中服务","借方经常项目中运输服务","借方经常项目中旅游服务","借方经常项目中通讯服务","借方经常项目中建筑服务","借方经常项目中保险服务","借方经常项目中金融服务","借方经常项目中计算机和信息服务","借方经常项目中专有权利使用费和特许费服务","借方经常项目中咨询服务","借方经常项目中广告、宣传服务","借方经常项目中电影、音像服务","借方经常项目中其它商业服务","借方经常项目中别处未提及的政府服务","借方经常项目中收益","借方经常项目中职工报酬","借方经常项目中投资收益","借方经常项目中经常转移","借方经常项目中各级政府经常转移","借方经常项目中其它部门经常转移"
//  "借方资本和金融项目","借方资本项目","借方金融项目","借方直接投资金融项目","借方金融项目我国在外直接投资","借方金融项目外国在华直接投资","借方金融项目的证券投资","借方金融项目中证券投资资产","借方金融项目中证券投资的股本证券资产","借方金融项目中证券投资的债务证券资产","借方金融项目中证券投资的中长期债务证券资产","借方金融项目中证券投资的货币市场工具债务证券资产","借方金融项目中证券投资负债","借方金融项目中证券投资的股本证券负债","借方金融项目中证券投资的债务证券负债","借方金融项目中证券投资的中长期债务证券负债","借方金融项目中证券投资的货币市场工具债务证券负债","借方金融项目中其它投资","借方金融项目中其它投资的资产","借方金融项目中其它投资的贸易信贷资产","借方金融项目中其它投资的长期贸易信贷资产","借方金融项目中其它投资的短期贸易信贷资产","借方金融项目中其它投资贷款资产","借方金融项目中其它投资长期贷款资产","借方金融项目中其它投资短期贷款资产","借方金融项目中其它投资货币和存款资产","借方金融项目中其它投资其它资产","借方金融项目中其它投资的长期其它资产","借方金融项目中其它投资的短期其它资产","借方金融项目其它投资中负债","借方金融项目其它投资的贸易信贷负债","借方金融项目的其它投资长期贸易信贷负债","借方金融项目其它投资的短期贸易信贷负债","借方金融项目中其它投资贷款负债","借方金融项目其它投资的长期贷款负债","借方金融项目其它投资中短期贷款负债","借方金融项目中其它投资货币和存款负债","借方金融项目其它投资中其它负债","借方金融项目其它投资长期其它负债","借方金融项目其它投资短期其它负债"
//  "借方储备资产","借方货币黄金储备资产","借方特别提款权储备资产","借方在基金组织的储备头寸储备资产","借方外汇储备资产","借方其它债权储备资产"
//  "借方净误差与遗漏"
//
//}
